from pathlib import Path
p=Path('src/App.tsx');s=p.read_text()
s=s.replace("import { aestraNations, aestraOrigins, applyAestraMonsterIdentity, AestraInfluence, AestraNation, AestraOrigin, valdoriaDepths, ValdoriaDepth } from './aestra'", "import { aestraNations, aestraOrigins, applyAestraMonsterIdentity, AestraInfluence, AestraNation, AestraOrigin, valdoriaDepths, ValdoriaDepth } from './aestra'\nimport { aestraEnvironments, aestraExposures, aestraWildOrigins, applyAestraWildIdentity, AestraEnvironment, AestraExposure, AestraWildOrigin } from './aestraWilds'")
s=s.replace("nation:'Garlond' as AestraNation", "nation:'Garlond' as AestraNation|'Aestra'")
s=s.replace("depth:'Market' as ValdoriaDepth", "depth:'Market' as ValdoriaDepth,environment:'Green Reaches' as AestraEnvironment,exposure:'Borderlands' as AestraExposure,wildOrigin:'Natural' as AestraWildOrigin")
s=s.replace("[nation,setNation]=useState<AestraNation>(initial.nation||'Garlond')", "[nation,setNation]=useState<AestraNation|'Aestra'>(initial.nation||'Garlond')")
s=s.replace("[depth,setDepth]=useState<ValdoriaDepth>(initial.depth||'Market'),[result,setResult]", "[depth,setDepth]=useState<ValdoriaDepth>(initial.depth||'Market'),[environment,setEnvironment]=useState<AestraEnvironment>(initial.environment||'Green Reaches'),[exposure,setExposure]=useState<AestraExposure>(initial.exposure||'Borderlands'),[wildOrigin,setWildOrigin]=useState<AestraWildOrigin>(initial.wildOrigin||'Natural'),[result,setResult]")
s=s.replace("{level,rank,soldierEquivalent,sp,complexity,combatStyle,theme,powerIntent,inspiration,setting,nation,origin,influence,depth}", "{level,rank,soldierEquivalent,sp,complexity,combatStyle,theme,powerIntent,inspiration,setting,nation,origin,influence,depth,environment,exposure,wildOrigin}")
s=s.replace("[level,rank,soldierEquivalent,sp,complexity,combatStyle,theme,powerIntent,inspiration,setting,nation,origin,influence,depth]", "[level,rank,soldierEquivalent,sp,complexity,combatStyle,theme,powerIntent,inspiration,setting,nation,origin,influence,depth,environment,exposure,wildOrigin]")
s=s.replace("if(setting==='Aestra') monster=applyAestraMonsterIdentity(monster,nation,origin,influence,depth)", "if(setting==='Aestra') monster=nation==='Aestra'?applyAestraWildIdentity(monster,environment,exposure,wildOrigin):applyAestraMonsterIdentity(monster,nation,origin,influence,depth)")
s=s.replace("Object.keys(aestraNations).map(n=><option key={n}>{n}</option>)", "[...Object.keys(aestraNations),'Aestra'].map(n=><option key={n}>{n}</option>)")
s=s.replace("setNation(e.target.value as AestraNation)", "setNation(e.target.value as AestraNation|'Aestra')")
needle="<label>Origin<select value={origin} onChange={e=>setOrigin(e.target.value as AestraOrigin)}>{aestraOrigins(nation).map(o=><option key={o}>{o}</option>)}</select></label>"
if needle in s:
 s=s.replace(needle,"{nation!=='Aestra'&&<label>Origin<select value={origin} onChange={e=>setOrigin(e.target.value as AestraOrigin)}>{aestraOrigins(nation as AestraNation).map(o=><option key={o}>{o}</option>)}</select></label>}{nation==='Aestra'&&<><label>Environment<select value={environment} onChange={e=>setEnvironment(e.target.value as AestraEnvironment)}>{aestraEnvironments.map(x=><option key={x}>{x}</option>)}</select></label><label>Exposure<select value={exposure} onChange={e=>setExposure(e.target.value as AestraExposure)}>{aestraExposures.map(x=><option key={x}>{x}</option>)}</select></label><label>Origin<select value={wildOrigin} onChange={e=>setWildOrigin(e.target.value as AestraWildOrigin)}>{aestraWildOrigins.map(x=><option key={x}>{x}</option>)}</select></label><p className=\"muted smallText\">Aestra here means lands outside direct national control. Environment changes the ecology and combat pattern; Exposure changes how strange or poorly understood it is, not simply its level.</p></>}")
else: raise SystemExit('origin UI needle missing')
s=s.replace("<label>Crystal influence<select", "{nation!=='Aestra'&&<label>Crystal influence<select")
s=s.replace("</select></label>{nation==='Valdoria'", "</select></label>}{nation==='Valdoria'")
p.write_text(s)
# trigger
