from pathlib import Path

p=Path('src/App.tsx')
s=p.read_text()

old="import { itemQualitySummary, monsterQualitySummary } from './generatorQuality'"
new="import { itemQualitySummary, monsterQualitySummary, validateItemDesign, validateMonsterDesign } from './generatorQuality'"
if old in s:
    s=s.replace(old,new,1)
elif 'validateMonsterDesign' not in s:
    raise SystemExit('generatorQuality import not found')

old_monster="const applyMonsterSetting=(monster:Monster):Monster=>setting!=='Aestra'?monster:(nation==='Aestra'?applyAestraWildIdentity(monster,environment,exposure,wildOrigin):applyAestraMonsterIdentity(monster,nation,origin,influence,depth));const make=()=>{const adjusted=powerAdjustedMonsterSettings(rank,complexity,soldierEquivalent,powerIntent);const hintedStyle=setting==='Aestra'&&combatStyle==='Mixed'?(nation==='Aestra'?aestraWildGenerationHint(environment).combatStyle:aestraGenerationHint(nation).combatStyle):combatStyle;const pattern=inspiration==='Official Pattern'?officialInspiredMonsterSettings(readStored<Monster[]>('fu-monsters',[]),level,sp,adjusted.rank,hintedStyle,adjusted.complexity):{style:hintedStyle,complexity:adjusted.complexity,attackCount:adjusted.complexity==='Simple'?1:adjusted.complexity==='Standard'?2:3,skillCount:99,spellCount:99,affinityCount:99,sampleCount:0,note:''};let chassis=generateMonster({level,rank:adjusted.rank,soldierEquivalent:adjusted.soldierEquivalent,species:sp,complexity:pattern.complexity,combatStyle:pattern.style});if(inspiration==='Official Pattern')chassis=applyOfficialMonsterStructure(chassis,pattern);let monster=applyMonsterTheme(chassis,theme==='Auto'?undefined:theme);monster=applyMonsterSetting(monster);monster={...monster,notes:[...(monster.notes||[]),...(setting==='Aestra'&&combatStyle==='Mixed'?[`Aestra generation hint: regional identity selected ${pattern.style} as the starting combat role because Combat Style was left Mixed.`]:[]),`Power intent: ${powerIntent}.${powerIntent==='Legendary'?' Legendary intent promotes the generated chassis to Champion.':''}`,...(pattern.note?[pattern.note]:[])]};setResult(monster)}"
new_monster="const applyMonsterSetting=(monster:Monster):Monster=>setting!=='Aestra'?monster:(nation==='Aestra'?applyAestraWildIdentity(monster,environment,exposure,wildOrigin):applyAestraMonsterIdentity(monster,nation,origin,influence,depth));const make=()=>{const adjusted=powerAdjustedMonsterSettings(rank,complexity,soldierEquivalent,powerIntent);const hintedStyle=setting==='Aestra'&&combatStyle==='Mixed'?(nation==='Aestra'?aestraWildGenerationHint(environment).combatStyle:aestraGenerationHint(nation).combatStyle):combatStyle;const pattern=inspiration==='Official Pattern'?officialInspiredMonsterSettings(readStored<Monster[]>('fu-monsters',[]),level,sp,adjusted.rank,hintedStyle,adjusted.complexity):{style:hintedStyle,complexity:adjusted.complexity,attackCount:adjusted.complexity==='Simple'?1:adjusted.complexity==='Standard'?2:3,skillCount:99,spellCount:99,affinityCount:99,sampleCount:0,note:''};const makeCandidate=()=>{let chassis=generateMonster({level,rank:adjusted.rank,soldierEquivalent:adjusted.soldierEquivalent,species:sp,complexity:pattern.complexity,combatStyle:pattern.style});if(inspiration==='Official Pattern')chassis=applyOfficialMonsterStructure(chassis,pattern);let monster=applyMonsterTheme(chassis,theme==='Auto'?undefined:theme);monster=applyMonsterSetting(monster);return {...monster,notes:[...(monster.notes||[]),...(setting==='Aestra'&&combatStyle==='Mixed'?[`Aestra generation hint: regional identity selected ${pattern.style} as the starting combat role because Combat Style was left Mixed.`]:[]),`Power intent: ${powerIntent}.${powerIntent==='Legendary'?' Legendary intent promotes the generated chassis to Champion.':''}`,...(pattern.note?[pattern.note]:[])]}};const candidates=Array.from({length:6},()=>makeCandidate());const monster=candidates.reduce((best,candidate)=>validateMonsterDesign(candidate).score>validateMonsterDesign(best).score?candidate:best);setResult({...monster,notes:[...(monster.notes||[]).filter(line=>!line.startsWith('Quality selection: ')),`Quality selection: best structural result selected from ${candidates.length} generated candidates (${validateMonsterDesign(monster).score}/100).`]})}"
if old_monster not in s:
    raise SystemExit('monster generation block not found')
s=s.replace(old_monster,new_monster,1)

old_item="const applyItemSetting=(item:AppItem):AppItem=>setting!=='Aestra'?item:(nation==='Aestra'?applyAestraWildItemIdentity(item,environment,exposure,wildOrigin):applyAestraNationItemIdentity(item,nation,origin,influence,depth));const generate=()=>{let budget=powerAdjustedItemBudget(maxCost,powerIntent);const pattern=inspiration==='Official Pattern'?officialInspiredItemBudget(readStored<AppItem[]>('fu-items',[]),type,budget):{maxCost:budget,sampleCount:0,martialRate:0.5,qualityRate:0.5,note:''};budget=pattern.maxCost;const makeCandidate=():AppItem=>type==='Weapon'&&weaponMethod==='Atlas Custom'?generateCustomWeapon({allowMartial,allowTransforming:powerIntent==='Legendary'?true:allowTransforming,preferredDamageType:damageType}):generateItem({type,maxCost:budget,allowMartial,preferredDamageType:damageType});let item:AppItem=inspiration==='Official Pattern'?chooseOfficialInspiredItemCandidate(Array.from({length:6},()=>makeCandidate()),pattern):makeCandidate();item=applyItemTheme(item,itemTheme==='Auto'?undefined:itemTheme);item={...item,breakdown:[...(item.breakdown||[]),`Power intent: ${powerIntent}.`,...(pattern.note?[pattern.note]:[])]};if(addMaterial){const material=generateMaterial({nature:materialNature,descriptorMode,element:descriptorMode==='Elemental'&&damageType!=='random'&&damageType!=='physical'?damageType:'Random',function:materialFunction});item={...item,material,origin:`Crafted using ${material.name.toLowerCase()}, a ${material.nature.toLowerCase()} material selected from the Natural Fantasy material tables.`,breakdown:[...(item.breakdown||[]).filter(line=>!line.startsWith('Concept material: ')),`Material: ${material.name} (authoritative material identity; does not alter equipment cost by itself).`]}}item=applyItemSetting(item);setResult(item)}"
new_item="const applyItemSetting=(item:AppItem):AppItem=>setting!=='Aestra'?item:(nation==='Aestra'?applyAestraWildItemIdentity(item,environment,exposure,wildOrigin):applyAestraNationItemIdentity(item,nation,origin,influence,depth));const generate=()=>{let budget=powerAdjustedItemBudget(maxCost,powerIntent);const pattern=inspiration==='Official Pattern'?officialInspiredItemBudget(readStored<AppItem[]>('fu-items',[]),type,budget):{maxCost:budget,sampleCount:0,martialRate:0.5,qualityRate:0.5,note:''};budget=pattern.maxCost;const makeBaseCandidate=():AppItem=>type==='Weapon'&&weaponMethod==='Atlas Custom'?generateCustomWeapon({allowMartial,allowTransforming:powerIntent==='Legendary'?true:allowTransforming,preferredDamageType:damageType}):generateItem({type,maxCost:budget,allowMartial,preferredDamageType:damageType});const makeCandidate=()=>{let item:AppItem=inspiration==='Official Pattern'?chooseOfficialInspiredItemCandidate(Array.from({length:6},()=>makeBaseCandidate()),pattern):makeBaseCandidate();item=applyItemTheme(item,itemTheme==='Auto'?undefined:itemTheme);item={...item,breakdown:[...(item.breakdown||[]),`Power intent: ${powerIntent}.`,...(pattern.note?[pattern.note]:[])]};if(addMaterial){const material=generateMaterial({nature:materialNature,descriptorMode,element:descriptorMode==='Elemental'&&damageType!=='random'&&damageType!=='physical'?damageType:'Random',function:materialFunction});item={...item,material,origin:`Crafted using ${material.name.toLowerCase()}, a ${material.nature.toLowerCase()} material selected from the Natural Fantasy material tables.`,breakdown:[...(item.breakdown||[]).filter(line=>!line.startsWith('Concept material: ')),`Material: ${material.name} (authoritative material identity; does not alter equipment cost by itself).`]}}return applyItemSetting(item)};const candidates=Array.from({length:6},()=>makeCandidate());const item=candidates.reduce((best,candidate)=>validateItemDesign(candidate).score>validateItemDesign(best).score?candidate:best);setResult({...item,breakdown:[...(item.breakdown||[]).filter(line=>!line.startsWith('Quality selection: ')),`Quality selection: best structural result selected from ${candidates.length} generated candidates (${validateItemDesign(item).score}/100).`]})}"
if old_item not in s:
    raise SystemExit('item generation block not found')
s=s.replace(old_item,new_item,1)

s=s.replace('Auto keeps the concept coherent. Power intent changes how aggressively the generator spends complexity; Legendary produces a Champion chassis. Official Pattern samples role and complexity from nearby official profiles without copying their names or rules text.','Auto keeps the concept coherent. Every full generation now creates six complete candidates and automatically keeps the strongest structural result. Power intent changes how aggressively the generator spends complexity; Legendary produces a Champion chassis. Official Pattern samples nearby official profiles without copying their names or rules text.',1)
s=s.replace('Power intent changes the budget the generator is willing to spend. Official Pattern uses matching official equipment to nudge the budget and rank several fresh candidates by common martial/category/range/handedness/quality structure without copying item text.','Every full generation now creates six complete candidates and automatically keeps the strongest structural result. Power intent changes the budget the generator is willing to spend. Official Pattern uses matching official equipment to nudge the budget and rank fresh candidates by common martial/category/range/handedness/quality structure without copying item text.',1)

p.write_text(s)
