from pathlib import Path
p=Path('src/App.tsx');s=p.read_text()
s=s.replace("import { aestraNations, aestraOrigins, applyAestraMonsterIdentity, AestraInfluence, AestraNation, AestraOrigin, valdoriaDepths, ValdoriaDepth } from './aestra'", "import { aestraNations, aestraOrigins, applyAestraMonsterIdentity, AestraInfluence, AestraNation, AestraOrigin, valdoriaDepths, ValdoriaDepth } from './aestra'\nimport { aestraEnvironments, aestraExposures, aestraWildOrigins, applyAestraWildIdentity, AestraEnvironment, AestraExposure, AestraWildOrigin } from './aestraWilds'")
s=s.replace("nation:'Garlond' as AestraNation,origin:", "nation:'Garlond' as AestraNation|'Aestra',environment:'Green Reaches' as AestraEnvironment,exposure:'Borderlands' as AestraExposure,wildOrigin:'Natural' as AestraWildOrigin,origin:")
s=s.replace("[nation,setNation]=useState<AestraNation>(initial.nation||'Garlond'),[origin", "[nation,setNation]=useState<AestraNation|'Aestra'>(initial.nation||'Garlond'),[environment,setEnvironment]=useState<AestraEnvironment>(initial.environment||'Green Reaches'),[exposure,setExposure]=useState<AestraExposure>(initial.exposure||'Borderlands'),[wildOrigin,setWildOrigin]=useState<AestraWildOrigin>(initial.wildOrigin||'Natural'),[origin")
s=s.replace("{level,rank,soldierEquivalent,sp,complexity,combatStyle,theme,powerIntent,inspiration,setting,nation,origin,influence,depth}", "{level,rank,soldierEquivalent,sp,complexity,combatStyle,theme,powerIntent,inspiration,setting,nation,environment,exposure,wildOrigin,origin,influence,depth}")
s=s.replace("[level,rank,soldierEquivalent,sp,complexity,combatStyle,theme,powerIntent,inspiration,setting,nation,origin,influence,depth]", "[level,rank,soldierEquivalent,sp,complexity,combatStyle,theme,powerIntent,inspiration,setting,nation,environment,exposure,wildOrigin,origin,influence,depth]")
s=s.replace("if(setting==='Aestra') monster=applyAestraMonsterIdentity(monster,nation,origin,influence,depth);", "if(setting==='Aestra') monster=nation==='Aestra'?applyAestraWildIdentity(monster,environment,exposure,wildOrigin):applyAestraMonsterIdentity(monster,nation,origin,influence,depth);")
old="<label>Aestra nation<select value={nation} onChange={e=>{const n=e.target.value as AestraNation;setNation(n);setOrigin(aestraOrigins(n)[0])}}>{(Object.keys(aestraNations) as AestraNation[]).map(n=><option key={n}>{n}</option>)}</select></label><p className=\"note\">{aestraNations[nation].identity}</p><label>Origin<select value={origin} onChange={e=>setOrigin(e.target.value as AestraOrigin)}>{aestraOrigins(nation).map(o=><option key={o}>{o}</option>)}</select></label><label>Crystal influence<select value={influence} onChange={e=>setInfluence(e.target.value as AestraInfluence)}><option>Stable</option><option>Fading</option><option>Crystal-Starved</option><option>Overcharged</option><option>Corrupted</option></select></label>"
new="<label>Aestra region<select value={nation} onChange={e=>{const n=e.target.value as AestraNation|'Aestra';setNation(n);if(n!=='Aestra')setOrigin(aestraOrigins(n)[0])}}>{[...(Object.keys(aestraNations) as AestraNation[]),'Aestra'].map(n=><option key={n}>{n}</option>)}</select></label>{nation==='Aestra'?<><p className=\"note\">Lands outside direct national control: wilderness, ruins, frontier settlements and the spaces between the four powers.</p><label>Environment<select value={environment} onChange={e=>setEnvironment(e.target.value as AestraEnvironment)}>{aestraEnvironments.map(x=><option key={x}>{x}</option>)}</select></label><label>Exposure<select value={exposure} onChange={e=>setExposure(e.target.value as AestraExposure)}>{aestraExposures.map(x=><option key={x}>{x}</option>)}</select></label><label>Origin<select value={wildOrigin} onChange={e=>setWildOrigin(e.target.value as AestraWildOrigin)}>{aestraWildOrigins.map(x=><option key={x}>{x}</option>)}</select></label><p className=\"muted smallText\">Exposure controls how poorly understood and unusual the threat is, independently of its level.</p></>:<><p className=\"note\">{aestraNations[nation].identity}</p><label>Origin<select value={origin} onChange={e=>setOrigin(e.target.value as AestraOrigin)}>{aestraOrigins(nation).map(o=><option key={o}>{o}</option>)}</select></label><label>Crystal influence<select value={influence} onChange={e=>setInfluence(e.target.value as AestraInfluence)}><option>Stable</option><option>Fading</option><option>Crystal-Starved</option><option>Overcharged</option><option>Corrupted</option></select></label></>}"
if old not in s: raise SystemExit('Aestra UI block not found')
s=s.replace(old,new,1)
p.write_text(s)
