from pathlib import Path
p=Path('src/App.tsx')
s=p.read_text()

old="import { aestraEnvironments, aestraExposures, aestraWildOrigins, applyAestraWildIdentity, AestraEnvironment, AestraExposure, AestraWildOrigin } from './aestraWilds'"
new=old+"\nimport { applyAestraNationItemIdentity, applyAestraWildItemIdentity } from './aestraItems'"
if "from './aestraItems'" not in s:
    s=s.replace(old,new)

old_effect="useEffect(()=>localStorage.setItem(ITEM_GENERATOR_KEY,JSON.stringify({type,weaponMethod,maxCost,allowMartial,allowTransforming,damageType,addMaterial,materialNature,descriptorMode,materialFunction,itemTheme,powerIntent,inspiration})),[type,weaponMethod,maxCost,allowMartial,allowTransforming,damageType,addMaterial,materialNature,descriptorMode,materialFunction,itemTheme,powerIntent,inspiration])"
new_effect="useEffect(()=>localStorage.setItem(ITEM_GENERATOR_KEY,JSON.stringify({type,weaponMethod,maxCost,allowMartial,allowTransforming,damageType,addMaterial,materialNature,descriptorMode,materialFunction,itemTheme,powerIntent,inspiration,setting,nation,environment,exposure,wildOrigin,origin,influence,depth})),[type,weaponMethod,maxCost,allowMartial,allowTransforming,damageType,addMaterial,materialNature,descriptorMode,materialFunction,itemTheme,powerIntent,inspiration,setting,nation,environment,exposure,wildOrigin,origin,influence,depth])"
if old_effect not in s: raise SystemExit('item settings effect needle missing')
s=s.replace(old_effect,new_effect)

old_generate="const generate=()=>{let budget=powerAdjustedItemBudget(maxCost,powerIntent);const pattern=inspiration==='Official Pattern'?officialInspiredItemBudget(readStored<AppItem[]>('fu-items',[]),type,budget):{maxCost:budget,note:''};budget=pattern.maxCost;let item:AppItem=type==='Weapon'&&weaponMethod==='Atlas Custom'?generateCustomWeapon({allowMartial,allowTransforming:powerIntent==='Legendary'?true:allowTransforming,preferredDamageType:damageType}):generateItem({type,maxCost:budget,allowMartial,preferredDamageType:damageType});item=applyItemTheme(item,itemTheme==='Auto'?undefined:itemTheme);item={...item,breakdown:[...(item.breakdown||[]),`Power intent: ${powerIntent}.`,...(pattern.note?[pattern.note]:[])]};if(addMaterial){const material=generateMaterial({nature:materialNature,descriptorMode,element:descriptorMode==='Elemental'&&damageType!=='random'&&damageType!=='physical'?damageType:'Random',function:materialFunction});item={...item,material,origin:`Crafted using ${material.name.toLowerCase()}, a ${material.nature.toLowerCase()} material selected from the Natural Fantasy material tables.`,breakdown:[...(item.breakdown||[]),`Material: ${material.name} (flavour/origin; does not alter equipment cost by itself).`]}}setResult(item)}"
new_generate="const applyItemSetting=(item:AppItem):AppItem=>setting!=='Aestra'?item:(nation==='Aestra'?applyAestraWildItemIdentity(item,environment,exposure,wildOrigin):applyAestraNationItemIdentity(item,nation,origin,influence,depth));const generate=()=>{let budget=powerAdjustedItemBudget(maxCost,powerIntent);const pattern=inspiration==='Official Pattern'?officialInspiredItemBudget(readStored<AppItem[]>('fu-items',[]),type,budget):{maxCost:budget,note:''};budget=pattern.maxCost;let item:AppItem=type==='Weapon'&&weaponMethod==='Atlas Custom'?generateCustomWeapon({allowMartial,allowTransforming:powerIntent==='Legendary'?true:allowTransforming,preferredDamageType:damageType}):generateItem({type,maxCost:budget,allowMartial,preferredDamageType:damageType});item=applyItemTheme(item,itemTheme==='Auto'?undefined:itemTheme);item={...item,breakdown:[...(item.breakdown||[]),`Power intent: ${powerIntent}.`,...(pattern.note?[pattern.note]:[])]};if(addMaterial){const material=generateMaterial({nature:materialNature,descriptorMode,element:descriptorMode==='Elemental'&&damageType!=='random'&&damageType!=='physical'?damageType:'Random',function:materialFunction});item={...item,material,origin:`Crafted using ${material.name.toLowerCase()}, a ${material.nature.toLowerCase()} material selected from the Natural Fantasy material tables.`,breakdown:[...(item.breakdown||[]).filter(line=>!line.startsWith('Concept material: ')),`Material: ${material.name} (authoritative material identity; does not alter equipment cost by itself).`]}}item=applyItemSetting(item);setResult(item)}"
if old_generate not in s: raise SystemExit('item generate needle missing')
s=s.replace(old_generate,new_generate)

old_reroll="const rerollItem=(part:ItemRerollPart)=>setResult(current=>current?rerollItemPart(current,part) as AppItem:current)"
new_reroll="const rerollItem=(part:ItemRerollPart)=>setResult(current=>current?applyItemSetting(rerollItemPart(current,part) as AppItem):current)"
if old_reroll not in s: raise SystemExit('reroll item needle missing')
s=s.replace(old_reroll,new_reroll)

old_material="return{...current,material,origin:`Crafted using ${material.name.toLowerCase()}, a ${material.nature.toLowerCase()} material selected from the Natural Fantasy material tables.`,breakdown:[...(current.breakdown||[]).filter(line=>!line.startsWith('Material: ')),`Material: ${material.name} (flavour/origin; does not alter equipment cost by itself).`]}})"
new_material="return applyItemSetting({...current,material,origin:`Crafted using ${material.name.toLowerCase()}, a ${material.nature.toLowerCase()} material selected from the Natural Fantasy material tables.`,breakdown:[...(current.breakdown||[]).filter(line=>!line.startsWith('Material: ')&&!line.startsWith('Concept material: ')&&!line.startsWith('Material identity: ')),`Material: ${material.name} (authoritative material identity; does not alter equipment cost by itself).`]})})"
if old_material not in s: raise SystemExit('reroll material needle missing')
s=s.replace(old_material,new_material)

needle="<p className=\"muted smallText\">Power intent changes the budget the generator is willing to spend. Official Pattern centers that budget on matching official equipment already in the database without copying item text.</p><div className=\"subpanel\">"
insert="<p className=\"muted smallText\">Power intent changes the budget the generator is willing to spend. Official Pattern centers that budget on matching official equipment already in the database without copying item text.</p><label>Setting<select value={setting} onChange={e=>setSetting(e.target.value as 'Generic'|'Aestra')}><option>Generic</option><option>Aestra</option></select></label>{setting==='Aestra'&&<div className=\"subpanel\"><label>Region<select value={nation} onChange={e=>{const n=e.target.value as AestraNation|'Aestra';setNation(n);if(n!=='Aestra')setOrigin(aestraOrigins(n)[0])}}>{[...(Object.keys(aestraNations) as AestraNation[]),'Aestra'].map(n=><option key={n}>{n}</option>)}</select></label>{nation==='Aestra'?<><p className=\"note\">Lands outside direct national control.</p><label>Environment<select value={environment} onChange={e=>setEnvironment(e.target.value as AestraEnvironment)}>{aestraEnvironments.map(x=><option key={x}>{x}</option>)}</select></label><label>Exposure<select value={exposure} onChange={e=>setExposure(e.target.value as AestraExposure)}>{aestraExposures.map(x=><option key={x}>{x}</option>)}</select></label><label>Origin<select value={wildOrigin} onChange={e=>setWildOrigin(e.target.value as AestraWildOrigin)}>{aestraWildOrigins.map(x=><option key={x}>{x}</option>)}</select></label><p className=\"muted smallText\">Environment controls the item’s local design/ecology. Exposure controls how familiar or poorly understood it is, not its raw price or power.</p></>:<><p className=\"note\">{aestraNations[nation].identity}</p><label>Origin<select value={origin} onChange={e=>setOrigin(e.target.value as AestraOrigin)}>{aestraOrigins(nation).map(o=><option key={o}>{o}</option>)}</select></label><label>Crystal influence<select value={influence} onChange={e=>setInfluence(e.target.value as AestraInfluence)}><option>Stable</option><option>Fading</option><option>Crystal-Starved</option><option>Overcharged</option><option>Corrupted</option></select></label>{nation==='Valdoria'&&<label>Valdoria depth<select value={depth} onChange={e=>setDepth(e.target.value as ValdoriaDepth)}>{valdoriaDepths.map(d=><option key={d}>{d}</option>)}</select></label>}</>}<p className=\"muted smallText\">Aestra item identity changes naming, provenance and a bounded situational mechanic without silently increasing the listed zenny budget.</p></div>}<div className=\"subpanel\">"
if needle not in s: raise SystemExit('item UI insertion needle missing')
s=s.replace(needle,insert)

p.write_text(s)
