from pathlib import Path
p=Path('src/App.tsx')
s=p.read_text()
def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'Missing {label}')
    s=s.replace(old,new,1)

rep("import { applyItemTheme, itemThemes, ItemTheme } from './itemThemeEngine'", "import { applyItemTheme, itemThemes, ItemTheme, rerollItemPart, ItemRerollPart, itemCoherenceSummary } from './itemThemeEngine'\nimport { createMonsterVariant, GeneratorPowerIntent, MonsterVariant, monsterCoherenceSummary, officialInspiredItemBudget, officialInspiredMonsterSettings, powerAdjustedItemBudget, powerAdjustedMonsterSettings } from './generatorEvolution'", 'generator imports')

old="""  const initial=useMemo(()=>readStored(MONSTER_GENERATOR_KEY,{level:10,rank:'Soldier' as Rank,soldierEquivalent:3,sp:'Monster' as Species,complexity:'Standard' as 'Simple'|'Standard'|'Crunchy',combatStyle:'Mixed' as CombatStyle,theme:'Auto' as MonsterTheme|'Auto'}),[])
  const [level,setLevel]=useState(initial.level),[rank,setRank]=useState<Rank>(initial.rank),[soldierEquivalent,setSoldierEquivalent]=useState(initial.soldierEquivalent),[sp,setSp]=useState<Species>(initial.sp),[complexity,setComplexity]=useState<'Simple'|'Standard'|'Crunchy'>(initial.complexity),[combatStyle,setCombatStyle]=useState<CombatStyle>(initial.combatStyle),[theme,setTheme]=useState<MonsterTheme|'Auto'>(initial.theme || 'Auto'),[result,setResult]=useState<Monster|null>(null)
  useEffect(()=>localStorage.setItem(MONSTER_GENERATOR_KEY,JSON.stringify({level,rank,soldierEquivalent,sp,complexity,combatStyle,theme})),[level,rank,soldierEquivalent,sp,complexity,combatStyle,theme])
  const make=()=>setResult(applyMonsterTheme(generateMonster({level,rank,soldierEquivalent,species:sp,complexity,combatStyle}),theme==='Auto'?undefined:theme))
  const reroll=(part:MonsterRerollPart)=>setResult(current=>current?rerollMonsterPart(current,part):current)"""
new="""  const initial=useMemo(()=>readStored(MONSTER_GENERATOR_KEY,{level:10,rank:'Soldier' as Rank,soldierEquivalent:3,sp:'Monster' as Species,complexity:'Standard' as 'Simple'|'Standard'|'Crunchy',combatStyle:'Mixed' as CombatStyle,theme:'Auto' as MonsterTheme|'Auto',powerIntent:'Standard' as GeneratorPowerIntent,inspiration:'Original' as 'Original'|'Official Pattern'}),[])
  const [level,setLevel]=useState(initial.level),[rank,setRank]=useState<Rank>(initial.rank),[soldierEquivalent,setSoldierEquivalent]=useState(initial.soldierEquivalent),[sp,setSp]=useState<Species>(initial.sp),[complexity,setComplexity]=useState<'Simple'|'Standard'|'Crunchy'>(initial.complexity),[combatStyle,setCombatStyle]=useState<CombatStyle>(initial.combatStyle),[theme,setTheme]=useState<MonsterTheme|'Auto'>(initial.theme || 'Auto'),[powerIntent,setPowerIntent]=useState<GeneratorPowerIntent>(initial.powerIntent||'Standard'),[inspiration,setInspiration]=useState<'Original'|'Official Pattern'>(initial.inspiration||'Original'),[result,setResult]=useState<Monster|null>(null)
  useEffect(()=>localStorage.setItem(MONSTER_GENERATOR_KEY,JSON.stringify({level,rank,soldierEquivalent,sp,complexity,combatStyle,theme,powerIntent,inspiration})),[level,rank,soldierEquivalent,sp,complexity,combatStyle,theme,powerIntent,inspiration])
  const make=()=>{const adjusted=powerAdjustedMonsterSettings(rank,complexity,soldierEquivalent,powerIntent);const pattern=inspiration==='Official Pattern'?officialInspiredMonsterSettings(readStored<Monster[]>('fu-monsters',[]),level,sp,adjusted.rank,combatStyle,adjusted.complexity):{style:combatStyle,complexity:adjusted.complexity,note:''};let monster=applyMonsterTheme(generateMonster({level,rank:adjusted.rank,soldierEquivalent:adjusted.soldierEquivalent,species:sp,complexity:pattern.complexity,combatStyle:pattern.style}),theme==='Auto'?undefined:theme);monster={...monster,notes:[...(monster.notes||[]),`Power intent: ${powerIntent}.${powerIntent==='Legendary'?' Legendary intent promotes the generated chassis to Champion.':''}`,...(pattern.note?[pattern.note]:[])]};setResult(monster)}
  const reroll=(part:MonsterRerollPart)=>setResult(current=>current?rerollMonsterPart(current,part):current)
  const variant=(kind:MonsterVariant)=>setResult(current=>current?createMonsterVariant(current,kind):current)"""
rep(old,new,'monster generator state')
rep("""<label>Theme<select value={theme} onChange={e=>setTheme(e.target.value as MonsterTheme|'Auto')}><option>Auto</option>{monsterThemes.map(x=><option key={x}>{x}</option>)}</select></label><p className="muted smallText">Auto chooses a theme that fits the species and combat style. Names, traits, damage types and status effects are generated from that same concept.</p><button className="primary" onClick={make}>Generate Monster</button>""", """<label>Theme<select value={theme} onChange={e=>setTheme(e.target.value as MonsterTheme|'Auto')}><option>Auto</option>{monsterThemes.map(x=><option key={x}>{x}</option>)}</select></label><label>Power intent<select value={powerIntent} onChange={e=>setPowerIntent(e.target.value as GeneratorPowerIntent)}><option>Conservative</option><option>Standard</option><option>Dangerous</option><option>Legendary</option></select></label><label>Design reference<select value={inspiration} onChange={e=>setInspiration(e.target.value as 'Original'|'Official Pattern')}><option>Original</option><option>Official Pattern</option></select></label><p className="muted smallText">Auto keeps the concept coherent. Power intent changes how aggressively the generator spends complexity; Legendary produces a Champion chassis. Official Pattern samples role and complexity from nearby official profiles without copying their names or rules text.</p><button className="primary" onClick={make}>Generate Monster</button>""", 'monster controls')
rep('<MonsterCard monster={result}/><div className="subpanel"><span className="source">Keep this monster, reroll only</span>', '<MonsterCard monster={result}/><div className="subpanel"><span className="source">Coherence summary</span><p className="note">{monsterCoherenceSummary(result)}</p></div><div className="subpanel"><span className="source">Create a related variant</span><div className="buttonRow"><button onClick={()=>variant(\'Minion\')}>Lesser / Minion</button><button onClick={()=>variant(\'Elite\')}>Elite</button><button onClick={()=>variant(\'Champion\')}>Champion / Boss</button><button onClick={()=>variant(\'Corrupted\')}>Corrupted</button><button onClick={()=>variant(\'Elemental\')}>Elemental</button><button onClick={()=>variant(\'Role Shift\')}>Different Role</button></div><p className="muted smallText">Variants regenerate a rules-aware chassis while preserving species and family identity, instead of merely multiplying HP or damage.</p></div><div className="subpanel"><span className="source">Keep this monster, reroll only</span>', 'monster variants')

old="""  const initial=useMemo(()=>readStored(ITEM_GENERATOR_KEY,{type:'Weapon' as ItemType,weaponMethod:'Core Rare' as 'Core Rare'|'Atlas Custom',maxCost:1500,allowMartial:true,allowTransforming:true,damageType:'random' as DamageType|'random',addMaterial:false,materialNature:'Random' as MaterialNature|'Random',descriptorMode:'Random' as 'Elemental'|'Functional'|'Random',materialFunction:'Random' as MaterialFunction|'Random',itemTheme:'Auto' as ItemTheme|'Auto'}),[])
  const [type,setType]=useState<ItemType>(initial.type),[weaponMethod,setWeaponMethod]=useState<'Core Rare'|'Atlas Custom'>(initial.weaponMethod),[maxCost,setMaxCost]=useState(initial.maxCost),[allowMartial,setAllowMartial]=useState(initial.allowMartial),[allowTransforming,setAllowTransforming]=useState(initial.allowTransforming),[damageType,setDamageType]=useState<DamageType|'random'>(initial.damageType),[addMaterial,setAddMaterial]=useState(initial.addMaterial),[materialNature,setMaterialNature]=useState<MaterialNature|'Random'>(initial.materialNature),[descriptorMode,setDescriptorMode]=useState<'Elemental'|'Functional'|'Random'>(initial.descriptorMode),[materialFunction,setMaterialFunction]=useState<MaterialFunction|'Random'>(initial.materialFunction),[itemTheme,setItemTheme]=useState<ItemTheme|'Auto'>(initial.itemTheme||'Auto'),[result,setResult]=useState<AppItem|null>(null)
  useEffect(()=>localStorage.setItem(ITEM_GENERATOR_KEY,JSON.stringify({type,weaponMethod,maxCost,allowMartial,allowTransforming,damageType,addMaterial,materialNature,descriptorMode,materialFunction,itemTheme})),[type,weaponMethod,maxCost,allowMartial,allowTransforming,damageType,addMaterial,materialNature,descriptorMode,materialFunction,itemTheme])
  const generate=()=>{let item:AppItem=type==='Weapon'&&weaponMethod==='Atlas Custom'?generateCustomWeapon({allowMartial,allowTransforming,preferredDamageType:damageType}):generateItem({type,maxCost,allowMartial,preferredDamageType:damageType});item=applyItemTheme(item,itemTheme==='Auto'?undefined:itemTheme);if(addMaterial){const material=generateMaterial({nature:materialNature,descriptorMode,element:descriptorMode==='Elemental'&&damageType!=='random'&&damageType!=='physical'?damageType:'Random',function:materialFunction});item={...item,material,origin:`Crafted using ${material.name.toLowerCase()}, a ${material.nature.toLowerCase()} material selected from the Natural Fantasy material tables.`,breakdown:[...(item.breakdown||[]),`Material: ${material.name} (flavour/origin; does not alter equipment cost by itself).`]}}setResult(item)}"""
new="""  const initial=useMemo(()=>readStored(ITEM_GENERATOR_KEY,{type:'Weapon' as ItemType,weaponMethod:'Core Rare' as 'Core Rare'|'Atlas Custom',maxCost:1500,allowMartial:true,allowTransforming:true,damageType:'random' as DamageType|'random',addMaterial:false,materialNature:'Random' as MaterialNature|'Random',descriptorMode:'Random' as 'Elemental'|'Functional'|'Random',materialFunction:'Random' as MaterialFunction|'Random',itemTheme:'Auto' as ItemTheme|'Auto',powerIntent:'Standard' as GeneratorPowerIntent,inspiration:'Original' as 'Original'|'Official Pattern'}),[])
  const [type,setType]=useState<ItemType>(initial.type),[weaponMethod,setWeaponMethod]=useState<'Core Rare'|'Atlas Custom'>(initial.weaponMethod),[maxCost,setMaxCost]=useState(initial.maxCost),[allowMartial,setAllowMartial]=useState(initial.allowMartial),[allowTransforming,setAllowTransforming]=useState(initial.allowTransforming),[damageType,setDamageType]=useState<DamageType|'random'>(initial.damageType),[addMaterial,setAddMaterial]=useState(initial.addMaterial),[materialNature,setMaterialNature]=useState<MaterialNature|'Random'>(initial.materialNature),[descriptorMode,setDescriptorMode]=useState<'Elemental'|'Functional'|'Random'>(initial.descriptorMode),[materialFunction,setMaterialFunction]=useState<MaterialFunction|'Random'>(initial.materialFunction),[itemTheme,setItemTheme]=useState<ItemTheme|'Auto'>(initial.itemTheme||'Auto'),[powerIntent,setPowerIntent]=useState<GeneratorPowerIntent>(initial.powerIntent||'Standard'),[inspiration,setInspiration]=useState<'Original'|'Official Pattern'>(initial.inspiration||'Original'),[result,setResult]=useState<AppItem|null>(null)
  useEffect(()=>localStorage.setItem(ITEM_GENERATOR_KEY,JSON.stringify({type,weaponMethod,maxCost,allowMartial,allowTransforming,damageType,addMaterial,materialNature,descriptorMode,materialFunction,itemTheme,powerIntent,inspiration})),[type,weaponMethod,maxCost,allowMartial,allowTransforming,damageType,addMaterial,materialNature,descriptorMode,materialFunction,itemTheme,powerIntent,inspiration])
  const generate=()=>{let budget=powerAdjustedItemBudget(maxCost,powerIntent);const pattern=inspiration==='Official Pattern'?officialInspiredItemBudget(readStored<AppItem[]>('fu-items',[]),type,budget):{maxCost:budget,note:''};budget=pattern.maxCost;let item:AppItem=type==='Weapon'&&weaponMethod==='Atlas Custom'?generateCustomWeapon({allowMartial,allowTransforming:powerIntent==='Legendary'?true:allowTransforming,preferredDamageType:damageType}):generateItem({type,maxCost:budget,allowMartial,preferredDamageType:damageType});item=applyItemTheme(item,itemTheme==='Auto'?undefined:itemTheme);item={...item,breakdown:[...(item.breakdown||[]),`Power intent: ${powerIntent}.`,...(pattern.note?[pattern.note]:[])]};if(addMaterial){const material=generateMaterial({nature:materialNature,descriptorMode,element:descriptorMode==='Elemental'&&damageType!=='random'&&damageType!=='physical'?damageType:'Random',function:materialFunction});item={...item,material,origin:`Crafted using ${material.name.toLowerCase()}, a ${material.nature.toLowerCase()} material selected from the Natural Fantasy material tables.`,breakdown:[...(item.breakdown||[]),`Material: ${material.name} (flavour/origin; does not alter equipment cost by itself).`]}}setResult(item)}
  const rerollItem=(part:ItemRerollPart)=>setResult(current=>current?rerollItemPart(current,part) as AppItem:current)
  const rerollMaterial=()=>setResult(current=>{if(!current||!addMaterial)return current;const material=generateMaterial({nature:materialNature,descriptorMode,element:descriptorMode==='Elemental'&&damageType!=='random'&&damageType!=='physical'?damageType:'Random',function:materialFunction});return{...current,material,origin:`Crafted using ${material.name.toLowerCase()}, a ${material.nature.toLowerCase()} material selected from the Natural Fantasy material tables.`,breakdown:[...(current.breakdown||[]).filter(line=>!line.startsWith('Material: ')),`Material: ${material.name} (flavour/origin; does not alter equipment cost by itself).`]}}})"""
rep(old,new,'item generator state')
rep("""<label>Theme<select value={itemTheme} onChange={e=>setItemTheme(e.target.value as ItemTheme|'Auto')}><option>Auto</option>{itemThemes.map(t=><option key={t}>{t}</option>)}</select></label><p className="muted smallText">Auto chooses a concept from the item’s category and damage profile. The name, damage identity, quality wording and material flavour are then kept in the same theme.</p>""", """<label>Theme<select value={itemTheme} onChange={e=>setItemTheme(e.target.value as ItemTheme|'Auto')}><option>Auto</option>{itemThemes.map(t=><option key={t}>{t}</option>)}</select></label><label>Power intent<select value={powerIntent} onChange={e=>setPowerIntent(e.target.value as GeneratorPowerIntent)}><option>Conservative</option><option>Standard</option><option>Dangerous</option><option>Legendary</option></select></label><label>Design reference<select value={inspiration} onChange={e=>setInspiration(e.target.value as 'Original'|'Official Pattern')}><option>Original</option><option>Official Pattern</option></select></label><p className="muted smallText">Power intent changes the budget the generator is willing to spend. Official Pattern centers that budget on matching official equipment already in the database without copying item text.</p>""", 'item controls')
rep('<ItemCard item={result}/><div className="buttonRow"><button onClick={generate}>Reroll</button><button className="primary" onClick={()=>onSave(result)}>Save to Database</button></div>', '<ItemCard item={result}/><div className="subpanel"><span className="source">Coherence summary</span><p className="note">{itemCoherenceSummary(result)}</p></div><div className="subpanel"><span className="source">Keep this item, reroll only</span><div className="buttonRow"><button onClick={()=>rerollItem(\'name\')}>Name</button><button onClick={()=>rerollItem(\'quality\')}>Quality / Effect</button><button onClick={()=>rerollItem(\'element\')} disabled={result.type!==\'Weapon\'}>Element</button><button onClick={()=>rerollItem(\'theme\')}>Theme</button><button onClick={rerollMaterial} disabled={!addMaterial}>Material</button></div><p className="muted smallText">Targeted rerolls preserve the base item, price and other details unless the selected part logically requires a thematic rewrite.</p></div><div className="buttonRow"><button onClick={generate}>Reroll Everything</button><button className="primary" onClick={()=>onSave(result)}>Save to Database</button></div>', 'item rerolls')
p.write_text(s)
print('Generator evolution migration applied')