# Retry after workflow install fix
from pathlib import Path
p=Path('src/App.tsx')
s=p.read_text()
s=s.replace("import { GeneratedMaterial, generateMaterial, MaterialFunction, MaterialNature } from './materials'", "import { GeneratedMaterial, generateMaterial, MaterialFunction, MaterialNature } from './materials'\nimport { aestraNations, aestraOrigins, applyAestraMonsterIdentity, AestraInfluence, AestraNation, AestraOrigin } from './aestra'")
old="""inspiration:'Original' as 'Original'|'Official Pattern'}),[])"""
new="""inspiration:'Original' as 'Original'|'Official Pattern',setting:'Generic' as 'Generic'|'Aestra',nation:'Garlond' as AestraNation,origin:'Military' as AestraOrigin,influence:'Stable' as AestraInfluence}),[])"""
s=s.replace(old,new)
s=s.replace("[inspiration,setInspiration]=useState<'Original'|'Official Pattern'>(initial.inspiration||'Original'),[result,setResult]", "[inspiration,setInspiration]=useState<'Original'|'Official Pattern'>(initial.inspiration||'Original'),[setting,setSetting]=useState<'Generic'|'Aestra'>(initial.setting||'Generic'),[nation,setNation]=useState<AestraNation>(initial.nation||'Garlond'),[origin,setOrigin]=useState<AestraOrigin>(initial.origin||'Military'),[influence,setInfluence]=useState<AestraInfluence>(initial.influence||'Stable'),[result,setResult]")
s=s.replace("{level,rank,soldierEquivalent,sp,complexity,combatStyle,theme,powerIntent,inspiration})),[level,rank,soldierEquivalent,sp,complexity,combatStyle,theme,powerIntent,inspiration])", "{level,rank,soldierEquivalent,sp,complexity,combatStyle,theme,powerIntent,inspiration,setting,nation,origin,influence})),[level,rank,soldierEquivalent,sp,complexity,combatStyle,theme,powerIntent,inspiration,setting,nation,origin,influence])")
s=s.replace("monster={...monster,notes:[...(monster.notes||[]),`Power intent:", "if(setting==='Aestra') monster=applyAestraMonsterIdentity(monster,nation,origin,influence);monster={...monster,notes:[...(monster.notes||[]),`Power intent:")
needle="<label>Power intent<select value={powerIntent}"
insert="""<label>Setting<select value={setting} onChange={e=>setSetting(e.target.value as 'Generic'|'Aestra')}><option>Generic</option><option>Aestra</option></select></label>{setting==='Aestra'&&<><label>Aestra nation<select value={nation} onChange={e=>{const n=e.target.value as AestraNation;setNation(n);setOrigin(aestraOrigins(n)[0])}}>{(Object.keys(aestraNations) as AestraNation[]).map(n=><option key={n}>{n}</option>)}</select></label><p className="note">{aestraNations[nation].identity}</p><label>Origin<select value={origin} onChange={e=>setOrigin(e.target.value as AestraOrigin)}>{aestraOrigins(nation).map(o=><option key={o}>{o}</option>)}</select></label><label>Crystal influence<select value={influence} onChange={e=>setInfluence(e.target.value as AestraInfluence)}><option>Stable</option><option>Fading</option><option>Crystal-Starved</option><option>Overcharged</option><option>Corrupted</option></select></label><p className="muted smallText">Aestra mode applies national design language, origin and crystal context to the generated monster while preserving the Fabula Ultima chassis.</p></>}"""
if needle not in s: raise SystemExit('power intent needle missing')
s=s.replace(needle,insert+needle,1)
p.write_text(s)
