from pathlib import Path

# 1) Traits targeted reroll.
p=Path('src/monsterThemeEngine.ts')
s=p.read_text()
s=s.replace("export type MonsterRerollPart = 'name' | 'attacks' | 'skills' | 'spells' | 'affinities' | 'theme'", "export type MonsterRerollPart = 'name' | 'traits' | 'attacks' | 'skills' | 'spells' | 'affinities' | 'theme'")
needle="export function rerollMonsterPart(monster:Monster, part:MonsterRerollPart):Monster {\n  const currentTheme=themeFromMonster(monster)"
replacement="export function rerollMonsterPart(monster:Monster, part:MonsterRerollPart):Monster {\n  const currentTheme=themeFromMonster(monster)\n  if(part==='traits') return {...monster,traits:unique(shuffled(profiles[currentTheme].traits).slice(0,2))}"
if needle not in s: raise SystemExit('reroll insertion point missing')
s=s.replace(needle,replacement,1)
p.write_text(s)

# 2) Give wild environments species hints and make affinity refresh preserve Corrupted influence.
p=Path('src/aestraWilds.ts')
s=p.read_text()
s=s.replace("import type { Affinity, DamageType, Monster, MonsterAttack, MonsterSkill } from './rules'", "import type { Affinity, DamageType, Monster, MonsterAttack, MonsterSkill, Species } from './rules'\nimport type { AestraInfluence } from './aestra'")
old="export function aestraWildGenerationHint(environment:AestraEnvironment){\n const styles:Record<AestraEnvironment,import('./rules').CombatStyle[]>={\n  'Green Reaches':['Controller','Brute','Mixed'],\n  'Scarlands':['Controller','Spellcaster','Brute'],\n  'Ruin Belts':['Defender','Controller','Spellcaster'],\n  'Frontier':['Mixed','Support','Assassin'],\n  'Deep Wilds':['Controller','Assassin','Mixed'],\n }\n return {combatStyle:pick(styles[environment])}\n}\n\nexport function refreshAestraWildAffinities(monster:Monster,environment:AestraEnvironment):Monster{\n const affinities={...monster.affinities}\n if(environment==='Green Reaches')affinities.earth=improve(affinities.earth)\n if(environment==='Ruin Belts')affinities.bolt=improve(affinities.bolt)\n return {...monster,affinities}\n}\n"
new="export function aestraWildGenerationHint(environment:AestraEnvironment){\n const styles:Record<AestraEnvironment,import('./rules').CombatStyle[]>={\n  'Green Reaches':['Controller','Brute','Mixed'],\n  'Scarlands':['Controller','Spellcaster','Brute'],\n  'Ruin Belts':['Defender','Controller','Spellcaster'],\n  'Frontier':['Mixed','Support','Assassin'],\n  'Deep Wilds':['Controller','Assassin','Mixed'],\n }\n const species:Record<AestraEnvironment,Species[]>={\n  'Green Reaches':['Plant','Beast','Monster'],\n  'Scarlands':['Elemental','Construct','Monster'],\n  'Ruin Belts':['Construct','Undead','Monster'],\n  'Frontier':['Humanoid','Beast','Construct'],\n  'Deep Wilds':['Monster','Beast','Elemental'],\n }\n return {combatStyle:pick(styles[environment]),species:pick(species[environment])}\n}\n\nexport function refreshAestraWildAffinities(monster:Monster,environment:AestraEnvironment,influence:AestraInfluence='Stable'):Monster{\n const affinities={...monster.affinities}\n if(environment==='Green Reaches')affinities.earth=improve(affinities.earth)\n if(environment==='Ruin Belts')affinities.bolt=improve(affinities.bolt)\n if(influence==='Corrupted'){affinities.dark=improve(affinities.dark);affinities.light=affinities.light==='Immune'?'Resistant':affinities.light==='Resistant'?'Normal':affinities.light==='Normal'?'Vulnerable':affinities.light}\n return {...monster,affinities}\n}\n\nexport function refreshAestraWildTraits(monster:Monster,environment:AestraEnvironment):Monster{\n const marker:Record<AestraEnvironment,string>={'Green Reaches':'overgrown','Scarlands':'war-scarred','Ruin Belts':'relic-touched','Frontier':'weathered','Deep Wilds':'unclassified'}\n const regional=new Set(Object.values(marker))\n return {...monster,traits:[marker[environment],...monster.traits.filter(t=>!regional.has(t))].slice(0,4)}\n}\n"
if old not in s: raise SystemExit('wild hint/refresh block missing')
s=s.replace(old,new,1)
p.write_text(s)

# 3) Auto Species + traits UI + context-preserving rerolls.
p=Path('src/App.tsx')
s=p.read_text()
s=s.replace("import { aestraEnvironments, aestraExposures, aestraWildOrigins, applyAestraWildIdentity, aestraWildGenerationHint, refreshAestraWildAffinities, AestraEnvironment, AestraExposure, AestraWildOrigin } from './aestraWilds'", "import { aestraEnvironments, aestraExposures, aestraWildOrigins, applyAestraWildIdentity, aestraWildGenerationHint, refreshAestraWildAffinities, refreshAestraWildTraits, AestraEnvironment, AestraExposure, AestraWildOrigin } from './aestraWilds'")
s=s.replace("[sp,setSp]=useState<Species>(initial.sp)", "[sp,setSp]=useState<Species|'Auto'>(initial.sp||'Auto')")
old="const applyMonsterSetting=(monster:Monster):Monster=>setting!=='Aestra'?monster:(nation==='Aestra'?applyAestraCrystalInfluence(applyAestraWildIdentity(monster,environment,exposure,wildOrigin),influence):applyAestraMonsterIdentity(monster,nation,origin,influence,depth));const make=()=>{const adjusted=powerAdjustedMonsterSettings(rank,complexity,soldierEquivalent,powerIntent);const hintedStyle=setting==='Aestra'&&combatStyle==='Mixed'?(nation==='Aestra'?aestraWildGenerationHint(environment).combatStyle:aestraGenerationHint(nation).combatStyle):combatStyle;const pattern=inspiration==='Official Pattern'?officialInspiredMonsterSettings(readStored<Monster[]>('fu-monsters',[]),level,sp,adjusted.rank,hintedStyle,adjusted.complexity):"
new="const applyMonsterSetting=(monster:Monster):Monster=>setting!=='Aestra'?monster:(nation==='Aestra'?applyAestraCrystalInfluence(applyAestraWildIdentity(monster,environment,exposure,wildOrigin),influence):applyAestraMonsterIdentity(monster,nation,origin,influence,depth));const make=()=>{const adjusted=powerAdjustedMonsterSettings(rank,complexity,soldierEquivalent,powerIntent);const regionalHint=setting==='Aestra'?(nation==='Aestra'?aestraWildGenerationHint(environment):aestraGenerationHint(nation)):null;const resolvedSpecies:Species=sp==='Auto'?(regionalHint?.species||species[Math.floor(Math.random()*species.length)]):sp;const hintedStyle=setting==='Aestra'&&combatStyle==='Mixed'?(regionalHint?.combatStyle||combatStyle):combatStyle;const pattern=inspiration==='Official Pattern'?officialInspiredMonsterSettings(readStored<Monster[]>('fu-monsters',[]),level,resolvedSpecies,adjusted.rank,hintedStyle,adjusted.complexity):"
if old not in s: raise SystemExit('make header missing')
s=s.replace(old,new,1)
s=s.replace("species:sp,complexity:pattern.complexity", "species:resolvedSpecies,complexity:pattern.complexity",1)
s=s.replace("...(setting==='Aestra'&&combatStyle==='Mixed'?[`Aestra generation hint: regional identity selected ${pattern.style} as the starting combat role because Combat Style was left Mixed.`]:[]),", "...(setting==='Aestra'&&combatStyle==='Mixed'?[`Aestra generation hint: regional identity selected ${pattern.style} as the starting combat role because Combat Style was left Mixed.`]:[]),...(sp==='Auto'?[`Species selection: Auto chose ${resolvedSpecies}${setting==='Aestra'?' from the current Aestra context':' from the general species pool'}.`]:[]),",1)
old="if(setting==='Aestra'&&(part==='name'||part==='theme')&&nation!=='Aestra')next=refreshAestraMonsterLabel(next,nation);if(setting==='Aestra'&&part==='affinities')next=nation==='Aestra'?refreshAestraWildAffinities(next,environment):refreshAestraAffinities(next,nation,influence,depth);return next"
new="if(setting==='Aestra'&&(part==='name'||part==='theme'||part==='traits')&&nation!=='Aestra')next=refreshAestraMonsterLabel(next,nation);if(setting==='Aestra'&&part==='traits'&&nation==='Aestra')next=refreshAestraWildTraits(next,environment);if(setting==='Aestra'&&part==='affinities')next=nation==='Aestra'?refreshAestraWildAffinities(next,environment,influence):refreshAestraAffinities(next,nation,influence,depth);return next"
if old not in s: raise SystemExit('reroll context block missing')
s=s.replace(old,new,1)
old="<label>Species<select value={sp} onChange={e=>setSp(e.target.value as Species)}>{species.map(s=><option key={s}>{s}</option>)}</select></label><p className=\"note\">{speciesRules[sp].note}</p>"
new="<label>Species<select value={sp} onChange={e=>setSp(e.target.value as Species|'Auto')}><option>Auto</option>{species.map(s=><option key={s}>{s}</option>)}</select></label>{sp==='Auto'?<p className=\"note\">Auto Species lets the current Aestra region or environment influence the creature family. Choosing a species explicitly always wins.</p>:<p className=\"note\">{speciesRules[sp].note}</p>}"
if old not in s: raise SystemExit('species UI missing')
s=s.replace(old,new,1)
s=s.replace("<button onClick={()=>reroll('name')}>Name</button><button onClick={()=>reroll('attacks')}>Attacks</button>", "<button onClick={()=>reroll('name')}>Name</button><button onClick={()=>reroll('traits')}>Traits</button><button onClick={()=>reroll('attacks')}>Attacks</button>",1)
s=s.replace("Targeted rerolls preserve level, rank, attributes, HP, MP and Aestra regional identity; name/theme/affinity rerolls refresh the relevant regional layer without stacking duplicate mechanics.", "Targeted rerolls preserve level, rank, attributes, HP, MP and Aestra regional identity; name, traits, theme and affinity rerolls refresh the relevant regional layer without stacking duplicate mechanics.",1)
p.write_text(s)
