import { useEffect } from 'react'
import './databaseEnhancementHub.css'

type Kind='monster'|'item'
type MonsterFilters={min:number|null;max:number|null;role:'All'|'Spellcaster'|'No Spells'|'Has Crisis Rule';damage:string;affinityType:string;affinityValue:string}
type CatalogType='All'|'Weapon'|'Armor'|'Shield'|'Accessory'|'Artifact'|'Inventory Item'|'Weapon Module'|'Other'
const MONSTER_KEY='fu-monster-profile-filters'
const CATALOG_KEY='fu-item-catalog-type'
const damageTypes=['','physical','air','bolt','dark','earth','fire','ice','light','poison']
const affinityValues=['','Vulnerable','Resistant','Immune','Absorb']

function readArray(key:string){try{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function kind(section:HTMLElement):Kind|null{if(section.querySelector('input[placeholder^="Search monsters"]'))return'monster';if(section.querySelector('input[placeholder^="Search items"]'))return'item';return null}
function readMonsterFilters():MonsterFilters{try{const v=JSON.parse(localStorage.getItem(MONSTER_KEY)||'{}');return{min:v.min==null?null:Number(v.min),max:v.max==null?null:Number(v.max),role:['All','Spellcaster','No Spells','Has Crisis Rule'].includes(v.role)?v.role:'All',damage:damageTypes.includes(v.damage)?v.damage:'',affinityType:damageTypes.includes(v.affinityType)?v.affinityType:'',affinityValue:affinityValues.includes(v.affinityValue)?v.affinityValue:''}}catch{return{min:null,max:null,role:'All',damage:'',affinityType:'',affinityValue:''}}}
function writeMonsterFilters(v:MonsterFilters){localStorage.setItem(MONSTER_KEY,JSON.stringify(v))}
function readCatalog():CatalogType{try{const v=JSON.parse(localStorage.getItem(CATALOG_KEY)||'"All"');return ['All','Weapon','Armor','Shield','Accessory','Artifact','Inventory Item','Weapon Module','Other'].includes(v)?v:'All'}catch{return'All'}}
function writeCatalog(v:CatalogType){localStorage.setItem(CATALOG_KEY,JSON.stringify(v))}
function catalogType(item:any):Exclude<CatalogType,'All'>{const text=`${item?.category||''} ${item?.origin||''} ${(item?.breakdown||[]).join(' ')} ${item?.name||''}`.toLowerCase();if(/artifact|relic artifact|legendary artifact/.test(text))return'Artifact';if(/weapon module|module /.test(text)||String(item?.category||'').toLowerCase().includes('module'))return'Weapon Module';if(/inventory item|consumable|remedy|potion|tonic|bomb|shard|symbol|utility item/.test(text))return'Inventory Item';if(['Weapon','Armor','Shield','Accessory'].includes(item?.type))return item.type;return'Other'}
function hasCrisisRule(record:any){const text=[...(record?.skills||[]).map((s:any)=>`${s.name} ${s.summary}`),...(record?.notes||[])].join(' ').toLowerCase();return text.includes('crisis')}
function monsterMatches(record:any,state:MonsterFilters){const level=Number(record?.level)||0;if(state.min!==null&&level<state.min)return false;if(state.max!==null&&level>state.max)return false;if(state.role==='Spellcaster'&&!(record?.spells?.length>0))return false;if(state.role==='No Spells'&&record?.spells?.length>0)return false;if(state.role==='Has Crisis Rule'&&!hasCrisisRule(record))return false;if(state.damage){const atk=(record?.attacks||[]).some((a:any)=>String(a?.damageType||'').toLowerCase()===state.damage);const spell=(record?.spells||[]).some((s:any)=>String(s?.effect||'').toLowerCase().includes(`${state.damage} damage`));if(!atk&&!spell)return false}if(state.affinityType&&state.affinityValue&&String(record?.affinities?.[state.affinityType]||'Normal')!==state.affinityValue)return false;return true}
function visibleCards(section:HTMLElement){return Array.from(section.querySelectorAll<HTMLElement>('.monsterCard,.itemCard')).filter(card=>!card.classList.contains('dbHiddenByFavorite')&&!card.classList.contains('dbHiddenByMonsterInfo')&&!card.classList.contains('dbHiddenByTaxonomy'))}
function csvCell(v:unknown){return `"${String(v??'').replace(/"/g,'""')}"`}
function csv(kind:Kind,records:any[]){const rows:any[][]=kind==='monster'?[['Name','Source','Level','Rank','Species','Style','HP','MP','Initiative','Defense','Magic Defense','Traits','Attacks','Skills','Spells'],...records.map(r=>[r.name,r.source,r.level,r.rank,r.species,r.combatStyle||'Mixed',r.hp,r.mp,r.initiative,r.defense,r.magicDefense,(r.traits||[]).join('; '),(r.attacks||[]).map((a:any)=>a.name).join('; '),(r.skills||[]).map((s:any)=>s.name).join('; '),(r.spells||[]).map((s:any)=>s.name).join('; ')])]:[['Name','Source','Type','Category','Cost','Martial','Range','Handedness','Accuracy','Damage','Damage Type','Defense','Magic Defense','Initiative','Quality','Effect'],...records.map(r=>[r.name,r.source,r.type,r.category||'',r.cost,r.martial?'Yes':'No',r.range||'',r.handedness||'',r.accuracy||'',r.damage??'',r.damageType||'',r.defense||'',r.magicDefense||'',r.initiative??'',r.quality||'',r.effect||''])];return rows.map(row=>row.map(csvCell).join(',')).join('\n')}
function markdown(kind:Kind,records:any[]){return records.map(r=>kind==='monster'?`## ${r.name}\n\n${r.source} | Lv ${r.level} ${r.rank} ${r.species}${r.combatStyle?` | ${r.combatStyle}`:''}\n\n**HP** ${r.hp} | **MP** ${r.mp} | **Init** ${r.initiative} | **DEF** ${r.defense} | **M.DEF** ${r.magicDefense}\n\n**Traits:** ${(r.traits||[]).join(', ')}\n\n${(r.attacks||[]).map((a:any)=>`- **${a.name}** — ${a.formula}; ${a.damageType}${a.effect?`; ${a.effect}`:''}`).join('\n')}`:`## ${r.name}\n\n${r.source} | ${r.type}${r.category?` | ${r.category}`:''} | ${r.cost||0}z${r.martial?' | Martial':''}\n\n${r.quality?`**Quality:** ${r.quality}\n\n`:''}${r.effect||''}`).join('\n\n---\n\n')}
function download(name:string,text:string,type:string){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function option(value:string,label?:string){return `<option value="${value}">${label||value||'Any'}</option>`}

export default function DatabaseEnhancementHub(){useEffect(()=>{let scheduled=false
 const apply=()=>{document.querySelectorAll<HTMLElement>('main > section').forEach(section=>{if(!section.querySelector('.databaseSummary'))return;const k=kind(section);if(!k)return;const data=readArray(k==='monster'?'fu-monsters':'fu-items');const byId=new Map(data.map(r=>[r?.id,r]));
  if(k==='monster'){const state=readMonsterFilters();section.querySelectorAll<HTMLElement>('.monsterCard').forEach(card=>{const r=byId.get(card.dataset.dbRecordId);card.classList.toggle('dbHiddenByMonsterInfo',!!r&&!monsterMatches(r,state))});let bar=section.querySelector<HTMLElement>('.dbMonsterProfileFilters');if(!bar){bar=document.createElement('div');bar.className='dbMonsterProfileFilters';bar.dataset.dbHub='monster';section.querySelector('.toolbar')?.insertAdjacentElement('afterend',bar)}if(bar){const sig=JSON.stringify(state);if(bar.dataset.signature!==sig){bar.dataset.signature=sig;bar.innerHTML=`<span class="dbHubTitle">Monster profile filters</span><label>Lv <input data-db-hub-filter="min" type="number" min="1" max="99" placeholder="min" value="${state.min??''}"></label><span>–</span><label><input data-db-hub-filter="max" type="number" min="1" max="99" placeholder="max" value="${state.max??''}"></label><label>Role <select data-db-hub-filter="role">${['All','Spellcaster','No Spells','Has Crisis Rule'].map(v=>option(v)).join('')}</select></label><label>Deals <select data-db-hub-filter="damage">${damageTypes.map(v=>option(v,v||'Any')).join('')}</select></label><label>Affinity <select data-db-hub-filter="affinityType">${damageTypes.map(v=>option(v,v||'Any type')).join('')}</select><select data-db-hub-filter="affinityValue">${affinityValues.map(v=>option(v,v||'Any')).join('')}</select></label><button data-db-hub-clear type="button">Clear</button>`;(bar.querySelector('[data-db-hub-filter="role"]')as HTMLSelectElement).value=state.role;(bar.querySelector('[data-db-hub-filter="damage"]')as HTMLSelectElement).value=state.damage;(bar.querySelector('[data-db-hub-filter="affinityType"]')as HTMLSelectElement).value=state.affinityType;(bar.querySelector('[data-db-hub-filter="affinityValue"]')as HTMLSelectElement).value=state.affinityValue}}}
  else{const selected=readCatalog();section.querySelectorAll<HTMLElement>('.itemCard').forEach(card=>{const item=byId.get(card.dataset.dbRecordId);if(!item)return;const ct=catalogType(item);card.classList.toggle('dbHiddenByTaxonomy',selected!=='All'&&ct!==selected);const meta=card.querySelector<HTMLElement>('.itemMeta');let badge=meta?.querySelector<HTMLElement>('.dbCatalogBadge');if(meta&&!badge){badge=document.createElement('span');badge.className='dbCatalogBadge';meta.appendChild(badge)}if(badge)badge.textContent=ct});let bar=section.querySelector<HTMLElement>('.dbTaxonomyBar');if(!bar){bar=document.createElement('div');bar.className='dbTaxonomyBar';bar.dataset.dbHub='item';section.querySelector('.toolbar')?.insertAdjacentElement('afterend',bar)}if(bar){const html=`<label>Catalog type <select data-db-hub-catalog>${(['All','Weapon','Armor','Shield','Accessory','Artifact','Inventory Item','Weapon Module','Other'] as CatalogType[]).map(v=>`<option ${v===selected?'selected':''}>${v}</option>`).join('')}</select></label><span>Artifacts, modules and inventory items remain distinct catalog categories.</span>`;if(bar.dataset.signature!==html){bar.innerHTML=html;bar.dataset.signature=html}}}
  let tools=section.querySelector<HTMLElement>('.dbHubResultTools');if(!tools){tools=document.createElement('div');tools.className='dbHubResultTools';tools.dataset.dbHubKind=k;tools.innerHTML='<span class="dbHubTitle">Filtered results</span><button type="button" data-db-hub-json>Export JSON</button><button type="button" data-db-hub-csv>Export CSV</button><button type="button" data-db-hub-names>Copy names</button><button type="button" data-db-hub-md>Copy Markdown</button>';const quick=section.querySelector('.dbQuickActions');(quick||section.querySelector('.databaseSummary'))?.insertAdjacentElement('afterend',tools)}
 })}
 const onInput=(event:Event)=>{const target=event.target as HTMLElement;const filter=target.closest<HTMLInputElement|HTMLSelectElement>('[data-db-hub-filter]');if(filter){const state=readMonsterFilters();const key=filter.dataset.dbHubFilter as keyof MonsterFilters;if(key==='min'||key==='max')(state as any)[key]=filter.value===''?null:Number(filter.value);else(state as any)[key]=filter.value;writeMonsterFilters(state);apply();return}const catalog=target.closest<HTMLSelectElement>('[data-db-hub-catalog]');if(catalog){writeCatalog(catalog.value as CatalogType);apply()}}
 const onClick=(event:MouseEvent)=>{const target=event.target as HTMLElement;if(target.closest('[data-db-hub-clear]')){writeMonsterFilters({min:null,max:null,role:'All',damage:'',affinityType:'',affinityValue:''});apply();return}const button=target.closest<HTMLButtonElement>('[data-db-hub-json],[data-db-hub-csv],[data-db-hub-names],[data-db-hub-md]');if(!button)return;const section=button.closest<HTMLElement>('section');const k=section?kind(section):null;if(!section||!k)return;const all=readArray(k==='monster'?'fu-monsters':'fu-items');const byId=new Map(all.map(r=>[r?.id,r]));const records=visibleCards(section).map(card=>byId.get(card.dataset.dbRecordId)).filter(Boolean);const stamp=new Date().toISOString().slice(0,10);if(button.hasAttribute('data-db-hub-json'))download(`fabula-ultima-${k}-results-${stamp}.json`,JSON.stringify({format:'fabula-ultima-tools-filtered-results',version:1,kind:k,exportedAt:new Date().toISOString(),count:records.length,records},null,2),'application/json');else if(button.hasAttribute('data-db-hub-csv'))download(`fabula-ultima-${k}-results-${stamp}.csv`,csv(k,records),'text/csv;charset=utf-8');else navigator.clipboard?.writeText(button.hasAttribute('data-db-hub-md')?markdown(k,records):records.map(r=>r.name).join('\n')).catch(()=>undefined)}
 apply();const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;apply()})});observer.observe(document.body,{childList:true,subtree:true});document.addEventListener('input',onInput);document.addEventListener('change',onInput);document.addEventListener('click',onClick);return()=>{observer.disconnect();document.removeEventListener('input',onInput);document.removeEventListener('change',onInput);document.removeEventListener('click',onClick)}},[]);return null}
