import type { Monster, Species } from './rules'

const normalAffinities = { physical:'Normal', air:'Normal', bolt:'Normal', dark:'Normal', earth:'Normal', fire:'Normal', ice:'Normal', light:'Normal', poison:'Normal' } as const
const m = (id:string,name:string,level:number,species:Species,traits:string[],attrs:Monster['attributes'],hp:number,mp:number,initiative:number,defense:number,magicDefense:number,attacks:Monster['attacks'],skills:Monster['skills']=[],spells:Monster['spells']=[],aff:Partial<Monster['affinities']>={}):Monster => ({
  id:`official-core-${id}`, name, source:'Official', level, rank:'Soldier', soldierEquivalent:1, species, traits, attributes:attrs,
  hp, crisis:Math.floor(hp/2), mp, initiative, defense, magicDefense, accuracyBonus:Math.floor(level/10), magicBonus:Math.floor(level/10), levelDamageBonus:level>=40?10:level>=20?5:0, turnsPerRound:1, skillBudget:0,
  affinities:{...normalAffinities,...aff} as Monster['affinities'], attacks, skills, spells, notes:['Official profile — Fabula Ultima Core Rulebook Bestiary.'], combatStyle:'Mixed'
})
const a=(name:string,formula:string,damageType:string,effect?:string)=>({name,formula,damageType,effect})
const s=(name:string,summary:string)=>({name,summary})
const sp=(name:string,mp:string,target:string,effect:string)=>({name,mp,target,duration:'Instantaneous',effect})

export const officialMonsters: Monster[] = [
  m('cutterpillar','Cutterpillar',5,'Beast',['heavy','resilient','slow','territorial'],{dex:8,ins:6,mig:10,wlp:8},60,45,7,10,7,[a('Mandible Slash','DEX + MIG','poison','HR + 5 damage; target suffers weak.'),a('Cutter Ball','DEX + MIG','physical','HR + 5 damage; deals 5 extra damage if it Guarded on its previous turn.')],[s('Roll Up','When it Guards, gains Immunity to physical damage until the start of its next turn.')],[],{earth:'Resistant',fire:'Vulnerable',ice:'Vulnerable'}),
  m('giant-rat','Giant Rat',5,'Beast',['afraid of fire','fast','hungry','vicious'],{dex:12,ins:8,mig:6,wlp:6},40,35,14,12,8,[a('Bad Bite','DEX + MIG','physical','HR + 5 damage; target suffers poisoned.')],[s('Cornered Rat','While in Crisis, gains +3 to all Checks.'),s('Quick','May fill or erase an additional section of escape/pursuit Clocks.')],[],{earth:'Resistant',fire:'Vulnerable',poison:'Resistant'}),
  m('grey-howler','Grey Howler',5,'Beast',['loyal','perceptive','smart','vigilant'],{dex:10,ins:8,mig:8,wlp:6},50,35,9,10,8,[a('Vicious Bite','DEX + MIG +3','physical','HR + 10 damage.')],[s('Protect','May take the place of another character who is in danger.')],[],{physical:'Resistant',ice:'Resistant'}),
  m('vampire-bat','Vampire Bat',5,'Beast',['afraid of light','aggressive','loud','smart'],{dex:10,ins:8,mig:6,wlp:8},50,45,9,10,8,[a('Blood Drinker','DEX + DEX','physical','HR + 5 damage; recovers HP equal to half the HP loss suffered by the target.'),a('Screech','DEX + WLP','air','HR + 5 damage; target suffers dazed.')],[s('Flying','Can fly; loses the benefit in Crisis or when struck by a Vulnerability.')],[],{physical:'Vulnerable',earth:'Resistant',poison:'Resistant'}),
  m('bombard-ant','Bombard Ant',10,'Beast',['explosive','flammable','mindless','territorial'],{dex:10,ins:6,mig:10,wlp:6},70,40,12,10,6,[a('Ant Slam','DEX + MIG +1','physical','HR + 10 damage.'),a('Ant Cannon','DEX + INS +1','physical','HR + 5 damage; target suffers dazed.')],[s('Burrow','When Guarding on dirt, sand, or rock, gains +2 Defense and becomes Vulnerable to earth until next turn.'),s('Empty Mind','Immune to dazed and enraged.')],[],{bolt:'Resistant',fire:'Vulnerable',light:'Resistant'}),
  m('thornfish','Thornfish',10,'Beast',['aggressive','quick','small','thick-skinned'],{dex:10,ins:10,mig:6,wlp:6},50,40,14,10,10,[a('Thorn Dive','DEX + DEX +1','physical','HR + 10 damage.'),a('Ocean Jet','DEX + INS +1','ice','HR + 5 damage; target suffers slow.')],[s('Flying','Can fly; loses the benefit in Crisis or when struck by a Vulnerability.')],[],{air:'Vulnerable',bolt:'Resistant',earth:'Resistant',fire:'Resistant',ice:'Resistant',poison:'Resistant'}),
  m('sun-bear','Sun Bear',15,'Beast',['hairy','huge','peaceful','smart'],{dex:8,ins:8,mig:10,wlp:6},80,45,8,9,10,[a('Bear Hug','DEX + MIG +1','physical','HR + 10 damage; target suffers weak.')],[s('Powerful','Immune to slow and weak.'),s('Suntouched','While in Crisis, Bear Hug deals 5 extra damage and becomes fire damage.')],[],{air:'Resistant',bolt:'Vulnerable',earth:'Vulnerable',fire:'Resistant',ice:'Resistant',light:'Resistant'}),
  m('white-howler','White Howler',20,'Beast',['brave','cunning','regal','vigilant'],{dex:8,ins:8,mig:10,wlp:8},90,60,8,10,9,[a('White Maw','DEX + MIG +5','physical','HR + 15 damage; target suffers weak.')],[s('Regal Aura','Allies are immune to shaken.')],[sp('Iceberg','20','One creature','MIG + WLP +2; HR + 30 ice damage; ignores Resistances.'),sp('Lick Wounds','5','Self','Recover 30 HP (40 at level 40+, 50 at level 60+).')],{physical:'Resistant',fire:'Vulnerable',ice:'Resistant'}),

  m('arcane-lantern','Arcane Lantern',5,'Construct',['glowing','helpful','magical','tiny'],{dex:8,ins:8,mig:6,wlp:10},40,55,8,9,10,[a('Elemental Discharge','DEX + INS','variable','HR + 5 bolt, fire, or ice damage (roll d6).')],[s('Mana Transfer','Spend up to 10 MP; another visible creature recovers the same MP.'),s('Construct','Immune to poisoned.')],[],{physical:'Vulnerable',earth:'Resistant',fire:'Resistant',ice:'Resistant',poison:'Immune'}),
  m('clatterclown','Clatterclown',10,'Construct',['creepy','loud','small','vengeful'],{dex:8,ins:10,mig:8,wlp:6},60,50,13,8,10,[a('Jester Kick','DEX + INS +1','physical','HR + 5 damage; +5 damage against dazed or shaken targets.')],[s('Construct','Immune to poisoned.')],[sp('Dancing Jester','20','Any number of visible creatures','Each target suffers shaken.')],{physical:'Vulnerable',earth:'Resistant',fire:'Resistant',poison:'Immune'}),
  m('gargoyle','Gargoyle',10,'Construct',['bound to a location','cunning','floating','vigilant'],{dex:10,ins:8,mig:8,wlp:6},70,50,9,10,8,[a('Stone Claws','DEX + MIG +1','physical','HR + 5 damage; targets Magic Defense.')],[s('Construct','Immune to poisoned.'),s('Flying','Can fly; loses the benefit in Crisis or when struck by a Vulnerability.')],[sp('Stone Barrage','10','One creature','MIG + WLP +1; HR + 15 earth damage; target suffers dazed.')],{physical:'Resistant',earth:'Resistant',fire:'Resistant',ice:'Vulnerable',poison:'Immune'}),
  m('magitech-trooper','Magitech Trooper',10,'Construct',['loyal','predictable','ruthless','vigilant'],{dex:8,ins:8,mig:10,wlp:6},80,40,5,11,8,[a('Axe Strike','MIG + MIG +1','physical','HR + 14 damage; target suffers slow.')],[s('Construct','Immune to poisoned.'),s('Exposed Core','In Crisis, loses fire/ice Resistance and Axe Strike becomes bolt damage.')],[],{physical:'Vulnerable',air:'Vulnerable',earth:'Resistant',fire:'Resistant',ice:'Resistant',poison:'Immune'}),
  m('bronze-golem','Bronze Golem',15,'Construct',['clattering','looming','powerful','slow'],{dex:6,ins:8,mig:12,wlp:6},100,45,7,8,9,[a('Punch','DEX + MIG +1','physical','HR + 10 damage; target suffers dazed.'),a('Whirlwind','DEX + MIG +1','air','HR + 5 damage; multi (2).')],[s('Construct','Immune to poisoned.')],[],{physical:'Vulnerable',air:'Vulnerable',earth:'Resistant',poison:'Immune'}),
  m('razorbird','Razorbird',15,'Construct',['fast','flying','heavily armed','loyal'],{dex:10,ins:8,mig:8,wlp:6},80,45,9,10,8,[a('Razor Dive','DEX + DEX +1','physical','HR + 10 damage; loses Flying until next turn.'),a('Gatling Gun','DEX + INS +1','physical','HR + 5 damage; multi (2).'),a('Scorch Rocket','DEX + INS +1','fire','HR + 10 damage.')],[s('Construct','Immune to poisoned.'),s('Fast & Furious','Immune to slow and weak.'),s('Flying','Can fly; loses the benefit in Crisis or when struck by a Vulnerability.')],[],{physical:'Vulnerable',air:'Vulnerable',earth:'Resistant',fire:'Immune',ice:'Vulnerable',poison:'Immune'}),
  m('forest-golem','Forest Golem',20,'Construct',['emotionless','flammable','lonely','towering'],{dex:6,ins:6,mig:12,wlp:10},110,80,6,6,6,[a('Bark Claws','MIG + MIG +2','physical','HR + 10 damage; multi (2).'),a('Life Blast','DEX + MIG +2','light','HR + 15 damage.')],[s('Construct','Immune to poisoned.')],[sp('Dispel','10','One creature','Ends all Scene-duration spells affecting the target.'),sp('Spore Breath','10','One creature','MIG + WLP +2; HR + 15 poison damage; target suffers weak.'),sp('Vine Burst','20','Any number of visible creatures','Each target suffers shaken.')],{physical:'Resistant',air:'Resistant',earth:'Resistant',fire:'Vulnerable',ice:'Vulnerable',poison:'Immune'}),
]
