import { GeneratedItem } from './items'

const w = (id:string,name:string,cost:number,category:string,martial:boolean,accuracy:string,accuracyBonus:number,damage:number,handedness:'One-handed'|'Two-handed',range:'Melee'|'Ranged',damageType:GeneratedItem['damageType']='physical',effect='No Quality.',breakdown:string[]=[]):GeneratedItem => ({id:`official-${id}`,name,type:'Weapon',source:'Official',cost,category,martial,accuracy,accuracyBonus,damage,handedness,range,damageType,effect,breakdown})

export const officialWeapons: GeneratedItem[] = [
  w('core-staff','Staff',100,'Arcane',false,'WLP + WLP',0,6,'Two-handed','Melee'),
  w('core-tome','Tome',100,'Arcane',false,'INS + INS',0,6,'Two-handed','Melee'),
  w('core-crossbow','Crossbow',150,'Bow',false,'DEX + INS',0,8,'Two-handed','Ranged'),
  w('core-shortbow','Shortbow',200,'Bow',false,'DEX + DEX',0,8,'Two-handed','Ranged'),
  w('core-unarmed','Unarmed Strike',0,'Brawling',false,'DEX + MIG',0,0,'One-handed','Melee','physical','Automatically equipped in each empty hand slot.'),
  w('core-improvised-melee','Improvised (Melee)',0,'Brawling',false,'DEX + MIG',0,2,'One-handed','Melee','physical','Breaks after the attack.'),
  w('core-iron-knuckle','Iron Knuckle',150,'Brawling',false,'DEX + MIG',0,6,'One-handed','Melee'),
  w('core-steel-dagger','Steel Dagger',150,'Dagger',false,'DEX + INS',1,4,'One-handed','Melee'),
  w('core-pistol','Pistol',250,'Firearm',true,'DEX + INS',0,8,'One-handed','Ranged'),
  w('core-chain-whip','Chain Whip',150,'Flail',false,'DEX + DEX',0,8,'Two-handed','Melee'),
  w('core-iron-hammer','Iron Hammer',200,'Heavy',false,'MIG + MIG',0,6,'One-handed','Melee'),
  w('core-broadaxe','Broadaxe',250,'Heavy',true,'MIG + MIG',0,10,'One-handed','Melee'),
  w('core-waraxe','Waraxe',250,'Heavy',true,'MIG + MIG',0,14,'Two-handed','Melee'),
  w('core-light-spear','Light Spear',200,'Spear',true,'DEX + MIG',0,8,'One-handed','Melee'),
  w('core-heavy-spear','Heavy Spear',200,'Spear',true,'DEX + MIG',0,12,'Two-handed','Melee'),
  w('core-bronze-sword','Bronze Sword',200,'Sword',true,'DEX + MIG',1,6,'One-handed','Melee'),
  w('core-greatsword','Greatsword',200,'Sword',true,'DEX + MIG',1,10,'Two-handed','Melee'),
  w('core-katana','Katana',200,'Sword',true,'DEX + INS',1,10,'Two-handed','Melee'),
  w('core-rapier','Rapier',200,'Sword',true,'DEX + INS',1,6,'One-handed','Melee'),
  w('core-improvised-ranged','Improvised (Ranged)',0,'Thrown',false,'DEX + MIG',0,2,'One-handed','Ranged','physical','Breaks after the attack.'),
  w('core-shuriken','Shuriken',150,'Thrown',false,'DEX + INS',0,4,'One-handed','Ranged'),

  w('hf-dancing-knives-1','Dancing Knives — Dagger Form',400,'Dagger',true,'DEX + MIG',0,5,'Two-handed','Melee','physical','Quick; Transforming.','High Fantasy Atlas · Dancing Knives · Form I'.split(' · ')),
  w('hf-dancing-knives-2','Dancing Knives — Flail Form',400,'Flail',true,'DEX + MIG',2,10,'Two-handed','Ranged','physical','Accurate; Powerful; Transforming.','High Fantasy Atlas · Dancing Knives · Form II'.split(' · ')),
  w('hf-blazing-chains-1','Blazing Chains — Dagger Form',1200,'Dagger',true,'DEX + MIG',0,9,'Two-handed','Melee','fire','Deals 5 extra damage to demons and undead; Quick; Transforming.',['High Fantasy Atlas','Rare evolution','Form I']),
  w('hf-blazing-chains-2','Blazing Chains — Flail Form',1200,'Flail',true,'DEX + MIG',2,14,'Two-handed','Ranged','fire','Deals 5 extra damage to demons and undead; Accurate; Powerful; Transforming.',['High Fantasy Atlas','Rare evolution','Form II']),
  w('hf-grimoire-force','Grimoire of Force',300,'Arcane',true,'DEX + INS',0,5,'Two-handed','Ranged','physical','Magic Defense Boost; Quick.',['High Fantasy Atlas']),
  w('hf-grimoire-wind','Grimoire of Wind',1200,'Arcane',true,'DEX + INS',1,9,'Two-handed','Ranged','air','Immune to slow while equipped; Magic Defense Boost; Quick.',['High Fantasy Atlas','Rare evolution']),
  w('hf-hoplite-axe-1','Hoplite’s Axe — Spear Form',400,'Spear',false,'DEX + MIG',2,5,'Two-handed','Melee','physical','Accurate; Defense Boost; Transforming.',['High Fantasy Atlas','Form I']),
  w('hf-hoplite-axe-2','Hoplite’s Axe — Axe Form',400,'Heavy',true,'DEX + MIG',0,14,'Two-handed','Melee','bolt','Elemental; Powerful; Transforming.',['High Fantasy Atlas','Form II']),
  w('hf-dragonspine-1','Dragonspine — Spear Form',1600,'Spear',false,'DEX + MIG',2,9,'Two-handed','Melee','physical','Resistance to fire and ice; Accurate; Defense Boost; Transforming.',['High Fantasy Atlas','Rare evolution','Form I']),
  w('hf-dragonspine-2','Dragonspine — Axe Form',1600,'Heavy',true,'DEX + MIG',0,18,'Two-handed','Melee','bolt','Resistance to fire and ice; Elemental; Powerful; Transforming.',['High Fantasy Atlas','Rare evolution','Form II']),
  w('hf-guardian-claymore','Guardian Claymore',300,'Sword',true,'DEX + MIG',0,10,'Two-handed','Melee','physical','Defense Boost; Magic Defense Boost; Powerful.',['High Fantasy Atlas']),
  w('hf-queenswarden','Queenswarden',2700,'Sword',true,'DEX + MIG',1,14,'Two-handed','Melee','light','Additional +1 Defense and +1 Magic Defense; Defense Boost; Magic Defense Boost; Powerful.',['High Fantasy Atlas','Rare evolution']),
  w('hf-somber-memory','Somber Memory',300,'Bow',true,'DEX + INS',2,10,'Two-handed','Ranged','physical','Accurate; Magic Defense Boost; Powerful.',['High Fantasy Atlas']),
  w('hf-angelslayer','Angelslayer',1600,'Bow',true,'DEX + INS',2,14,'Two-handed','Ranged','dark','When you hit a flying target, you may force them to land immediately; Accurate; Magic Defense Boost; Powerful.',['High Fantasy Atlas','Rare evolution']),
  w('hf-cannon-gauntlets-1','Cannon Gauntlets — Brawling Form',400,'Brawling',true,'DEX + MIG',0,5,'Two-handed','Melee','physical','Quick; Transforming.',['High Fantasy Atlas','Form I']),
  w('hf-cannon-gauntlets-2','Cannon Gauntlets — Firearm Form',400,'Firearm',true,'DEX + MIG',0,10,'Two-handed','Melee','physical','Defense Boost; Powerful; Transforming.',['High Fantasy Atlas','Form II']),
  w('hf-groundsplitters-1','Groundsplitters — Brawling Form',2000,'Brawling',true,'DEX + MIG',2,5,'Two-handed','Melee','earth','Targets hit suffer dazed; Accurate; Defense Boost; Transforming.',['High Fantasy Atlas','Rare evolution','Form I']),
  w('hf-groundsplitters-2','Groundsplitters — Firearm Form',2000,'Firearm',true,'DEX + MIG',0,10,'Two-handed','Melee','earth','Targets hit suffer dazed; Defense Boost; Powerful; Transforming.',['High Fantasy Atlas','Rare evolution','Form II']),
  w('hf-giant-shuriken','Giant Shuriken',300,'Thrown',true,'DEX + INS',2,10,'Two-handed','Ranged','physical','Accurate; Defense Boost; Powerful.',['High Fantasy Atlas']),
  w('hf-pale-presence','Pale Presence',1600,'Thrown',true,'DEX + INS',2,14,'Two-handed','Ranged','ice','Attacks have multi (2); Accurate; Defense Boost; Powerful.',['High Fantasy Atlas','Rare evolution']),
]
