import { GeneratedItem } from './items'

const w = (id:string,name:string,cost:number,category:string,martial:boolean,accuracy:string,accuracyBonus:number,damage:number,handedness:'One-handed'|'Two-handed',range:'Melee'|'Ranged',damageType:GeneratedItem['damageType']='physical',effect='No Quality.',source='Atlas'):GeneratedItem => ({
  id:`official-${id}`,
  name,
  type:'Weapon',
  source:'Official',
  cost,
  category,
  martial,
  accuracy,
  accuracyBonus,
  damage,
  handedness,
  range,
  damageType,
  effect,
  breakdown:[source,'Rare weapon'],
})

export const officialAtlasRareWeapons: GeneratedItem[] = [
  // High Fantasy Atlas
  w('hf-bringer-of-justice','Bringer of Justice',600,'Brawling',false,'DEX + MIG',1,6,'One-handed','Melee','physical','When you use Provoke against a creature whose current HP are higher than yours, the Skill is automatically successful.','High Fantasy Atlas'),
  w('hf-chimera-tail','Chimera Tail',900,'Flail',true,'DEX + DEX',0,12,'Two-handed','Melee','physical','Attacks with this weapon deal 1 extra damage for every different creature Species among those you learned your known Chimerist spells from.','High Fantasy Atlas'),
  w('hf-major-arcana','Major Arcana',900,'Thrown',false,'DEX + INS',0,4,'One-handed','Ranged','physical','While merged with an Arcanum, Accuracy Checks with this weapon trigger a critical success if both dice show the same number and it is not a fumble.','High Fantasy Atlas'),
  w('hf-midas','Midas',900,'Dagger',false,'DEX + INS',1,4,'One-handed','Melee','dark','When Soul Steal succeeds against an elite or champion, the value of their soul treasure increases by 100 zenit.','High Fantasy Atlas'),
  w('hf-achilles','Achilles',1000,'Spear',true,'DEX + MIG',0,12,'One-handed','Melee','physical','As long as your current HP are equal to or greater than your maximum HP, you are immune to all status effects.','High Fantasy Atlas'),
  w('hf-bestiarium','Bestiarium',1200,'Arcane',false,'INS + INS',0,6,'Two-handed','Melee','light','You gain a +2 bonus to Magic Checks targeting creatures of which you know two or more Traits; this also applies to Opposed Checks against them.','High Fantasy Atlas'),
  w('hf-chiaroscuro','Chiaroscuro',1200,'Arcane',true,'INS + WLP',0,10,'Two-handed','Melee','physical','When you apply a symbol to one or more creatures, choose one: each of them recovers 5 HP, or each of them loses 5 HP.','High Fantasy Atlas'),
  w('hf-floating-edge','Floating Edge',1200,'Sword',true,'DEX + INS',1,10,'Two-handed','Melee','air','Damage dealt by spells you cast with a total MP cost of 20 or lower ignores Immunities and Resistances.','High Fantasy Atlas'),
  w('hf-grim-waltz','Grim Waltz',1200,'Spear',true,'DEX + MIG',0,12,'Two-handed','Melee','physical','After you reduce a creature to 0 HP with this weapon, you may immediately perform a dance with an Instantaneous duration among those you have learned; its MP cost cannot be lower than 10.','High Fantasy Atlas'),
  w('hf-heavy-metal','Heavy Metal',1200,'Heavy',true,'MIG + MIG',0,14,'Two-handed','Melee','bolt','When you attack with this weapon using Vibrato, all damage dealt by the attack becomes the same type as the key type of the last verse you sang.','High Fantasy Atlas'),
  w('hf-tametomo','Tametomo',1500,'Bow',true,'DEX + DEX',0,12,'Two-handed','Ranged','ice','Attacks with this weapon deal 5 extra damage against creatures suffering from slow and/or shaken.','High Fantasy Atlas'),
  w('hf-immernacht','Immernacht',1800,'Bow',false,'DEX + DEX',0,8,'Two-handed','Ranged','dark','When a creature includes you among the targets of an offensive spell, if you are in Crisis, that creature must spend HP instead of MP to cast the spell.','High Fantasy Atlas'),
  w('hf-ultimatum','Ultimatum',1800,'Firearm',true,'DEX + INS',1,12,'One-handed','Ranged','earth','When a creature includes you among the targets of an attack or offensive spell, they must first spend 5 MP; otherwise they cannot include you among the targets.','High Fantasy Atlas'),
  w('hf-revenger','Revenger',2000,'Heavy',true,'MIG + MIG',0,14,'One-handed','Melee','fire','When a creature inflicts a status effect on you, that creature also suffers the same status effect, unless you were immune to it or already suffering from it.','High Fantasy Atlas'),

  // Natural Fantasy Atlas
  w('nf-ladle','Ladle',500,'Thrown',false,'DEX + INS',0,8,'One-handed','Ranged','physical','If you have acquired Made with Love, treat your Skill Level in it as increased by 1, up to a maximum of SL 4.','Natural Fantasy Atlas'),
  w('nf-camera-obscura','Camera Obscura',600,'Arcane',false,'INS + INS',0,6,'Two-handed','Melee','dark','When you obtain a result of 13 or higher in a Check made to examine the profile of one or more enemies that you can see, if you have Spell Mimic, you can choose one of those enemies; if it knows one or more spells, you may learn one of them as a Chimerist spell.','Natural Fantasy Atlas'),
  w('nf-memorialis','Memorialis',700,'Spear',true,'DEX + MIG',1,12,'Two-handed','Melee','physical','When you use Ripple, recover 5 MP.','Natural Fantasy Atlas'),
  w('nf-blazing-fan','Blazing Fan',800,'Brawling',true,'DEX + MIG',1,6,'One-handed','Melee','fire','Your invocations that target two or more creatures deal extra damage equal to your Skill Level in Linked Invocations.','Natural Fantasy Atlas'),
  w('nf-derringer','Derringer',800,'Firearm',false,'DEX + INS',1,8,'One-handed','Ranged','physical','The first attack you perform with this weapon during each scene deals 5 extra damage. Despite being shaped like a pistol, this is not considered a martial weapon.','Natural Fantasy Atlas'),
  w('nf-bronze-libra','Bronze Libra',900,'Arcane',false,'INS + INS',0,6,'Two-handed','Melee','earth','After you perform a Magic Check, if the value of one die is a multiple of the other, regain Inventory Points equal to half your Skill Level in Winds of Trade, rounded down.','Natural Fantasy Atlas'),
  w('nf-giant-fork','Giant Fork',1000,'Spear',true,'DEX + MIG',0,16,'Two-handed','Melee','physical','When you use this weapon with Knife and Fork, you may add the High Roll to the attack damage; this cannot reduce the total below 0.','Natural Fantasy Atlas'),
  w('nf-viper-bone','Viper Bone',1200,'Dagger',false,'DEX + INS',1,8,'One-handed','Melee','poison','Attacks with this weapon deal 5 extra damage as long as it is not your turn.','Natural Fantasy Atlas'),
  w('nf-summer-masher','Summer Masher',1300,'Heavy',true,'MIG + MIG',0,18,'Two-handed','Melee','ice','When you hit only one creature with this weapon, if that creature belongs to the Plant Species, the attack deals 10 extra damage. Then, if that creature is in Crisis, you and every ally who can see you recover MP equal to your High Roll in the Accuracy Check.','Natural Fantasy Atlas'),
  w('nf-norimitsu','Norimitsu',1400,'Sword',true,'DEX + INS',1,14,'Two-handed','Melee','physical','Attacks with this weapon deal 6 extra damage to elite- or champion-rank creatures.','Natural Fantasy Atlas'),
  w('nf-the-barrel','The Barrel',1500,'Heavy',true,'MIG + MIG',0,18,'Two-handed','Melee','physical','When you hit one or more creatures with this weapon, you may spend 1 Trade Point. If you do, the attack deals extra damage equal to five times your Skill Level in Private Stock.','Natural Fantasy Atlas'),
  w('nf-pinwheel-rod','Pinwheel Rod',1600,'Arcane',false,'WLP + WLP',0,6,'Two-handed','Melee','air','As long as one of your spells or invocations deals air damage, it deals 10 extra damage.','Natural Fantasy Atlas'),
  w('nf-voltaic-hound','Voltaic Hound',1600,'Firearm',true,'DEX + INS',1,16,'Two-handed','Ranged','bolt','After this weapon deals damage to one or more creatures, if at least one of those creatures is Vulnerable to bolt damage, you may deal 10 bolt damage to every enemy you can see.','Natural Fantasy Atlas'),
  w('nf-hirundo','Hirundo',1800,'Bow',true,'DEX + DEX',0,12,'Two-handed','Ranged','light','After resolving Encourage, you may perform a free attack with this weapon. If you do, treat your High Roll as 0 when calculating damage dealt by that attack.','Natural Fantasy Atlas'),

  // Techno Fantasy Atlas
  w('tf-connector','Connector',600,'Flail',false,'DEX + DEX',0,8,'Two-handed','Melee','physical','You gain a +2 bonus to Checks you perform for Magitech Override.','Techno Fantasy Atlas'),
  w('tf-therion-ripper','Therion Ripper',700,'Brawling',true,'DEX + MIG',1,10,'One-handed','Melee','physical','This weapon deals extra damage equal to your Skill Level in Akromorphosis, and its Category is always identical to that of your unarmed strikes. It also benefits from the Akromorphosis Heroic Skill as if it were an unarmed strike.','Techno Fantasy Atlas'),
  w('tf-carbon-bow','Carbon Bow',800,'Bow',false,'DEX + DEX',1,8,'Two-handed','Ranged','physical','Attacks with this weapon treat the target’s Defense as equal to their current Dexterity die size.','Techno Fantasy Atlas'),
  w('tf-grenade-launcher','Grenade Launcher',1000,'Firearm',true,'DEX + INS',0,16,'Two-handed','Ranged','physical','When you apply an infusion to an attack made with this weapon, that attack deals extra damage equal to your Skill Level in Gadgets.','Techno Fantasy Atlas'),
  w('tf-ignition-spear','Ignition Spear',1000,'Spear',true,'DEX + MIG',0,16,'Two-handed','Melee','fire','When you use Compression Tech to summon your personal vehicle, you can pay 10 MP instead of the normal Inventory Point cost.','Techno Fantasy Atlas'),
  w('tf-interlace-ring','Interlace Ring',1000,'Arcane',false,'WLP + WLP',0,6,'One-handed','Melee','physical','You halve the MP cost of all Rituals tied to the soul network that you perform through Cognitive Ghost or Navigator.','Techno Fantasy Atlas'),
  w('tf-scale-thresher','Scale Thresher',1100,'Heavy',true,'MIG + MIG',0,14,'Two-handed','Melee','physical','When you use Breach, if you hit the target you may choose two of the available options instead of one. If you choose only one option, the target loses MP equal to your High Roll in the Accuracy Check.','Techno Fantasy Atlas'),
  w('tf-rngenerator','RNGenerator',1200,'Thrown',false,'DEX + INS',0,8,'One-handed','Ranged','dark','When you cast Gamble, if you have Lucky Seven you can use it to replace one die you rolled; this counts as the use of Lucky Seven for the scene.','Techno Fantasy Atlas'),
  w('tf-steady-knuckles','Steady Knuckles',1200,'Brawling',true,'DEX + MIG',0,10,'One-handed','Melee','physical','As long as the current die size of one of your Attributes is higher than its base die size, your attacks with this weapon deal extra damage equal to your Skill Level in Withstand.','Techno Fantasy Atlas'),
  w('tf-butterfly-dream','Butterfly Dream',1300,'Sword',true,'DEX + INS',1,10,'One-handed','Melee','air','When you hit one or more creatures with this weapon, if your Brainwave Clock has 2 or more filled sections, you can erase 1.','Techno Fantasy Atlas'),
  w('tf-azotophore','Azotophore',1400,'Dagger',false,'DEX + INS',1,8,'One-handed','Melee','ice','Spells you cast that deal ice damage deal 5 extra damage.','Techno Fantasy Atlas'),
  w('tf-seismic-pillar','Seismic Pillar',1600,'Heavy',true,'MIG + MIG',0,18,'Two-handed','Melee','earth','Damage dealt by this weapon to creatures whose current Might die size is lower than yours ignores Immunities and Resistances.','Techno Fantasy Atlas'),
  w('tf-sniper-rifle','Sniper Rifle',1800,'Firearm',true,'DEX + INS',1,16,'Two-handed','Ranged','physical','If you have Hawkeye, treat your Skill Level in it as increased by 3, up to a maximum of SL 8.','Techno Fantasy Atlas'),
  w('tf-thunder-vulcan','Thunder Vulcan',3000,'Firearm',true,'DEX + INS',1,16,'Two-handed','Ranged','bolt','The first time during a turn you use the Attack action with this weapon, you can perform up to three attacks against one or multiple targets. If you do, all of these attacks follow the two-weapon fighting rules.','Techno Fantasy Atlas'),
]
