import { GeneratedItem } from './items'

const w = (id:string,name:string,cost:number,category:string,martial:boolean,accuracy:string,accuracyBonus:number,damage:number,handedness:'One-handed'|'Two-handed',range:'Melee'|'Ranged',damageType:GeneratedItem['damageType']='physical',effect='No Quality.'):GeneratedItem => ({
  id:`official-core-rare-${id}`,
  name,
  type:'Weapon',
  source:'Official',
  cost,
  category,
  martial,
  accuracy,
  accuracyBonus,
  damage,
  handedness,
  range,
  damageType,
  effect,
  breakdown:['Core Rulebook','Sample Rare Weapon',category],
})

export const officialCoreRareWeapons: GeneratedItem[] = [
  // Arcane
  w('blessed-mace','Blessed Mace',200,'Arcane',false,'WLP + WLP',0,2,'One-handed','Melee','light'),
  w('encyclopedia','Encyclopedia',600,'Arcane',false,'INS + INS',0,6,'Two-handed','Melee','physical','You are immune to dazed.'),
  w('ars-goetia','Ars Goetia',800,'Arcane',false,'INS + INS',0,6,'Two-handed','Melee','light','You gain +2 to Magic Checks and Opposed Checks against demons.'),
  w('ferula','Ferula',1050,'Arcane',false,'INS + WLP',0,2,'One-handed','Melee','physical','You gain +1 to Magic Checks.'),
  w('tyrants-scepter','Tyrant’s Scepter',1200,'Arcane',false,'WLP + WLP',0,6,'Two-handed','Melee','dark','Whenever you hit one or more creatures, each loses 10 MP.'),
  w('cultes-des-ghoules','Cultes des Ghoules',1400,'Arcane',false,'INS + INS',0,6,'One-handed','Melee','air','When you hit one or more creatures, you may recover 5 HP.'),
  w('caduceus','Caduceus',1600,'Arcane',false,'WLP + WLP',0,6,'Two-handed','Melee','physical','Spells you cast that restore HP restore 5 extra HP.'),
  w('necronomicon','Necronomicon',1800,'Arcane',false,'INS + WLP',1,6,'Two-handed','Melee','dark','When you hit one or more creatures with an offensive spell, each suffers shaken.'),
  w('yellow-book','Yellow Book',2100,'Arcane',false,'INS + INS',0,6,'Two-handed','Melee','physical','Spells you cast deal 5 extra damage.'),
  w('rafflesia-staff','Rafflesia Staff',2200,'Arcane',false,'WLP + WLP',0,6,'Two-handed','Melee','poison','When you hit one or more creatures with an offensive spell, each suffers poisoned.'),

  // Bow
  w('hand-crossbow','Hand Crossbow',150,'Bow',false,'DEX + INS',0,4,'One-handed','Ranged'),
  w('composite-bow','Composite Bow',250,'Bow',false,'DEX + MIG',1,8,'Two-handed','Ranged'),
  w('siegebreaker','Siegebreaker',750,'Bow',true,'DEX + INS',0,12,'Two-handed','Ranged','physical','Damage dealt by this weapon ignores Resistances.'),
  w('yoichi','Yoichi',900,'Bow',false,'DEX + DEX',1,8,'Two-handed','Ranged','air','You are immune to shaken.'),
  w('thundering-bow','Thundering Bow',1000,'Bow',false,'DEX + DEX',0,8,'Two-handed','Ranged','bolt','You have Resistance to bolt damage.'),
  w('looting-bow','Looting Bow',1250,'Bow',false,'DEX + INS',0,8,'Two-handed','Ranged','fire','When you reduce a creature to 0 HP with this weapon, you may immediately recover 2 Inventory Points.'),
  w('gatling-crossbow','Gatling Crossbow',1350,'Bow',true,'DEX + INS',0,12,'Two-handed','Ranged','physical','Attacks with this weapon have multi (2).'),
  w('dragontrap-bow','Dragontrap Bow',1500,'Bow',true,'DEX + DEX',0,12,'Two-handed','Ranged','earth','When you hit a flying target, you may force it to land immediately.'),
  w('frozen-envy','Frozen Envy',1500,'Bow',true,'DEX + DEX',0,12,'Two-handed','Ranged','ice','When you hit one or more creatures, if you have at least one Bond of inferiority, you may recover 5 MP.'),
  w('gorgon-eye','Gorgon Eye',2000,'Bow',true,'DEX + DEX',0,12,'Two-handed','Ranged','poison','Each target hit by this weapon suffers slow.'),
  w('artemis','Artemis',2100,'Bow',true,'DEX + DEX',1,12,'Two-handed','Ranged','light','You have Immunity to dark damage.'),

  // Brawling
  w('nekode','Nekode',250,'Brawling',false,'DEX + MIG',1,6,'One-handed','Melee'),
  w('hellfist','Hellfist',350,'Brawling',false,'DEX + MIG',0,6,'One-handed','Melee','dark','Attacks with this weapon target Magic Defense.'),
  w('frozen-grasp','Frozen Grasp',750,'Brawling',false,'DEX + MIG',0,6,'One-handed','Melee','ice','You are immune to enraged.'),
  w('bear-paw','Bear Paw',850,'Brawling',true,'DEX + MIG',0,10,'One-handed','Melee','physical','You are immune to weak.'),
  w('fuel-knuckle','Fuel Knuckle',950,'Brawling',false,'DEX + MIG',0,6,'One-handed','Melee','fire','You have Resistance to fire damage.'),
  w('silver-talon','Silver Talon',1100,'Brawling',false,'DEX + DEX',0,6,'One-handed','Melee','light','You gain +1 Magic Defense.'),
  w('old-bandages','Old Bandages',1250,'Brawling',false,'DEX + MIG',1,6,'One-handed','Melee','physical','You have Resistance to dark and poison damage.'),
  w('storm-fist','Storm Fist',1300,'Brawling',false,'MIG + MIG',0,6,'One-handed','Melee','bolt','Attacks with this weapon have multi (2).'),
  w('lobster-claw','Lobster Claw',1950,'Brawling',true,'DEX + MIG',1,10,'One-handed','Melee','physical','Each target hit by this weapon suffers slow.'),
  w('dozer-glove','Dozer Glove',2000,'Brawling',true,'MIG + MIG',0,10,'One-handed','Melee','earth','Each target hit by this weapon suffers dazed.'),
  w('venom-claw','Venom Claw',2250,'Brawling',false,'DEX + MIG',1,6,'One-handed','Melee','physical','Each target hit by this weapon suffers poisoned.'),
  w('god-hand','God Hand',2550,'Brawling',true,'DEX + MIG',1,10,'One-handed','Melee','light','Damage dealt by this weapon ignores Immunities.'),

  // Dagger
  w('latrodectus','Latrodectus',250,'Dagger',false,'DEX + INS',1,4,'One-handed','Melee','poison'),
  w('heart-knife','Heart Knife',550,'Dagger',false,'DEX + WLP',0,4,'One-handed','Melee','light','Deals 5 extra damage to demons.'),
  w('atom-slicer','Atom Slicer',600,'Dagger',false,'DEX + DEX',1,4,'One-handed','Melee','physical','Damage dealt by this weapon ignores Resistances.'),
  w('silent-edge','Silent Edge',700,'Dagger',false,'DEX + DEX',0,4,'One-handed','Melee','air','You are immune to slow.'),
  w('spell-sever','Spell Sever',850,'Dagger',false,'DEX + INS',1,4,'One-handed','Melee','dark','When you hit a single target, you may end one Scene-duration spell affecting it.'),
  w('assassins-blade','Assassin’s Blade',1000,'Dagger',false,'DEX + INS',1,4,'One-handed','Melee','physical','Deals 5 extra damage to targets in Crisis.'),
  w('gourmet-cutter','Gourmet Cutter',1350,'Dagger',false,'DEX + INS',1,8,'One-handed','Melee','physical','When you hit one or more creatures, you may recover 5 HP.'),
  w('barbed-knife','Barbed Knife',1650,'Dagger',false,'DEX + INS',1,4,'One-handed','Melee','physical','Each target hit by this weapon suffers shaken.'),
  w('cold-finger','Cold Finger',1950,'Dagger',false,'DEX + INS',1,8,'One-handed','Melee','ice','Each target hit by this weapon suffers weak.'),
  w('hornet','Hornet',2200,'Dagger',false,'DEX + DEX',1,4,'One-handed','Melee','physical','Attacks with this weapon have multi (3).'),
  w('frantic-nail','Frantic Nail',2450,'Dagger',false,'INS + INS',1,8,'One-handed','Melee','fire','Each target hit by this weapon suffers enraged.'),

  // Firearm
  w('revolver','Revolver',300,'Firearm',true,'DEX + DEX',0,8,'One-handed','Ranged'),
  w('istinggar','Istinggar',350,'Firearm',true,'DEX + INS',1,12,'Two-handed','Ranged'),
  w('spellshot','Spellshot',400,'Firearm',true,'INS + INS',0,8,'One-handed','Ranged','physical','Attacks with this weapon target Magic Defense.'),
  w('diamond-pistol','Diamond Pistol',650,'Firearm',true,'DEX + INS',1,8,'One-handed','Ranged','physical','Deals 5 extra damage to constructs.'),
  w('headhunter','Headhunter',800,'Firearm',true,'DEX + INS',0,8,'One-handed','Ranged','physical','Deals 5 extra damage to targets you have a Bond of hatred toward.'),
  w('comet-gun','Comet Gun',950,'Firearm',true,'DEX + INS',1,8,'One-handed','Ranged','dark','You are immune to dazed.'),
  w('bunker-cannon','Bunker Cannon',1050,'Firearm',true,'DEX + INS',0,12,'Two-handed','Ranged','physical','You gain +1 Defense.'),
  w('alchemusket','Alchemusket',1300,'Firearm',true,'DEX + INS',0,8,'One-handed','Ranged','poison','Potions created with Inventory Points deal 5 extra damage and restore 5 extra HP.'),
  w('calamity','Calamity',1550,'Firearm',true,'DEX + INS',0,16,'Two-handed','Ranged','fire','Attacks with this weapon have multi (2).'),
  w('freezing-shot','Freezing Shot',1850,'Firearm',true,'DEX + INS',0,8,'One-handed','Ranged','ice','Each target hit by this weapon suffers slow.'),
  w('quatermain','Quatermain',2600,'Firearm',true,'DEX + INS',1,12,'Two-handed','Ranged','air','Deals extra damage equal to the difference between your current and maximum Inventory Points.'),

  // Flail
  w('old-whip','Old Whip',650,'Flail',false,'DEX + DEX',0,8,'Two-handed','Melee','physical','Deals 5 extra damage to beasts and monsters.'),
  w('dusk-star','Dusk Star',750,'Flail',false,'DEX + DEX',0,4,'One-handed','Melee','dark','You are immune to shaken.'),
  w('witchbane','Witchbane',800,'Flail',false,'DEX + DEX',1,8,'Two-handed','Melee','physical','Damage reduces the target’s MP instead of HP; excess damage carries over to HP.'),
  w('salamander','Salamander',1000,'Flail',false,'DEX + MIG',0,8,'One-handed','Melee','physical','You have Resistance to fire damage.'),
  w('nunchaku','Nunchaku',1100,'Flail',false,'DEX + MIG',0,8,'One-handed','Melee','physical','You gain +1 Defense.'),
  w('dominatrix','Dominatrix',1200,'Flail',false,'DEX + WLP',0,8,'One-handed','Melee','fire','You gain +2 to Accuracy Checks and Magic Checks against enraged targets.'),
  w('whipblade','Whipblade',1400,'Flail',true,'DEX + MIG',1,12,'Two-handed','Melee','physical','Attacks with this weapon have multi (2).'),
  w('silk-wire','Silk Wire',1450,'Flail',true,'DEX + DEX',0,12,'Two-handed','Melee','physical','You have Resistance to physical damage.'),
  w('kusarigama','Kusarigama',1650,'Flail',false,'DEX + DEX',0,8,'Two-handed','Melee','physical','Each target hit by this weapon suffers slow.'),
  w('jormungand','Jormungand',2400,'Flail',true,'DEX + MIG',0,12,'Two-handed','Melee','dark','Attacks with this weapon have multi (3).'),
  w('koi-whisker','Koi Whisker',2800,'Flail',true,'DEX + WLP',0,12,'Two-handed','Melee','physical','You have Immunity to dark and light damage.'),

  // Heavy
  w('bardiche','Bardiche',350,'Heavy',true,'MIG + MIG',1,14,'Two-handed','Melee'),
  w('artisans-mallet','Artisan’s Mallet',450,'Heavy',false,'INS + MIG',0,6,'One-handed','Melee','physical','Deals 5 extra damage to constructs.'),
  w('beowulf','Beowulf',550,'Heavy',true,'MIG + MIG',0,10,'One-handed','Melee','physical','Deals 5 extra damage to monsters.'),
  w('belly-of-the-beast','Belly of the Beast',650,'Heavy',true,'MIG + MIG',0,14,'Two-handed','Melee','poison','Deals 5 extra damage to humanoids.'),
  w('forest-hatchet','Forest Hatchet',750,'Heavy',true,'MIG + MIG',0,10,'One-handed','Melee','physical','Deals 5 extra damage to beasts and plants.'),
  w('adamanthammer','Adamanthammer',1050,'Heavy',true,'MIG + MIG',0,14,'Two-handed','Melee','physical','You gain +1 Defense.'),
  w('aura-hammer','Aura Hammer',1350,'Heavy',true,'MIG + MIG',0,14,'Two-handed','Melee','light','Attacks with this weapon have multi (2).'),
  w('gravity-mace','Gravity Mace',1850,'Heavy',true,'MIG + MIG',0,14,'Two-handed','Melee','earth','Each target hit by this weapon suffers slow.'),
  w('mjolnir','Mjolnir',1850,'Heavy',true,'MIG + MIG',0,10,'One-handed','Melee','bolt','Each target hit by this weapon suffers dazed.'),
  w('wyrmwing','Wyrmwing',2050,'Heavy',true,'MIG + MIG',0,18,'Two-handed','Melee','fire','You have Immunity to fire damage.'),
  w('soul-of-pillage','Soul of Pillage',2550,'Heavy',true,'MIG + MIG',0,18,'Two-handed','Melee','dark','Each target hit by this weapon suffers enraged.'),
  w('winter-kolossus','Winter Kolossus',2550,'Heavy',true,'MIG + MIG',0,18,'Two-handed','Melee','ice','You gain +1 Defense and +1 Magic Defense.'),

  // Spear
  w('dragontongue','Dragontongue',500,'Spear',true,'DEX + MIG',1,12,'Two-handed','Melee','fire','Attacks with this weapon target Magic Defense.'),
  w('rocinante','Rocinante',500,'Spear',true,'DEX + MIG',0,8,'One-handed','Melee','physical','Deals 1 extra damage per status effect you have.'),
  w('serpent-spear','Serpent Spear',800,'Spear',true,'DEX + MIG',0,16,'Two-handed','Melee','physical','Damage dealt by this weapon ignores Resistances.'),
  w('halberd','Halberd',1000,'Spear',true,'DEX + MIG',0,12,'Two-handed','Melee','physical','You gain +1 Defense.'),
  w('narwhalhorn','Narwhalhorn',1200,'Spear',true,'DEX + MIG',0,12,'One-handed','Melee','ice','You have Resistance to ice damage.'),
  w('brave-glaive','Brave Glaive',1300,'Spear',true,'MIG + WLP',0,12,'Two-handed','Melee','earth','With at least three Bonds of loyalty or affection, you gain +1 Defense and +1 Magic Defense.'),
  w('morrigan','Morrigan',1400,'Spear',true,'DEX + MIG',1,12,'Two-handed','Melee','dark','When you hit one or more creatures, you may recover 10 MP.'),
  w('gae-bolg','Gae Bolg',1800,'Spear',true,'DEX + MIG',1,12,'Two-handed','Melee','physical','On a critical success with this weapon, you may spend the opportunity to deal 10 extra damage.'),
  w('longinus','Longinus',2000,'Spear',true,'DEX + MIG',1,16,'Two-handed','Melee','physical','Each target hit by this weapon suffers weak.'),
  w('nine-teeth-rake','Nine-teeth Rake',2500,'Spear',true,'DEX + MIG',0,16,'Two-handed','Melee','poison','You Absorb poison damage.'),
  w('gungnir','Gungnir',3000,'Spear',true,'DEX + MIG',0,16,'Two-handed','Melee','light','You have Immunity to fire and ice damage.'),

  // Sword
  w('zweihander','Zweihänder',400,'Sword',true,'DEX + MIG',1,14,'Two-handed','Melee'),
  w('falling-rain','Falling Rain',450,'Sword',true,'DEX + DEX',1,10,'Two-handed','Melee','ice','Attacks with this weapon target Magic Defense.'),
  w('flamberge','Flamberge',500,'Sword',true,'DEX + MIG',1,10,'One-handed','Melee','fire'),
  w('elegant-edge','Elegant Edge',700,'Sword',true,'DEX + INS',1,6,'One-handed','Melee','physical','You are immune to enraged.'),
  w('joyeuse','Joyeuse',900,'Sword',true,'MIG + WLP',1,10,'One-handed','Melee','physical','You are immune to shaken.'),
  w('deathblade','Deathblade',1000,'Sword',true,'DEX + MIG',1,6,'One-handed','Melee','dark','Deals 5 extra damage if you are in Crisis.'),
  w('gunsword','Gunsword',1000,'Sword',true,'DEX + MIG',1,10,'Two-handed','Melee','physical','This weapon can target flying creatures.'),
  w('main-gauche','Main Gauche',1000,'Sword',true,'DEX + MIG',1,6,'One-handed','Melee','physical','You gain +1 Defense.'),
  w('the-rikizo','The Rikizo',1200,'Sword',true,'DEX + INS',1,10,'Two-handed','Melee','physical','Deals 2 extra damage for each Class you have mastered.'),
  w('flesh-eater','Flesh Eater',1300,'Sword',true,'MIG + MIG',0,10,'One-handed','Melee','poison','Deals 5 extra damage to weak targets.'),
  w('kusanagi','Kusanagi',1500,'Sword',true,'DEX + MIG',1,14,'Two-handed','Melee','air','Attacks with this weapon have multi (2).'),
  w('excalibur','Excalibur',2300,'Sword',true,'MIG + WLP',1,10,'Two-handed','Melee','light','You are immune to all status effects.'),

  // Thrown
  w('crescent-edge','Crescent Edge',350,'Thrown',false,'DEX + INS',0,4,'One-handed','Ranged','light','Attacks with this weapon target Magic Defense.'),
  w('meteor-star','Meteor Star',350,'Thrown',false,'DEX + INS',1,4,'One-handed','Ranged','fire'),
  w('throwing-axe','Throwing Axe',350,'Thrown',false,'DEX + MIG',0,8,'One-handed','Ranged'),
  w('boomerang','Boomerang',750,'Thrown',false,'DEX + MIG',1,4,'One-handed','Ranged','physical','Deals 5 extra damage to beasts and monsters.'),
  w('wind-dancer','Wind Dancer',850,'Thrown',false,'DEX + WLP',0,8,'One-handed','Ranged','air','Damage dealt by this weapon ignores Resistances.'),
  w('acupuncturer','Acupuncturer',950,'Thrown',false,'DEX + INS',1,8,'One-handed','Ranged','physical','You are immune to poisoned.'),
  w('blue-pinwheel','Blue Pinwheel',950,'Thrown',false,'DEX + INS',0,4,'One-handed','Ranged','ice','You have Resistance to ice damage.'),
  w('crones-needle','Crone’s Needle',1050,'Thrown',false,'DEX + INS',1,4,'One-handed','Ranged','earth','You have Resistance to dark damage.'),
  w('chakram','Chakram',1250,'Thrown',false,'DEX + MIG',1,4,'One-handed','Ranged','physical','Attacks with this weapon have multi (2).'),
  w('vajra','Vajra',2050,'Thrown',false,'DEX + WLP',1,8,'One-handed','Ranged','bolt','Each target hit by this weapon suffers shaken.'),
  w('dark-orbit','Dark Orbit',2250,'Thrown',false,'DEX + INS',0,4,'One-handed','Ranged','dark','You gain +1 Defense and +1 Magic Defense.'),
  w('hive-dart','Hive Dart',2300,'Thrown',false,'DEX + DEX',0,4,'One-handed','Ranged','poison','Each target hit by this weapon suffers poisoned.'),
]
