import type { Monster, Species, Rank } from './rules'

const normal = { physical:'Normal', air:'Normal', bolt:'Normal', dark:'Normal', earth:'Normal', fire:'Normal', ice:'Normal', light:'Normal', poison:'Normal' } as const
const a=(name:string,formula:string,damageType:string,effect?:string)=>({name,formula,damageType,effect})
const s=(name:string,summary:string)=>({name,summary})
const sp=(name:string,mp:string,target:string,effect:string,duration='Instantaneous')=>({name,mp,target,duration,effect})
const m=(id:string,name:string,level:number,rank:Rank,eq:number,species:Species,traits:string[],attrs:Monster['attributes'],hp:number,mp:number,initiative:number,defense:number,magicDefense:number,attacks:Monster['attacks'],skills:Monster['skills']=[],spells:Monster['spells']=[],aff:Partial<Monster['affinities']>={},notes:string[]=[]):Monster=>({
  id:`official-techno-${id}`,name,source:'Official',level,rank,soldierEquivalent:eq,species,traits,attributes:attrs,
  hp,crisis:Math.floor(hp/2),mp,initiative,defense,magicDefense,accuracyBonus:Math.floor(level/10),magicBonus:Math.floor(level/10),levelDamageBonus:level>=40?10:level>=20?5:0,turnsPerRound:eq,skillBudget:0,
  affinities:{...normal,...aff} as Monster['affinities'],attacks,skills,spells,notes:['Official profile - Fabula Ultima Atlas: Techno Fantasy.',...notes],combatStyle:'Mixed'
})

export const officialTechnoFantasyMonsters: Monster[] = [
  m('commissioner-vyne','Commissioner Vyne',10,'Champion',3,'Humanoid',['arrogant','authoritarian','cruel','violent'],{dex:6,ins:8,mig:8,wlp:10},180,140,8,11,10,[a('Shield Bash','MIG + MIG +4','physical','HR + 5 damage.'),a('Shock Baton','MIG + WLP +4','bolt','HR + 6 damage and target suffers shaken.')],[
    s('Cannon Fodder','When about to take damage, redirect it to a visible ally Resistant/Immune to that type; while in Crisis the ally is chosen randomly.'),
    s('Crush the Worms','Against targets suffering status effects, deal +5 damage plus +1 per status effect.'),
    s('Infamous','Other creatures cannot recover from shaken while Vyne is present.'),
    s('Make it Rain!','Using Charge! on a surveillance drone gives its Suppressive Fire multi (2).'),
    s('Media Presence','+3 to Opposed Checks using public persona or media manipulation.'),
    s("You're Done When I Say So",'When a visible creature reaches 0 HP and is not shaken, immediately make a free Shock Baton attack; if it hits, deal no damage, target cannot Surrender/Sacrifice, recovers 20 HP and suffers dazed and shaken.')
  ],[sp('Charge!','20','One creature','Target may immediately perform a free weapon/basic attack.')],{bolt:'Resistant',dark:'Resistant',earth:'Vulnerable',light:'Vulnerable',poison:'Vulnerable'},['Printed page 186.']),

  m('eight','Eight (VIII)',20,'Champion',2,'Construct',['imposing','loyal to the Squadron','radicalized','strategic'],{dex:8,ins:10,mig:10,wlp:6},200,100,15,9,10,[a('Linebreaker Tackle','DEX + MIG +2','earth','HR + 10 damage.'),a('Ion Cannon','DEX + INS +2','bolt','HR + 10 damage.')],[
    s('Construct','Immune to poisoned.'),s('Defensive Swarm','When Seven/Nine suffer damage, spend 20 MP to halve that damage before Affinities; Eight loses HP equal to prevented damage.'),s('Flying','Can fly.'),s('Seven, Nine! No!','First time Seven/Nine reach 0 HP, Eight recovers all lost HP, gains +3 Accuracy for scene, suffers enraged and cannot recover from it.'),s('Squad Tactics','At round start choose Defensive Formation (+2 DEF/M.DEF to allies), Magebreaker Protocol (+10 MP cost to enemy spells/Skills), or No Quarter (+5 damage dealt and suffered by squad).')
  ],[],{air:'Vulnerable',bolt:'Resistant',dark:'Vulnerable',earth:'Resistant',light:'Resistant',poison:'Immune'},['Printed page 192.']),

  m('nine','Nine (IX)',20,'Soldier',1,'Construct',['disillusioned','loyal to the Squadron','reckless','undisciplined'],{dex:6,ins:8,mig:8,wlp:12},80,80,7,8,8,[a('Typhoon Missile','INS + MIG +2','air','HR + 15 damage.')],[s('Construct','Immune to poisoned.'),s('Flying','Can fly.'),s("I'll Cover You!",'When Eight misses with Linebreaker Tackle, make a free Typhoon Missile against the same target with HR treated as 0.'),s("Perhaps It's Better This Way",'While in Crisis cannot recover from status effects.'),s('Seven, Eight! No!','First time Seven/Eight reach 0 HP, may cast Gamma Cannon for free against their attacker; afterwards all damage dealt ignores Resistances.')],[sp('Gamma Cannon','10','One creature','INS + WLP +5; HR + 20 ice damage and target suffers weak.'),sp('Ventus','10 x T','Up to three creatures','INS + WLP +5; HR + 20 air damage; flying targets hit are forced to land.')],{air:'Resistant',bolt:'Vulnerable',earth:'Resistant',fire:'Vulnerable',poison:'Immune'},['Printed page 193.']),

  m('seven','Seven (VII)',20,'Soldier',1,'Construct',['acrobatic','calm','loyal to the Squadron','radicalized'],{dex:8,ins:10,mig:8,wlp:8},80,70,9,8,8,[a('Caduceus Lance','DEX + WLP +2','dark','HR + 10 damage.')],[s('Construct','Immune to poisoned.'),s('Eight, Nine! No!','First time Eight/Nine reach 0 HP, Seven may keep one or both at exactly 1 HP; once per scene per character.'),s('Energy Feedback','When Eight misses with Ion Cannon, one visible ally regains 10 MP.'),s('Flying','Can fly.'),s('Repair Subroutine','At start of turn, choose one ally to immediately recover from weak or slow.')],[sp('Heal','10 x T','Up to three creatures','Each target recovers 50 HP.')],{dark:'Resistant',earth:'Resistant',fire:'Resistant',ice:'Vulnerable',light:'Vulnerable',poison:'Immune'},['Printed page 194.']),

  m('primary-core','DeepFusion - Primary Core',30,'Champion',3,'Demon',['corrupted','gluttonous','uncreative','uncritical'],{dex:8,ins:10,mig:6,wlp:10},270,200,12,8,8,[a('Unstable Diffusion','DEX + INS +3','bolt','Damage equals the last damage suffered by the primary core this scene, max 40.'),a('Antivirus Program','INS + WLP +3','light','HR + 10 damage; if target has status effects, loses MP equal to damage but recovers from all statuses.')],[s('Binary Presence','Inside the soul network, HR 1, 10 or 11 also creates an opportunity, even on a fumble.'),s('CTRL + C / CTRL + V','When a creature creates a potion, elemental shard or symbol with Inventory, the core copies its basic effect onto itself.'),s('Digital Augmentation','While at least one digital limb is present, the core loses its standard Vulnerabilities.'),s('Rewrite the Code','On an opportunity in the soul network, roll d8: dazed 1-2, weak 3-4, slow 5-6, shaken 7-8; if core already has it, core recovers, otherwise all creatures suffer it.')],[sp('Computer Virus','10 x T','Up to three creatures','INS + WLP +3; each target suffers poisoned.'),sp('CTRL + ALT + DEL','30','Special','Choose any number of visible creatures; each suffers 35 bolt damage. Once per turn, only during the core’s last turn.')],{bolt:'Immune',earth:'Vulnerable',fire:'Vulnerable',ice:'Absorb',light:'Resistant',poison:'Immune'},['Printed page 198.']),

  m('digital-limb-a','DeepFusion - Digital Limb A',30,'Soldier',1,'Demon',['nimble','powerful','rendered','temporary'],{dex:10,ins:8,mig:10,wlp:6},120,60,13,8,8,[a('Identify and Acquire','DEX + MIG +6','light','HR + 10 damage and target suffers slow; inside soul network gains multi (2).')],[s('Component Optimization','When recovering from one or more status effects, also recover 10 HP.')],[],{physical:'Immune',air:'Vulnerable',dark:'Vulnerable',ice:'Resistant',light:'Resistant',poison:'Immune'},['Printed page 199.']),

  m('digital-limb-b','DeepFusion - Digital Limb B',30,'Soldier',1,'Demon',['nimble','predictable','rendered','temporary'],{dex:8,ins:10,mig:8,wlp:8},100,70,9,9,10,[a('IF (...) ELSE','INS + WLP +3','physical','Targets Magic Defense and deals no damage: dazed forces Attack next turn; weak loses 20 HP; slow loses one action next turn; shaken loses 20 MP.')],[s('Component Optimization','When recovering from one or more status effects, also recover 10 HP.')],[],{physical:'Immune',dark:'Vulnerable',earth:'Vulnerable',ice:'Resistant',light:'Resistant',poison:'Immune'},['Printed page 199.']),

  m('relentless','The Relentless',40,'Champion',3,'Construct',['colossal','mechanical','tenacious','transport'],{dex:6,ins:10,mig:10,wlp:10},390,180,11,8,8,[a('Ramming Speed','INS + MIG +4','physical','HR + 20 damage.'),a('Aurora Batteries','INS + WLP +4','light','HR + 20 damage; type depends on Target Locked. If no Vulnerable-type damage was suffered this round, target also suffers dazed, weak, slow and shaken.'),a('Fire!','DEX + INS +4','fire','HR + 15 damage; multi (2).')],[s('No Hesitation','While in Crisis spend 10 MP to suffer dazed and deal +5 damage with all attacks while dazed.'),s('Target Locked','Choose a visible enemy; Aurora Batteries becomes air, fire or light, and ship becomes Vulnerable to bolt, ice or dark respectively until the attack is used.'),s('Code Red','While in Crisis and dazed, DEF and M.DEF are 16; suffering Vulnerable damage in Crisis ends dazed.'),s('Construct','Immune to poisoned.'),s('Flying','Can fly.')],[],{physical:'Resistant',air:'Resistant',earth:'Resistant',fire:'Resistant',light:'Resistant',poison:'Immune'},['Printed page 202.']),

  m('attack-wing','Attack Wing',40,'Soldier',1,'Construct',['fast','light','nimble','small'],{dex:12,ins:10,mig:8,wlp:6},120,70,15,8,8,[a('Armor Breaker Missile','DEX + MIG +4','fire','HR + 20 damage; until start of next turn, all damage to target ignores Resistances.'),a('Laser Burst','DEX + INS +4','light','HR + 15 damage; multi (2).')],[s('Construct','Immune to poisoned.'),s('Flying','Can fly.'),s('Reinforcements!','At 0 HP, if Relentless is present and not in Crisis, return to 60 HP and Relentless loses 60 HP.')],[],{air:'Resistant',bolt:'Vulnerable',earth:'Resistant',fire:'Resistant',poison:'Immune'},['Printed page 203.']),

  m('support-wing','Support Wing',40,'Soldier',1,'Construct',['fast','light','nimble','small'],{dex:10,ins:12,mig:6,wlp:8},120,80,11,8,8,[a('Jammer Beam','DEX + INS +4','bolt','HR + 15 damage and target suffers dazed; targets Magic Defense.')],[s('Construct','Immune to poisoned.'),s('Flying','Can fly.'),s('Reinforcements!','At 0 HP, if Relentless is present and not in Crisis, return to 60 HP and Relentless loses 60 HP.')],[],{physical:'Resistant',air:'Resistant',bolt:'Resistant',earth:'Resistant',fire:'Vulnerable',light:'Resistant',poison:'Immune'},['Printed page 203.']),

  m('admiral-ceryon','Admiral Ceryon',40,'Soldier',1,'Humanoid',['cowardly','cruel','egotistical','opportunistic'],{dex:10,ins:10,mig:8,wlp:8},120,80,9,9,9,[a('Gunshot','DEX + INS +4','physical','HR + 22 damage.'),a('Frantic Burst','DEX + INS +4','physical','HR + 22 damage; multi (2), only if Ceryon has no ally on the scene.')],[s('Do Something, You Stupid Beast!','Bioengine recovers 30 HP and deals +5 damage until Ceryon’s next turn.'),s('Seal the Bulkheads!','Next PC Check to fill the To the Bridge! Clock suffers -5.'),s('Escape Plan','At end of each turn fill 1 Escape Pod Clock section, or 2 if To the Bridge! is full.')],[],{physical:'Resistant',air:'Resistant',bolt:'Resistant',dark:'Resistant',earth:'Resistant',fire:'Resistant',ice:'Resistant'},['Printed page 204.']),

  m('bioengine','Bioengine',40,'Champion',3,'Monster',['aching','engineered','eyeless','mighty'],{dex:12,ins:6,mig:12,wlp:6},420,140,12,10,12,[a('Smash','MIG + MIG +4','physical','HR + 20 damage.'),a('Lightning Quill','DEX + MIG +4','bolt','HR + 15 damage and target suffers slow.')],[s('Adrenal Overcharge','Lose 50 HP; Lightning Quill gains multi (2) until end of next turn.'),s('Bioelectric Converter','When suffering physical damage, lose MP equal to damage; if this does not reduce MP to 0, that source becomes bolt damage.'),s('Growing Anger','Non-bolt/non-physical damage grants Rage Points; at 5+, lose all Rage Points, regain 10 HP per point and make a free Lightning Quill with +1 damage per point.'),s('His Love, Returned','When To the Bridge! reaches 8, if alive and Ceryon has not left, Bioengine destroys the bridge and both are doomed.'),s('Painful Anger','First time entering Crisis, gain 5 Rage Points.'),s('Short Circuit','At 0 HP, To the Bridge! Clock is immediately filled.')],[],{air:'Resistant',bolt:'Absorb',dark:'Resistant',earth:'Resistant',fire:'Resistant',ice:'Vulnerable',light:'Vulnerable',poison:'Resistant'},['Printed page 205.']),

  m('patriarch','Innocentius XV - The Patriarch',50,'Champion',3,'Humanoid',['charismatic','egotistic','manipulative','zealous'],{dex:6,ins:10,mig:8,wlp:12},420,220,9,12,13,[a("Patriarch's Scepter",'WLP + WLP +5','physical','HR + 16 damage.')],[s('Ontological Proscription','Name a randomly chosen PC Class; until used again, characters with that Class cannot use Skill/Spell actions to use Skills or spells from that Class.'),s('Deep Insight','When completely filling a Clock via diplomacy/charm/deception/intimidation, learn a secret about another creature.'),s('Heed My Words','+3 to Checks to persuade, convince or deceive.'),s('Witness My Conviction','When recovering MP while in Crisis, recover 10 additional MP.')],[sp('Blinding Light','10','One creature','INS + WLP +8; HR + 35 light damage and target suffers dazed.'),sp('Enveloping Shadow','10','One creature','INS + WLP +8; HR + 35 dark damage and target suffers slow.'),sp('Judgment','30','Special','Any number of visible creatures suffer 50 light damage; once per turn, only on last turn.'),sp('Gospel of Strife','10 x T','Up to three creatures','INS + WLP +8; each target suffers enraged.')],{dark:'Immune',ice:'Vulnerable',light:'Immune',poison:'Vulnerable'},['Printed page 210. Innocentius XV phase 1.']),

  m('right-hand','Innocentius XV - Right Hand',50,'Soldier',1,'Humanoid',['cruel','loyal','stealthy','violent'],{dex:10,ins:10,mig:8,wlp:8},140,90,14,11,10,[a('Bloodletting','DEX + INS +8','physical','Target recovers from all status effects but loses 20 HP per status removed.'),a('Memento Mori','DEX + INS +9','ice','HR + 20 damage and target suffers weak and slow; targets Magic Defense.')],[],[],{air:'Resistant',dark:'Resistant',fire:'Vulnerable',ice:'Resistant',light:'Vulnerable',poison:'Resistant'},['Printed page 211.']),

  m('left-hand','Innocentius XV - Left Hand',50,'Soldier',1,'Humanoid',['devout','loyal','silent','zealous'],{dex:10,ins:8,mig:10,wlp:8},160,100,6,14,10,[a('Ipse Dixit','DEX + INS +5','physical','HR + 22 damage and target suffers dazed and shaken; while Patriarch is in Crisis, +5 damage.')],[s('Outrageous!','After a creature hits the Right Hand with an attack/offensive spell, Left Hand performs Ipse Dixit against that creature.')],[sp('In Corpore Sano','30 x T','Up to three creatures','Each target recovers 40 HP and all status effects.')],{physical:'Resistant',air:'Resistant',bolt:'Vulnerable',dark:'Vulnerable',fire:'Resistant',ice:'Resistant',light:'Resistant',poison:'Resistant'},['Printed page 211.']),

  m('conceptual-dyad','Innocentius XV - Conceptual Dyad',50,'Champion',5,'Demon',['analytical','arrogant','imposing','incongruous'],{dex:8,ins:10,mig:8,wlp:10},700,200,18,11,11,[a('Direct Proof','INS + WLP +8','physical','HR + 20 damage; targets whichever of Defense or Magic Defense is lower.'),a('Indirect Proof','DEX + MIG +8','physical','HR + 15 damage; multi (2), or multi (3) in Crisis.')],[s('Imperishable Dyad','Recover from all status effects, losing 20 MP per status healed.'),s('Manifest Dyad','Declare Pneuma (dark/light), Psyche (air/bolt), or Soma (fire/ice/earth); until next use, while not in Crisis and with MP, Immune to all damage except the two/three types in the concept.'),s('Reductio ad Absurdum','Deal 9999 typeless damage to one visible PC.'),s('Proof by Construction','Direct/Indirect Proof damage becomes the most advantageous type of the current amplified concept.'),s('Proof by Deduction','Taking current-concept damage exposes the Dyad to the other type; taking an exposed type makes it Vulnerable to both until next Manifest Dyad.'),s('Proof by Induction','When missed by attack/offensive spell, gain 1 Axiom Point; at 5+, spend all to raise DEF/M.DEF to 99 until HP is lost.')],[],{physical:'Resistant',earth:'Vulnerable',poison:'Resistant'},['Printed page 212. Innocentius XV phase 2.']),

  m('pure-concept','Innocentius XV - The Pure Concept',50,'Champion',5,'Monster',['apathetic','divine','incomprehensible','inhuman'],{dex:8,ins:8,mig:8,wlp:8},560,200,12,11,11,[a('So Below','DEX + MIG +5','physical','HR + 15 damage; roll d6 for type: physical 1-2, earth 3-4, poison 5-6.'),a('As Above','INS + WLP +5','physical','HR + 15 damage; roll d6 for type: air 1-2, ice 3-4, light 5-6.')],[s('Glory','Increase all Attributes one die size until scene end, cumulative to d12.'),s('Transcendence','Recover from all status effects, remove any carried symbol, and end all Scene-duration spells affecting the Pure Concept.'),s('Magnum Opus','When As Above/So Below would cause PC HP loss while Pure Concept is in Crisis or has odd HP, instead fill Foundations of a New Universe Clock by the HP that would be lost.'),s('Paradise Lost','First time entering Crisis, erase that Clock; each PC recovers 9999 MP and gains Fabula Points based on erased sections.'),s('Power of Creation','First damage suffered each round while not in Crisis becomes light and cannot change.'),s('Power of Disruption','When dealing damage to a PC, they may spend 1 Fabula Point; otherwise they also lose MP equal to damage.'),s('Power of Transformation','When suffering a new status effect, every other creature suffers the same status.')],[sp('Kaleidomachy','10 x T','Up to three creatures','MIG + WLP +5; HR + 25 damage of the same type as the last damage suffered by the Pure Concept this scene.')],{physical:'Resistant',air:'Resistant',bolt:'Vulnerable',dark:'Resistant',earth:'Immune',fire:'Vulnerable',ice:'Resistant',light:'Absorb',poison:'Immune'},['Printed page 213. Innocentius XV phase 3.'])
]
