import type { Monster, Species, Rank } from './rules'

const normal = { physical:'Normal', air:'Normal', bolt:'Normal', dark:'Normal', earth:'Normal', fire:'Normal', ice:'Normal', light:'Normal', poison:'Normal' } as const
const a=(name:string,formula:string,damageType:string,effect?:string)=>({name,formula,damageType,effect})
const s=(name:string,summary:string)=>({name,summary})
const sp=(name:string,mp:string,target:string,effect:string,duration='Instantaneous')=>({name,mp,target,duration,effect})
const m=(id:string,name:string,level:number,rank:Rank,eq:number,species:Species,traits:string[],attrs:Monster['attributes'],hp:number,mp:number,initiative:number,defense:number,magicDefense:number,attacks:Monster['attacks'],skills:Monster['skills']=[],spells:Monster['spells']=[],aff:Partial<Monster['affinities']>={},notes:string[]=[]):Monster=>({
  id:`official-high-${id}`,name,source:'Official',level,rank,soldierEquivalent:eq,species,traits,attributes:attrs,
  hp,crisis:Math.floor(hp/2),mp,initiative,defense,magicDefense,accuracyBonus:Math.floor(level/10),magicBonus:Math.floor(level/10),levelDamageBonus:level>=40?10:level>=20?5:0,turnsPerRound:eq,skillBudget:0,
  affinities:{...normal,...aff} as Monster['affinities'],attacks,skills,spells,notes:['Official profile — Fabula Ultima Atlas: High Fantasy.',...notes],combatStyle:'Mixed'
})

export const officialHighFantasyMonsters: Monster[] = [
  m('eileen','Eileen, Pirate Queen',10,'Champion',3,'Humanoid',['authoritarian','charismatic','cunning','rebellious'],{dex:8,ins:8,mig:8,wlp:8},180,120,12,13,9,[
    a('Harpoon (form I)','DEX + MIG +4','physical','HR + 10 damage.'),
    a('Revolver (form II)','DEX + INS +4','physical','HR + 5 damage; may perform two separate attacks using two-weapon fighting rules; while in Crisis, damage becomes fire.')
  ],[
    s('Strike Now!','Spend 10 MP and choose one visible ally; that ally immediately performs a free basic attack.'),
    s('Calm Seas','While not in Crisis, allies on the scene gain +2 to Accuracy and Magic Checks.'),
    s('Charismatic Presence','On a successful Opposed Check involving charisma or crew, fills/erases 1 additional Clock section.'),
    s('Fox Garb','Immune to slow while wearing the armor.'),
    s('Lady of Fortune','After an Accuracy Check with matching dice that is not a fumble, may trigger a critical success; HR counts as 0 for damage.'),
    s('Stormy Seas','While in Crisis, immune to shaken and loses poison Vulnerability.'),
    s('Equipment','Fox garb; transforming revolver-harpoon custom weapon.')
  ],[sp('Soaring Strike','10','Self','Make a free Harpoon attack; +5 damage, can reach ranged-only targets, and can force a flying target to land.')],{air:'Resistant',bolt:'Vulnerable',ice:'Resistant',poison:'Vulnerable'}),

  m('salamander','Salamander',10,'Soldier',1,'Beast',['flesh-eater','loyal','trained','vicious'],{dex:8,ins:8,mig:10,wlp:6},70,50,13,8,8,[a('Burning Bite','DEX + MIG +1','fire','HR + 5 damage; target suffers slow and shaken.')],[s('Opportunist','When an ally triggers a critical success, that opportunity may grant the salamander a free Burning Bite attack.')],[sp('Burning Breath','5','One creature','INS + WLP +1; HR + 10 fire damage.')],{fire:'Immune',ice:'Vulnerable'}),
  m('cryomander','Cryomander',10,'Soldier',1,'Beast',['flesh-eater','loyal','trained','vicious'],{dex:8,ins:8,mig:10,wlp:6},70,50,9,10,9,[a('Freezing Bite','DEX + MIG +1','ice','HR + 5 damage; +5 damage against slow targets.')],[s('Bodyguard','When Guarding to provide cover, that ally gains Resistance to all damage types until the start of the cryomander’s next turn.'),s('Opportunist','When an ally triggers a critical success, that opportunity may grant the cryomander a free Freezing Bite attack.')],[sp('Freezing Breath','5','One creature','INS + WLP +1; HR + 10 ice damage.')],{fire:'Vulnerable',ice:'Immune'}),
  m('pirate','Pirate',10,'Soldier',1,'Humanoid',['brave','insightful','loyal','noisy'],{dex:8,ins:8,mig:8,wlp:8},60,50,13,8,10,[a('Saber','DEX + MIG +4','physical','HR + 6 damage.'),a('Pistol','DEX + INS +4','physical','HR + 8 damage.')],[s('Hang On, Boss!','If Eileen is present and in Crisis, spend 10 MP to have her recover 10 HP.'),s('Braggart','Gains +3 to Hinder Checks used to inflict slow or shaken.'),s('Equipment','Pistol, saber, silk shirt.')],[],{physical:'Resistant',air:'Resistant',ice:'Vulnerable'}),

  m('flame-dragon','Flame Dragon',20,'Champion',4,'Monster',['ancient','colossal','territorial','ruthless'],{dex:8,ins:8,mig:10,wlp:8},360,120,13,9,10,[a('Piercing Fangs','DEX + MIG +2','physical','HR + 15 damage.'),a('Rending Claws','DEX + MIG +2','physical','HR + 10 damage; gains multi (2) while in Crisis.')],[
    s('Gift of Flame','Spend 10 MP and choose a visible creature’s equipped weapon; all damage dealt by that weapon becomes fire until scene end or until Gift of Flame is used again.'),
    s('Draconic Vitality','First time it enters Crisis each scene: recover 20 HP, recover from all status effects, lose Hardened Scales, and increase MIG one die size for the scene.'),
    s('Flying','Can fly.'),
    s('Fuel to the Fire','Whenever a single source causes 30+ HP loss, next Draconic Breath deals +5 damage; stacks until used.'),
    s('Hardened Scales','While airborne, Resistance to all damage types except ice.'),
    s('Rain of Fire','While not in Crisis, Draconic Breath costs 10 × T MP and can target up to two creatures.'),
    s('Reverential Fear','Shaken creatures suffer -2 to Accuracy and Opposed Checks against the dragon.')
  ],[sp('Draconic Breath','10','One creature','MIG + WLP +2; HR + 15 fire damage; +5 damage to shaken targets.'),sp('Thundering Roar','20','Special','Any number of visible creatures suffer shaken.')],{fire:'Immune',ice:'Vulnerable'}),

  m('cerine','Cerine, Mournful Lady',30,'Champion',3,'Undead',['bitter','devout','jaded','priestess'],{dex:8,ins:10,mig:6,wlp:10},270,220,14,10,14,[a('Heart of the Goddess','INS + INS +3','light','HR + 11 damage; when hitting one or more creatures, Cerine recovers 5 HP.')],[s('Soulshift','Spend any amount of MP to have another creature on the scene recover that much MP.'),s('All Light Casts a Shadow','When Cerine or an ally she can see deals dark or light damage, she may change that source to the opposite type.'),s('Undead','Immune to poisoned; HP recovery may harm her. If armor is lost, becomes Vulnerable to light.'),s('Equipment','Heart of the Goddess; holy cloak.')],[
    sp('Acceleration','20','One creature','Target gains one additional action each turn; spell ends after it grants two additional actions.','Scene'),
    sp('Dispel','10','One creature','Ends all Scene-duration spells affecting the target.'),
    sp('Enrage','10','One creature','MIG + WLP +6; target suffers enraged and cannot Guard or Spell on next turn.'),
    sp('Forced Tribute','10','One creature','MIG + WLP +6; target loses HR + 15 MP; Cerine recovers half the MP lost.'),
    sp('Lux','10 × T','Up to three creatures','INS + WLP +6; HR + 20 light damage; opportunity: dazed.')
  ],{dark:'Immune',fire:'Resistant',light:'Normal',poison:'Immune'}),

  m('cecilia','Cecilia',30,'Elite',2,'Undead',['capable','devout','heroic','silent'],{dex:8,ins:6,mig:10,wlp:10},0,280,9,14,10,[a('Resentment','DEX + MIG +7','dark','HR + 15 damage; ignores Resistances.')],[s('Martyr’s Slash','Spend 10 MP to make a free Resentment attack; it gains multi (2) and +5 damage.'),s('Arcane Resurrection','Has no HP; effects that would change HP instead change MP.'),s('Undead','Immune to poisoned; HP recovery may harm her. If armor is lost, becomes Vulnerable to light.'),s('Undying Devotion','Can always Protect Cerine without needing to recharge.'),s('Equipment','Paladin’s cuirass; Resentment greatsword.')],[sp('Cleanse','5 × T','Up to three creatures','Each target recovers from all status effects.')],{dark:'Immune',fire:'Vulnerable',poison:'Immune'},['HP is Special in the printed profile: Cecilia uses MP as her health track.']),

  m('spectral-servant','Spectral Servant',30,'Soldier',1,'Undead',['cruel','mindless','murderous','silent'],{dex:10,ins:8,mig:10,wlp:6},110,60,13,9,10,[a('Dark Claws','DEX + MIG +3','dark','HR + 10 damage; target suffers weak.')],[s('Bodyguard','When Guarding to provide cover, the covered ally gains Resistance to all damage until the start of the servant’s next turn.'),s('Rage Claw','After a creature hits or misses the servant with a melee attack, the servant may immediately make a free Dark Claws attack against it.'),s('Undead','Immune to poisoned; HP recovery may harm it.')],[],{dark:'Immune',light:'Vulnerable',poison:'Immune'}),

  m('maximilian-prince','Maximilian, the Prince',40,'Champion',3,'Humanoid',['ambitious','dignified','honorable','proud'],{dex:8,ins:8,mig:10,wlp:10},390,200,7,14,10,[a('Bronze Sword','DEX + MIG +5','physical','HR + 16 damage; +10 damage if target’s current MIG die is smaller than Maximilian’s.'),a('Shield Bash','DEX + MIG +4','physical','HR + 15 damage; target suffers weak.')],[s('Smash Through','Spend 10 MP to make a free Shield Bash followed by a free Bronze Sword attack against the same target; HR counts as 0 for both damage rolls.'),s('Clash of Wills','If targeted by an offensive spell and Maximilian’s WLP die is larger than the caster’s, +2 Magic Defense against that spell.'),s('Endure Alone','When Guarding without providing cover, recover from all status effects except enraged.'),s('Instinctive Dodge','If targeted by an attack and Maximilian’s DEX die is larger than the attacker’s, +2 Defense against that attack.'),s('Punishment','After being hit by a melee attack, may immediately make a free Shield Bash against that attacker.'),s('Weak Spot','When dealing damage to a creature whose INS die is smaller than Maximilian’s, damage ignores Resistances.'),s('Equipment','Adamantorso, bronze sword, runic shield.')],[sp('Awaken','20','One creature','Increase DEX, INS, MIG or WLP by one die size, max d12.','Scene')],{physical:'Resistant',bolt:'Vulnerable',fire:'Resistant',ice:'Resistant'}),

  m('maximilian-bastion','Maximilian, the Bastion',40,'Champion',2,'Humanoid',['arrogant','determined','desperate','proud'],{dex:10,ins:8,mig:8,wlp:10},280,180,11,14,8,[a('Conviction','DEX + INS +6','light','HR + 24 damage.')],[s('Elemental Charge','Spend 10 MP; next Conviction deals +5 damage and changes to a visible random type among air, bolt, fire, ice, earth, poison.'),s('Exploding Charge','Spend 10 MP; next Conviction gains multi (3).'),s('Piercing Charge','Spend 10 MP; next Conviction ignores Resistances.'),s('Raise the Banner','Once per conflict; while banner stands, Maximilian, Nike and Theo gain their listed bonuses; removing it requires a six-section Clock.'),s('Desperate Measures','First time entering Crisis, immediately use one Charge for free and benefit from Desperate Times.'),s('Desperate Times','After using a Charge while in Crisis, immediately make a free Conviction attack.'),s('Last Stand','First time reduced to 0 HP while banner stands, remain at 1 HP, immediately take one free action, then fall to 0 HP if conflict continues.'),s('Token of Conviction','Can spend 1 Ultima Point to prevent Conviction from being stolen/destroyed; immune to all status effects while equipped.'),s('Equipment','Adamantorso; Conviction mortar-shield.')],[],{physical:'Resistant',air:'Resistant',bolt:'Resistant',fire:'Vulnerable',ice:'Resistant'}),

  m('nike','Nike',40,'Soldier',1,'Humanoid',['determined','diligent','loyal','veteran'],{dex:10,ins:8,mig:10,wlp:8},140,70,6,15,13,[a('Twin Shields','MIG + MIG +7','physical','HR + 15 damage; multi (2).')],[s('Divide and Conquer','After a creature misses Nike with a melee attack, that creature suffers slow.'),s('Dual Shieldbearer','Uses the Core Rulebook Dual Shieldbearer rules.'),s('Protection','May swap places with an endangered creature as per Protect.'),s('Shield of the Empire','While Maximilian’s banner stands, reduce all damage taken by 5 before Affinities.'),s('Thundering Blow','When hit by a melee attack, may make a free Twin Shields attack against that creature; loses multi and HR counts as 0 for damage.'),s('Equipment','Runic plate; two runic shields.')],[],{physical:'Resistant',bolt:'Vulnerable',earth:'Resistant'}),

  m('theo','Theo',40,'Soldier',1,'Humanoid',['compassionate','elegant','loyal','well-read'],{dex:8,ins:10,mig:6,wlp:12},110,130,11,9,10,[a('Caduceus','WLP + WLP +4','physical','HR + 16 damage.')],[s('Sense of Belonging','While Maximilian’s banner stands, recover 10 MP at start of turns.'),s('Caduceus','Healing spells restore +5 HP; already included in Heal.'),s('Debt of Gratitude','When Maximilian first enters Crisis, if Theo has enough MP, immediately cast Heal on Maximilian only.'),s('Support','When sacrificing turn to help an ally, teamwork bonus becomes +4.'),s('Equipment','Caduceus; sage robe.')],[sp('Elemental Shroud','5 × T','Up to three creatures','Choose air, bolt, fire, ice, or earth; targets gain Resistance to that type.','Scene'),sp('Heal','10 × T','Up to three creatures','Each target recovers 65 HP.'),sp('Ventus','10 × T','Up to three creatures','INS + WLP +4; HR + 25 air damage; opportunity: flying targets are forced to land.')],{air:'Immune',ice:'Vulnerable'}),

  m('mimesis','Mimesis',60,'Champion',3,'Demon',['inevitable','mutable'],{dex:8,ins:10,mig:8,wlp:12},480,240,16,12,10,[a('Transcendental Spike','MIG + WLP +6','physical','HR + 20 damage; next time target takes damage, that source deals +20 damage.')],[s('Wheel of Fate','Embodies a selected Villain other than the one embodied last turn; after embodying all available Villains at least once, gains 1 Destiny up to 5.'),s('Apocrypha','Attacks gain multi equal to current Destiny; if already multi, increase it by Destiny.'),s('Echoes of Fate','Gains Traits, Affinities, basic attacks, spells and applicable equipment-derived effects of the embodied Villain, with extra damage for lower-level copied profiles.'),s('Final Clash','When targeting a creature bonded to the embodied Villain, gains Accuracy/Magic bonus equal to Destiny.'),s('Flying','Can fly.'),s('Red String Aegis','Reduces damage taken by current Destiny.')],[],{},['Tragedia — Phase 1.']),

  m('anagnorisis','Anagnorisis',60,'Champion',2,'Demon',['authoritarian','oppressive','tenacious','unfathomable'],{dex:8,ins:10,mig:8,wlp:12},320,240,13,12,10,[a('Interpolation','MIG + WLP +6','physical','HR + 20 damage; ignores all Affinities except Resistances; if it causes a PC to enter Crisis, fill 1 Predestination Clock section.')],[s('Death of the Author','Immune to poisoned and enraged.'),s('Dramatis Personae','Damage taken is reduced by the total strength of the attacker’s Bonds.'),s('Fourth Wall','Immune to all damage while the Dramatist’s Quill is not in Crisis.')],[],{physical:'Resistant',light:'Resistant'},['Tragedia — Phase 2.']),

  m('dramatists-quill','Dramatist’s Quill',60,'Soldier',1,'Elemental',['autonomous','ethereal','immutable','tenacious'],{dex:12,ins:12,mig:6,wlp:8},180,100,13,12,12,[a('Thus They Suffered a Grievous Wound...','INS + WLP +6','physical','HR + 20 damage.')],[s('As Ordained by Fate...','Commands a PC to perform a randomly determined harmful/beneficial action on their turn; obeying grants 1 Fabula Point and fills Predestination, refusing costs 20 HP and 20 MP.'),s('Exeunt','Spend 50 MP to immediately end all status effects and all other Scene-duration effects, including spells.'),s('Elemental','Immune to poisoned.'),s('In the Next Episode...','At 0 HP, if Predestination has 2+ filled sections, return with 90 HP and erase 2 sections; all PCs gain 2 Fabula Points.')],[],{air:'Resistant',bolt:'Resistant',dark:'Resistant',earth:'Resistant',fire:'Resistant',ice:'Resistant',light:'Immune',poison:'Immune'}),

  m('catharsis','Catharsis',60,'Champion',3,'Demon',['divine','dominating','imposing','punishing'],{dex:8,ins:12,mig:10,wlp:8},510,200,13,12,10,[a('Slow Epilogue','MIG + WLP +6','untyped','HR + 20 damage; multi (3); damage has no type and ignores Affinities.')],[s('Abyssal Agony','All other creatures suffer dazed, shaken, slow and weak; any PC may spend 1 Fabula Point to negate this action.'),s('Divine Frenzy','Reduces every enemy’s HP and MP to 1; any PC may spend 1 Fabula Point to negate this action.'),s('Bonds that Transcend Destiny','PCs deal extra damage equal to the total strength of their Bonds.'),s('Catharsis','First time entering Crisis, each PC gains 15 Fabula Points; all Resistances become Vulnerabilities and Slow Epilogue loses its +6 Accuracy bonus.'),s('Divine Tribute','When Catharsis damages a PC, that PC suffers extra damage equal to their current Fabula Points.')],[],{physical:'Resistant',air:'Resistant',bolt:'Resistant',dark:'Resistant',earth:'Resistant',fire:'Resistant',ice:'Resistant',light:'Resistant',poison:'Resistant'},['Tragedia — Phase 3.'])
]
