import type { Monster, Species } from './rules'

const normal = { physical:'Normal', air:'Normal', bolt:'Normal', dark:'Normal', earth:'Normal', fire:'Normal', ice:'Normal', light:'Normal', poison:'Normal' } as const
const speciesAffinity = (species:Species): Partial<Monster['affinities']> => {
  if (species === 'Construct') return { earth:'Resistant', poison:'Immune' }
  if (species === 'Elemental') return { poison:'Immune' }
  if (species === 'Undead') return { dark:'Immune', poison:'Immune', light:'Vulnerable' }
  return {}
}
const a=(name:string,formula:string,damageType:string,effect?:string)=>({name,formula,damageType,effect})
const s=(name:string,summary:string)=>({name,summary})
const sp=(name:string,mp:string,target:string,effect:string,duration='Instantaneous')=>({name,mp,target,duration,effect})
const m=(id:string,name:string,level:number,species:Species,traits:string[],attrs:Monster['attributes'],hp:number,mp:number,initiative:number,defense:number,magicDefense:number,attacks:Monster['attacks'],skills:Monster['skills']=[],spells:Monster['spells']=[],aff:Partial<Monster['affinities']>={}):Monster=>({
  id:`official-core-${id}`,name,source:'Official',level,rank:'Soldier',soldierEquivalent:1,species,traits,attributes:attrs,
  hp,crisis:Math.floor(hp/2),mp,initiative,defense,magicDefense,accuracyBonus:Math.floor(level/10),magicBonus:Math.floor(level/10),levelDamageBonus:level>=40?10:level>=20?5:0,turnsPerRound:1,skillBudget:0,
  affinities:{...normal,...speciesAffinity(species),...aff} as Monster['affinities'],attacks,skills,spells,notes:['Official profile — Fabula Ultima Core Rulebook Bestiary.'],combatStyle:'Mixed'
})

export const officialCoreBestiaryRemaining: Monster[] = [
  m('imp','Imp',5,'Demon',['cowardly','cunning','mischievous','tainted'],{dex:8,ins:8,mig:6,wlp:10},50,55,8,8,8,[a('Freezing Nails','DEX + WLP','ice','HR + 5 damage; targets Magic Defense.')],[],[sp('Enrage','10','One creature','Target suffers enraged and cannot Guard or Spell on its next turn.'),sp('Shell','10','Self','Gain Resistance to physical damage.','Scene')]),
  m('lightning-wheel','Lightning Wheel',10,'Demon',['bright','cackling','cruel','fast'],{dex:12,ins:6,mig:6,wlp:8},60,60,9,12,6,[a('Sharp Turn','DEX + MIG +1','physical','HR + 10 damage.')],[s('Quick','When filling or erasing an escape/pursuit Clock, affects two additional sections.')],[sp('Fulgur','10 × T','Up to three creatures','INS + WLP +1; each target suffers HR + 15 bolt damage; opportunity: dazed.')],{bolt:'Absorb',earth:'Vulnerable'}),
  m('shadow-howler','Shadow Howler',15,'Demon',['ghastly','large','silent','unearthly'],{dex:8,ins:6,mig:10,wlp:8},80,55,7,9,8,[a('Ghostbite','DEX + MIG +4','physical','HR + 10 damage; targets Magic Defense.')],[],[sp('Ember Breath','10','One creature','MIG + WLP +1; HR + 15 fire damage and weak.'),sp('Howls of Tragedy','5','One creature','MIG + WLP +1; target suffers shaken.')]),
  m('echidna','Echidna',20,'Demon',['clever','knowledgeable','slithering','unfathomable'],{dex:8,ins:10,mig:6,wlp:10},70,80,9,8,10,[a('Tangle of Vipers','DEX + INS +5','poison','HR + 15 damage.'),a('Cold Glare','DEX + WLP +5','ice','HR + 10 damage; target cannot use Objective on its next turn; targets Magic Defense.')],[s('Eloquent','Gains +3 to Opposed Checks during social occasions.')],[sp('Brain Melt','5 × T','Up to three creatures','INS + WLP +2; each target loses HR + 10 MP.')]),

  m('acorn-pixie','Acorn Pixie',5,'Elemental',['curious','glowing','kind','playful'],{dex:10,ins:6,mig:6,wlp:10},40,55,8,10,6,[a('Sharp Needle','DEX + DEX','physical','HR + 5 damage; +5 damage against slow targets.')],[s('Elemental','Immune to poisoned.'),s('Flying','Can fly; loses the benefit in Crisis or when struck by a Vulnerability.')],[sp('Entangle','5','One creature','INS + WLP; target suffers slow.'),sp('Heal','10 × T','Up to three creatures','Each target recovers 40 HP (50 at level 20+, 60 at level 40+).')]),
  m('chaos-shard','Chaos Shard',5,'Elemental',['alien','hungry','small','spreads darkness'],{dex:8,ins:10,mig:8,wlp:6},50,35,9,8,10,[a('Chaos Dart','DEX + INS','dark','HR + 5 damage; target suffers weak.')],[s('Elemental','Immune to poisoned.'),s('Empty Mind','Immune to dazed, enraged and shaken.')]),
  m('grenado','Grenado',10,'Elemental',['bright','excitable','scorching','unstable'],{dex:8,ins:6,mig:8,wlp:10},60,60,7,9,8,[a('Flame Belch','DEX + WLP +1','fire','HR + 10 damage; target loses fire Resistance until end of grenado’s next turn.')],[s('Detonation','At 0 HP, deals 10 fire damage to every other creature unless reduced to 0 HP by ice.'),s('Elemental','Immune to poisoned.')],[],{fire:'Absorb',earth:'Vulnerable',ice:'Vulnerable'}),
  m('static-ooze','Static Ooze',10,'Elemental',['hungry','slow','soft','static'],{dex:6,ins:6,mig:10,wlp:10},70,70,6,7,8,[a('Jelly Slam','DEX + MIG +1','physical','HR + 5 damage.')],[s('Elemental','Immune to poisoned.')],[sp('Static Wave','10','One creature','MIG + WLP +1; HR + 15 bolt damage and slow.')],{bolt:'Absorb',earth:'Vulnerable'}),
  m('nymph','Nymph',15,'Elemental',['fast','territorial','wary','wise'],{dex:8,ins:10,mig:6,wlp:8},70,55,9,8,10,[a('Seasonal Touch','DEX + INS +1','air','HR + 10 damage; inflicts dazed in spring, shaken in winter, slow in autumn, weak in summer.')],[s('Elemental','Immune to poisoned.')]),
  m('spikeflake','Spikeflake',15,'Elemental',['fear of heat','floating','ice-cold','spinning'],{dex:8,ins:10,mig:6,wlp:8},70,65,9,9,10,[a('Cold Bite','DEX + INS +1','ice','HR + 5 damage.')],[s('Elemental','Immune to poisoned.')],[sp('Frost Breath','10','One creature','INS + WLP +4; HR + 15 ice damage and weak.')],{ice:'Absorb',fire:'Vulnerable'}),
  m('cragboar','Cragboar',20,'Elemental',['destructive','irritable','massive','rocky'],{dex:8,ins:6,mig:12,wlp:8},110,60,7,8,8,[a('Rock Charge','DEX + MIG +2','physical','HR + 15 damage; multi (2); loses 20 HP if it misses any target.'),a('Rock Tusk','MIG + MIG +2','physical','HR + 10 damage.')],[s('Angry Snort','Next turn must use Rock Charge; targets hit also suffer shaken.'),s('Elemental','Immune to poisoned.')],[sp('Rock Barrage','10','One creature','MIG + WLP +2; HR + 20 earth damage and dazed.'),sp('Terra','10 × T','Up to three creatures','MIG + WLP +2; HR + 20 earth damage; cannot target airborne creatures; opportunity: one fewer action next turn.')]),

  m('brigand','Brigand',5,'Humanoid',['boastful','irritable','proud','strong'],{dex:6,ins:8,mig:10,wlp:8},60,45,10,11,9,[a("Brigand's Axe",'MIG + MIG','physical','HR + 10 damage.')],[s('Bad Temper','While in Crisis, immune to all status effects.'),s('Equipment','Broadaxe, bronze shield, travel garb.')]),
  m('guard','Guard',5,'Humanoid',['brave','disciplined','loyal','trained'],{dex:8,ins:8,mig:8,wlp:8},60,45,5,11,8,[a('Heavy Spear','DEX + MIG','physical','HR + 12 damage.'),a('Crossbow','DEX + INS','physical','HR + 8 damage.')],[s('Defensive Formation','Gains +1 Defense and Magic Defense while another Guard is in the conflict.'),s('Protect','May take another character’s place when they are in danger.'),s('Equipment','Heavy spear, crossbow, bronze plate.')]),
  m('kobold-scout','Kobold Scout',5,'Humanoid',['fast','hairy','perceptive','small'],{dex:10,ins:8,mig:6,wlp:8},40,45,8,11,9,[a('Steel Dagger','DEX + INS +1','physical','HR + 4 damage; +5 damage to targets suffering a status effect.'),a('Stone','DEX + MIG','physical','HR + 5 damage and dazed.')],[s('Equipment','Steel dagger, travel garb.')]),
  m('kobold-witch','Kobold Witch',5,'Humanoid',['cryptic','hairy','small','wise'],{dex:8,ins:8,mig:6,wlp:10},50,55,6,9,10,[a('Oaken Staff','WLP + WLP','physical','HR + 6 damage.')],[s('Equipment','Staff, sage robe.')],[sp('Awaken','20','One creature','Choose DEX, INS, MIG or WLP; target treats it as one die size higher, max d12.','Scene'),sp('Bad Breath','5','One creature','INS + WLP; HR + 10 poison damage.')]),
  m('hivekin','Hivekin',10,'Humanoid',['buzzing','industrious','lover of beauty','secretive'],{dex:10,ins:8,mig:8,wlp:6},70,50,11,11,10,[a('Hiveblade','DEX + INS +5','physical','HR + 10 damage.')],[s('Flying','Can fly; loses the benefit in Crisis or when struck by a Vulnerability.'),s('Equipment','Katana, sage robe.')],[sp('Bee Dance','20','One creature','Target immediately performs a free weapon/basic attack.')]),
  m('mercenary','Mercenary',10,'Humanoid',['competent','grim','jaded','ruthless'],{dex:8,ins:8,mig:8,wlp:8},60,50,5,11,9,[a('Bronze Sword','DEX + MIG +5','physical','HR + 11 damage.'),a('Pistol','DEX + INS +4','physical','HR + 8 damage.')],[s('Charged Attack','Next attack gains multi (2) and ignores Resistances.'),s('Equipment','Bronze sword, pistol, runic plate.')]),
  m('sniper','Sniper',15,'Humanoid',['accurate','disciplined','furtive','observant'],{dex:10,ins:10,mig:6,wlp:6},60,45,13,11,11,[a('Dagger','DEX + INS +5','physical','HR + 4 damage.'),a('Sniper Bow','DEX + DEX +4','physical','HR + 8 damage; target suffers dazed or slow.')],[s('Equipment','Shortbow, steel dagger, travel garb.')]),
  m('battlemage','Battlemage',20,'Humanoid',['ambitious','cunning','disciplined','knowledgeable'],{dex:8,ins:8,mig:8,wlp:10},80,90,9,11,9,[a('Decorated Staff','WLP + WLP +2','physical','HR + 11 damage.')],[s('Equipment','Staff, runic plate.')],[sp('Fulgur','10 × T','Up to three creatures','INS + WLP +5; each target suffers HR + 20 bolt damage; opportunity: dazed.'),sp('Heal','10 × T','Up to three creatures','Each target recovers 40 HP (50 at level 20+, 60 at level 40+).')]),

  m('cait-sith','Cait Sith',5,'Monster',['curious','playful','smart','tiny'],{dex:8,ins:8,mig:6,wlp:10},40,65,12,9,10,[a('Scratch','DEX + MIG','physical','HR + 5 damage.'),a('Ghostfire','INS + WLP','fire','HR + 5 fire or ice damage; targets Magic Defense.')],[],[sp('Heat Control','15','One creature','Choose fire or ice; target suffers 5 extra damage from that type.','Scene')]),
  m('dreadmoth','Dreadmoth',5,'Monster',['creepy','flying','hairy','smelly'],{dex:10,ins:6,mig:8,wlp:8},60,55,8,10,6,[a('Moth Bite','DEX + MIG','physical','HR + 10 damage.')],[s('Flying','Can fly; loses the benefit in Crisis or when struck by a Vulnerability.')],[sp('Poison Cloud','10 × T','Up to three creatures','MIG + WLP; each target suffers poisoned.')]),
  m('mellow-ooze','Mellow Ooze',5,'Monster',['glowing','soft','terribly cute','warm'],{dex:8,ins:6,mig:10,wlp:8},60,55,7,9,8,[a('Mellow Lick','DEX + MIG','physical','HR + 10 damage.'),a('Mellow Woosh','DEX + INS','air','HR + 5 damage.')],[],[sp('Mellow Dance','10','One creature','Target recovers 30 HP (40 at level 20+, 50 at level 40+, 60 at level 60+) and one status effect.')]),
  m('drake','Drake',10,'Monster',['heavy','hungry','lazy','scaly'],{dex:8,ins:8,mig:10,wlp:6},70,50,8,10,9,[a('Bite','MIG + MIG +4','physical','HR + 10 damage.')],[],[sp('Dragonbreath','10','One creature','MIG + WLP +4; HR + 15 fire damage and shaken.')]),
  m('hexeye','Hexeye',10,'Monster',['cunning','hypnotic','silent','winged'],{dex:10,ins:6,mig:8,wlp:8},60,60,12,10,6,[a('Claw','DEX + MIG +1','physical','HR + 10 damage.'),a('Chaos Glare','DEX + WLP +1','dark','HR + 5 damage; if target is dazed, one fewer action next turn.')],[s('Flying','Can fly; loses the benefit in Crisis or when struck by a Vulnerability.')],[sp('Doomgaze','10','One creature','MIG + WLP +4; target suffers dazed and weak.')]),
  m('hydrozoa','Hydrozoa',10,'Monster',['floating','glowing','silent','transparent'],{dex:8,ins:8,mig:10,wlp:6},70,40,8,9,10,[a('Acid Touch','MIG + MIG +1','poison','HR + 10 damage; target loses 1 IP.'),a('Stinging Tentacle','DEX + MIG +1','bolt','HR + 5 damage and enraged.')],[s('Flying','Can fly; loses the benefit in Crisis or when struck by a Vulnerability.')]),
  m('cockatrice','Cockatrice',15,'Monster',['agile','small','smelly','unpredictable'],{dex:8,ins:10,mig:8,wlp:6},70,45,9,9,10,[a('Petrifying Peck','DEX + INS +4','physical','No damage; targets Magic Defense; inflicts slow; if already slow, DL 10 MIG + WLP or petrified.'),a('Toxic Peck','DEX + MIG +4','poison','HR + 10 damage.')]),
  m('mimic','Mimic',15,'Monster',['cunning','formless','ravenous','stealthy'],{dex:10,ins:8,mig:8,wlp:6},70,45,9,9,10,[a('Mimic Claw','DEX + MIG +4','physical','HR + 5 damage; double damage if it ambushed an unsuspecting target.'),a('Item Steal','DEX + INS +4','physical','HR + 5 damage; target loses 2 IP.')],[s('Shapeshifting','While transformed, identical to the copied object except for one disturbing or unusual detail.')]),

  m('alraune','Alraune',5,'Plant',['creepy','fast','malevolent','tiny'],{dex:10,ins:8,mig:6,wlp:8},50,45,9,10,8,[a('Vine Slap','DEX + MIG','physical','HR + 5 damage; +5 against shaken targets.'),a('Alraune Scream','WLP + WLP','physical','No damage; target suffers shaken; targets Magic Defense; requires hearing.')],[s('Plant','Immune to dazed, enraged and shaken.')]),
  m('cursed-pumpkin','Cursed Pumpkin',5,'Plant',['furious','rotting','small','smelly'],{dex:8,ins:8,mig:8,wlp:8},50,55,8,9,10,[a('Rotten Bite','DEX + MIG +3','poison','HR + 5 damage.')],[s('Plant','Immune to dazed, enraged and shaken.')],[sp('Pumpkin Puke','10','One creature','Target suffers 5 extra damage from poison sources.','Scene')]),
  m('pestervine','Pestervine',10,'Plant',['aggressive','cursed','quick','thorny'],{dex:10,ins:8,mig:8,wlp:6},60,40,9,10,8,[a('Corrupting Vines','DEX + DEX +1','physical','HR + 5 damage and weak; while weak, target cannot Guard.'),a('Dark Bite','DEX + MIG +1','dark','HR + 10 damage.')],[s('Plant','Immune to dazed, enraged and shaken.')]),
  m('shroomkin','Shroomkin',10,'Plant',['eyeless','mud-loving','peaceful','slow'],{dex:6,ins:8,mig:10,wlp:8},70,60,7,10,9,[a('Shroom Slap','DEX + MIG +1','physical','HR + 5 damage.')],[s('Plant','Immune to dazed, enraged and shaken.'),s('Wide Cap','When Guarding, may grant another creature Resistance to all damage until start of its next turn.')],[sp('Spore Belch','10','One creature','MIG + WLP +1; HR + 15 poison damage and dazed.')]),
  m('cactroll','Cactroll',15,'Plant',['creepy','hulking','territorial','water sensitive'],{dex:8,ins:6,mig:12,wlp:6},90,55,7,8,6,[a('Piercing Hug','MIG + MIG +1','physical','HR + 10 damage.'),a('Thorn Barrage','DEX + MIG +1','physical','HR + 5 damage.')],[s('Cactroll Juice','Heals slow and weak, then performs Thorn Barrage as a free attack.'),s('Plant','Immune to dazed, enraged and shaken.')],[sp('Moisture Drain','10','One creature','MIG + WLP +1; HR + 15 poison damage; recovers HP equal to half target HP loss.')]),
  m('dragontrap','Dragontrap',20,'Plant',['colossal','hungry','patient','rooted in place'],{dex:8,ins:8,mig:10,wlp:8},90,60,8,8,8,[a('Dragoneater','MIG + MIG +5','physical','HR + 10 damage; weak targets are swallowed and suffer 20 physical damage at start of each dragontrap turn; four-section Objective Clock to escape.'),a('Lashing Vines','DEX + MIG +5','air','HR + 15 damage and weak.')],[s('Plant','Immune to dazed, enraged and shaken.')],[sp('Numbing Gas','10 × T','Up to three creatures','MIG + WLP +2; each target loses half current MP.'),sp('Pre-digestion','10','One creature','Target suffers 10 extra physical damage from all sources.','Scene')]),

  m('dread-urn','Dread Urn',5,'Undead',['cackling','fragile','floating','tiny'],{dex:10,ins:6,mig:6,wlp:10},50,55,8,9,10,[a('Urn Poke','DEX + MIG','physical','HR + 5 damage.'),a('Chaos Cackle','DEX + MIG','dark','HR + 5 damage and shaken; targets Magic Defense.')],[s('Undead','Immune to poisoned; HP recovery may harm it.')]),
  m('zombie','Zombie',5,'Undead',['creepy','mindless','rotting','slow'],{dex:6,ins:6,mig:12,wlp:8},70,45,6,10,9,[a('Ravenous Bite','DEX + MIG','dark','HR + 5 damage and weak.'),a('Zombie Rake','MIG + MIG','physical','HR + 5 damage.')],[s('Empty Mind','Immune to dazed, enraged and shaken.'),s('Undead','Immune to poisoned; HP recovery may harm it.')]),
  m('skeletal-mage','Skeletal Mage',10,'Undead',['ambitious','clever','knowledgeable','ruthless'],{dex:6,ins:8,mig:8,wlp:10},60,70,5,10,12,[a('Staff','WLP + WLP +1','physical','HR + 6 damage; recovers 5 MP.')],[s('Undead','Immune to poisoned; HP recovery may harm it.'),s('Equipment','Staff, sage robe.')],[sp('Umbra','10 × T','Up to three creatures','INS + WLP +1; each target suffers HR + 15 dark damage; opportunity: shaken.')]),
  m('skeletal-soldier','Skeletal Soldier',10,'Undead',['cruel','mindless','murderous','silent'],{dex:8,ins:8,mig:10,wlp:6},70,40,6,12,8,[a('Bronze Sword','DEX + MIG +5','physical','HR + 11 damage.')],[s('Empty Mind','Immune to dazed, enraged and shaken.'),s('Undead','Immune to poisoned; HP recovery may harm it.'),s('Equipment','Bronze sword, bronze shield, brigandine.')]),
  m('bone-howler','Bone Howler',15,'Undead',['eternally hungry','fast','resilient','vicious'],{dex:10,ins:6,mig:10,wlp:6},80,55,8,10,6,[a('Serrated Maw','DEX + MIG +1','physical','HR + 10 damage and slow.')],[s('Undead','Immune to poisoned; HP recovery may harm it.')],[sp('Rot Breath','10','One creature','MIG + WLP +1; HR + 15 dark damage and weak.')]),
  m('ghoul','Ghoul',15,'Undead',['aggressive','large','powerful','terrifying'],{dex:8,ins:6,mig:12,wlp:6},90,45,7,8,6,[a('Furious Claws','MIG + MIG +1','physical','HR + 10 damage; multi (2).'),a('Poison Breath','DEX + MIG +1','poison','HR + 5 damage and poisoned.')],[s('Undead','Immune to poisoned; HP recovery may harm it.')]),
  m('mummy','Mummy',20,'Undead',['cursed','eternally loyal','flammable','silent'],{dex:6,ins:8,mig:10,wlp:10},90,70,7,8,10,[a('Grave Claw','MIG + WLP +5','earth','HR + 10 damage; inflicts slow; if already slow, target becomes Vulnerable to all damage until slow ends.')],[s('Ancient Curse','At 0 HP, all living creatures on the scene suffer shaken and weak.'),s('Empty Mind','Immune to dazed, enraged and shaken.'),s('Undead','Immune to poisoned; HP recovery may harm it.')]),
  m('shackled-soul','Shackled Soul',20,'Undead',['anguished','cursed','ethereal','vengeful'],{dex:12,ins:8,mig:6,wlp:8},70,70,10,12,8,[a('Fury Claw','DEX + WLP +5','dark','HR + 10 damage and enraged.')],[s('Undead','Immune to poisoned; HP recovery may harm it.')],[sp('Ghastly Wail','10','One creature','INS + WLP +5; HR + 20 ice damage and shaken.')]),
]