import { GeneratedItem } from './items'

type OfficialItem = GeneratedItem & { origin?: string }

const armor = (id:string,name:string,cost:number,martial:boolean,defense:string,magicDefense:string,initiative:number,effect:string,origin:string): OfficialItem => ({
  id, name, type:'Armor', source:'Official', cost, martial, defense, magicDefense, initiative, effect, origin, breakdown:[origin]
})
const shield = (id:string,name:string,cost:number,martial:boolean,defense:string,magicDefense:string,effect:string,origin:string): OfficialItem => ({
  id, name, type:'Shield', source:'Official', cost, martial, defense, magicDefense, initiative:0, effect, origin, breakdown:[origin]
})
const accessory = (id:string,name:string,cost:number,effect:string,origin:string,category='Accessory'): OfficialItem => ({
  id, name, type:'Accessory', source:'Official', cost, martial:false, category, effect, origin, breakdown:[origin]
})
const artifact = (id:string,name:string,effect:string,origin:string): OfficialItem => accessory(id,name,0,effect,origin,'Artifact')
const moduleItem = (id:string,name:string,cost:number,category:string,accuracy:string|undefined,accuracyBonus:number,damage:number|undefined,damageType:any,effect:string,origin:string,range:'Melee'|'Ranged'|undefined): OfficialItem => ({
  id, name, type:'Weapon', source:'Official', cost, martial:false, category:`Weapon Module · ${category}`, accuracy, accuracyBonus, damage, damageType, range, effect, origin, breakdown:[origin,'Techno Fantasy weapon module']
})

export const officialOtherItems: OfficialItem[] = [
  // Core Rulebook basic armor and shields
  armor('official-core-silk-shirt','Silk Shirt',100,false,'DEX','INS +2',-1,'No Quality.','Core Rulebook · Basic Armor'),
  armor('official-core-travel-garb','Travel Garb',100,false,'DEX +1','INS +1',-1,'No Quality.','Core Rulebook · Basic Armor'),
  armor('official-core-combat-tunic','Combat Tunic',150,false,'DEX +1','INS +1',0,'No Quality.','Core Rulebook · Basic Armor'),
  armor('official-core-sage-robe','Sage Robe',200,false,'DEX +1','INS +2',-2,'No Quality.','Core Rulebook · Basic Armor'),
  armor('official-core-brigandine','Brigandine',150,true,'10','INS',-2,'No Quality.','Core Rulebook · Basic Armor'),
  armor('official-core-bronze-plate','Bronze Plate',200,true,'11','INS',-3,'No Quality.','Core Rulebook · Basic Armor'),
  armor('official-core-runic-plate','Runic Plate',250,true,'11','INS +1',-3,'No Quality.','Core Rulebook · Basic Armor'),
  armor('official-core-steel-plate','Steel Plate',300,true,'12','INS',-4,'No Quality.','Core Rulebook · Basic Armor'),
  shield('official-core-bronze-shield','Bronze Shield',100,false,'+2','—','No Quality.','Core Rulebook · Basic Shield'),
  shield('official-core-runic-shield','Runic Shield',150,true,'+2','+2','No Quality.','Core Rulebook · Basic Shield'),

  // Core Rulebook rare armor
  armor('official-core-slimy-jacket','Slimy Jacket',600,false,'DEX +1','INS +1',-1,'You are immune to poisoned.','Core Rulebook · Rare Armor'),
  armor('official-core-fox-garb','Fox Garb',650,false,'DEX +1','INS +1',0,'You are immune to slow.','Core Rulebook · Rare Armor'),
  armor('official-core-shadow-tunic','Shadow Tunic',650,false,'DEX +1','INS +1',4,'You gain a +4 bonus to Initiative (already included).','Core Rulebook · Rare Armor'),
  armor('official-core-desperado-coat','Desperado Coat',750,false,'DEX +1','INS +1',-1,'The MP cost of Barrage is halved.','Core Rulebook · Rare Armor'),
  armor('official-core-butler-uniform','Butler Uniform',800,false,'DEX +1','INS +2',-2,'Potions or magispheres made with your Inventory Points restore 5 extra HP.','Core Rulebook · Rare Armor'),
  armor('official-core-maid-uniform','Maid Uniform',800,false,'DEX +1','INS +2',-2,'Potions or magispheres made with your Inventory Points restore 5 extra MP.','Core Rulebook · Rare Armor'),
  armor('official-core-bandit-jacket','Bandit Jacket',900,false,'DEX +1','INS +1',-1,'You gain +1 to Accuracy Checks with daggers.','Core Rulebook · Rare Armor'),
  armor('official-core-crystal-plate','Crystal Plate',900,true,'11','INS',-3,'You have Resistance to dark damage.','Core Rulebook · Rare Armor'),
  armor('official-core-valkyrie-wings','Valkyrie Wings',900,true,'11','INS +1',-3,'The MP cost of Soaring Strike is halved.','Core Rulebook · Rare Armor'),
  armor('official-core-armor-of-heroes','Armor of Heroes',1000,true,'12','INS',-4,'Critical successes on hostile Accuracy or Magic Checks that include you generate no opportunities.','Core Rulebook · Rare Armor'),
  armor('official-core-black-belt','Black Belt',1000,false,'DEX','INS',0,'Your attacks with brawling weapons deal 5 extra damage.','Core Rulebook · Rare Armor'),
  armor('official-core-meditation-robe','Meditation Robe',1000,false,'DEX +1','INS +2',-2,'Whenever you recover MP, recover 5 extra MP.','Core Rulebook · Rare Armor'),
  armor('official-core-archmage-robe','Archmage Robe',1200,false,'DEX +1','INS +2',-2,'You gain +1 to Magic Checks.','Core Rulebook · Rare Armor'),
  armor('official-core-automaton-suit','Automaton Suit',1250,true,'11','INS +1',-3,'Immune to earth and poison damage; Vulnerable to bolt damage.','Core Rulebook · Rare Armor'),
  armor('official-core-adamantorso','Adamantorso',1300,true,'12','INS',-4,'You have Resistance to physical damage.','Core Rulebook · Rare Armor'),
  armor('official-core-ardent-yoroi','Ardent Yoroi',1300,true,'12','INS',-4,'You gain +1 to Accuracy Checks.','Core Rulebook · Rare Armor'),
  armor('official-core-demongrin','Demongrin',1500,true,'12','INS',-4,'After a creature hits you with a melee attack, deal 5 fire damage to it.','Core Rulebook · Rare Armor'),
  armor('official-core-bio-plate','Bio Plate',1700,true,'11','INS',-3,'You have Immunity to poison damage.','Core Rulebook · Rare Armor'),
  armor('official-core-white-tunic','White Tunic',1700,false,'DEX +1','INS +2',-2,'Spells you cast that restore HP restore 5 extra HP.','Core Rulebook · Rare Armor'),
  armor('official-core-granny-vest','Granny Vest',2000,false,'DEX','INS +2',-1,'Treat Willpower as one die size higher, up to d12.','Core Rulebook · Rare Armor'),
  armor('official-core-black-tunic','Black Tunic',2200,false,'DEX +1','INS +2',-2,'Spells you cast deal 5 extra damage.','Core Rulebook · Rare Armor'),
  armor('official-core-red-tunic','Red Tunic',2500,false,'DEX','INS +2',-1,'You count as having an arcane weapon equipped for Skills that require one.','Core Rulebook · Rare Armor'),

  // Core Rulebook rare shields
  shield('official-core-aegis-fulgur','Aegis, Fulgur',800,false,'+2','—','Resistance to bolt damage.','Core Rulebook · Rare Shield'),
  shield('official-core-aegis-gelum','Aegis, Gelum',800,false,'+2','—','Resistance to ice damage.','Core Rulebook · Rare Shield'),
  shield('official-core-aegis-gorgonis','Aegis, Gorgonis',800,false,'+2','—','Resistance to poison damage.','Core Rulebook · Rare Shield'),
  shield('official-core-aegis-ignis','Aegis, Ignis',800,false,'+2','—','Resistance to fire damage.','Core Rulebook · Rare Shield'),
  shield('official-core-aegis-lux','Aegis, Lux',800,false,'+2','—','Resistance to light damage.','Core Rulebook · Rare Shield'),
  shield('official-core-aegis-terra','Aegis, Terra',800,false,'+2','—','Resistance to earth damage.','Core Rulebook · Rare Shield'),
  shield('official-core-aegis-umbra','Aegis, Umbra',800,false,'+2','—','Resistance to dark damage.','Core Rulebook · Rare Shield'),
  shield('official-core-aegis-ventus','Aegis, Ventus',800,false,'+2','—','Resistance to air damage.','Core Rulebook · Rare Shield'),
  shield('official-core-demonshield','Demonshield',950,true,'+2','+2','After a creature damages you while you are in Crisis, you may have it suffer shaken.','Core Rulebook · Rare Shield'),
  shield('official-core-shield-of-spring','Shield of Spring',1150,true,'+2','+2','Whenever you recover HP, recover 5 extra HP.','Core Rulebook · Rare Shield'),
  shield('official-core-seraph-shield','Seraph Shield',2050,true,'+2','+2','While in Crisis, you are immune to all status effects.','Core Rulebook · Rare Shield'),
  shield('official-core-adamantower','Adamantower',2500,true,'+3','+3','Grants an additional +1 Defense and Magic Defense (already included).','Core Rulebook · Rare Shield'),

  // Core Rulebook accessories
  accessory('official-core-explorers-belt',"Explorer's Belt",500,'Gain +4 Initiative.','Core Rulebook · Accessory'),
  accessory('official-core-gloves-elegant','Gloves, Elegant',500,'Immune to dazed.','Core Rulebook · Accessory'),
  accessory('official-core-gloves-rough','Gloves, Rough',500,'Immune to weak.','Core Rulebook · Accessory'),
  accessory('official-core-gloves-silky','Gloves, Silky',500,'Immune to slow.','Core Rulebook · Accessory'),
  accessory('official-core-gloves-warm','Gloves, Warm',500,'Immune to shaken.','Core Rulebook · Accessory'),
  accessory('official-core-rookies-boots',"Rookie's Boots",600,'On a fumble, if below 10 XP, gain 1 XP.','Core Rulebook · Accessory'),
  accessory('official-core-hannya-mask',"Han'nya Mask",700,'Damage you deal to shaken creatures ignores Resistances.','Core Rulebook · Accessory'),
  accessory('official-core-pendant-amber','Pendant, Amber',700,'Resistance to earth damage.','Core Rulebook · Accessory'),
  accessory('official-core-pendant-amethyst','Pendant, Amethyst',700,'Resistance to dark damage.','Core Rulebook · Accessory'),
  accessory('official-core-pendant-diamond','Pendant, Diamond',700,'Resistance to light damage.','Core Rulebook · Accessory'),
  accessory('official-core-pendant-emerald','Pendant, Emerald',700,'Resistance to poison damage.','Core Rulebook · Accessory'),
  accessory('official-core-pendant-opal','Pendant, Opal',700,'Resistance to air damage.','Core Rulebook · Accessory'),
  accessory('official-core-pendant-ruby','Pendant, Ruby',700,'Resistance to fire damage.','Core Rulebook · Accessory'),
  accessory('official-core-pendant-sapphire','Pendant, Sapphire',700,'Resistance to ice damage.','Core Rulebook · Accessory'),
  accessory('official-core-pendant-topaz','Pendant, Topaz',700,'Resistance to bolt damage.','Core Rulebook · Accessory'),
  accessory('official-core-ring-of-sorcery','Ring of Sorcery',800,'Gain +1 Magic Defense.','Core Rulebook · Accessory'),
  accessory('official-core-wanderers-boots',"Wanderer's Boots",900,'When the group makes a discovery while traveling, gain 1 Fabula Point.','Core Rulebook · Accessory'),
  accessory('official-core-crested-helm','Crested Helm',1000,'Gain +1 to Accuracy Checks.','Core Rulebook · Accessory'),
  accessory('official-core-gloves-crimson','Gloves, Crimson',1000,'When attacking with multi, gain +2 to the Accuracy Check.','Core Rulebook · Accessory'),
  accessory('official-core-pointy-yellow-hat','Pointy Yellow Hat',1000,'Gain +1 to Magic Checks.','Core Rulebook · Accessory'),
  accessory('official-core-ring-of-the-lion','Ring of the Lion',1500,'Gain +2 to Opposed Checks relying on Willpower.','Core Rulebook · Accessory'),
  accessory('official-core-ring-of-the-owl','Ring of the Owl',1500,'Gain +2 to Opposed Checks relying on Insight.','Core Rulebook · Accessory'),
  accessory('official-core-ring-of-the-pupil','Ring of the Pupil',1500,'With at least two Bonds of admiration, gain +1 Defense and Magic Defense.','Core Rulebook · Accessory'),
  accessory('official-core-ring-of-tales','Ring of Tales',1500,'On a critical success, you may spend the opportunity to gain 1 Fabula Point.','Core Rulebook · Accessory'),
  accessory('official-core-gloves-multigroa','Gloves, Multigroa Skin',2000,'Immune to all status effects.','Core Rulebook · Accessory'),
  accessory('official-core-ring-of-onions','Ring of Onions',2000,'Increase maximum HP and MP by 2 for each different Class you have.','Core Rulebook · Accessory'),
  accessory('official-core-ring-of-frost','Ring of Frost',2500,'Absorb ice damage; Vulnerable to fire damage.','Core Rulebook · Accessory'),
  accessory('official-core-ring-of-magma','Ring of Magma',2500,'Absorb fire damage; Vulnerable to ice damage.','Core Rulebook · Accessory'),
  accessory('official-core-ring-of-the-egg','Ring of the Egg',3000,'When reduced to 0 HP, you may remain at exactly 1 HP; the ring then breaks and costs 2000 zenit to repair.','Core Rulebook · Accessory'),

  // Core inventory items
  accessory('official-core-elixir','Elixir',0,'Inventory item · IP Cost 3 · One creature recovers 50 MP.','Core Rulebook · Inventory','Inventory Item'),
  accessory('official-core-remedy','Remedy',0,'Inventory item · IP Cost 3 · One creature recovers 50 HP.','Core Rulebook · Inventory','Inventory Item'),
  accessory('official-core-tonic','Tonic',0,'Inventory item · IP Cost 2 · One creature recovers from one status effect.','Core Rulebook · Inventory','Inventory Item'),
  accessory('official-core-elemental-shard','Elemental Shard',0,'Inventory item · IP Cost 2 · One creature suffers 10 air, bolt, earth, fire, or ice damage.','Core Rulebook · Inventory','Inventory Item'),
  accessory('official-core-magic-tent','Magic Tent',0,'Inventory item · IP Cost 4 · Allows the entire group to rest in the wilderness.','Core Rulebook · Inventory','Inventory Item'),

  // High Fantasy armor, shields, accessories
  armor('official-hf-dancing-dress','Dancing Dress',1000,false,'DEX','INS +2',-1,'After a dance lasting until the start of your next turn, you may heal one status effect.','High Fantasy Atlas · Rare Armor'),
  armor('official-hf-elemental-robe','Elemental Robe',1800,false,'DEX +1','INS +2',-2,'While in Crisis, spells dealing air, fire, bolt, ice, or earth deal 5 extra damage.','High Fantasy Atlas · Rare Armor'),
  armor('official-hf-orichalcum','Orichalcum',2500,true,'12','INS',-4,'Increase maximum HP by 10. This armor cannot be destroyed.','High Fantasy Atlas · Rare Armor'),
  shield('official-hf-bag-shield','Bag Shield',1000,false,'+2','—','When a Skill restores Inventory Points, recover 1 additional IP.','High Fantasy Atlas · Rare Shield'),
  shield('official-hf-drumshield','Drumshield',1700,false,'+2','—','If you have Resonance, treat its Skill Level as 2 higher, to a maximum of 5.','High Fantasy Atlas · Rare Shield'),
  shield('official-hf-argus','Argus',2000,true,'+2','+2',"King's Castle and Bishop's Edict may exclude one visible creature.",'High Fantasy Atlas · Rare Shield'),
  shield('official-hf-shield-of-blades','Shield of Blades',2000,true,'+2','+2','Multi attacks with heavy, spear, or sword weapons deal 5 extra damage.','High Fantasy Atlas · Rare Shield'),
  shield('official-hf-parry-shield','Parry Shield',2500,true,'+2','+2','Counterattack also triggers when an enemy Accuracy Check result is odd.','High Fantasy Atlas · Rare Shield'),
  accessory('official-hf-ring-of-denial','Ring of Denial',600,'Dispel becomes 10 × T MP and can target up to three creatures.','High Fantasy Atlas · Accessory'),
  accessory('official-hf-ring-of-occultist','Ring of the Occultist',600,'Spells targeting up to three creatures can instead target up to four, paying MP for the fourth.','High Fantasy Atlas · Accessory'),
  accessory('official-hf-ivory-ring','Ivory Ring',700,'You may take HP loss suffered by your Faithful Companion instead.','High Fantasy Atlas · Accessory'),
  accessory('official-hf-magic-palette','Magic Palette',700,'Damage you deal to a creature bearing one of your symbols ignores Resistance.','High Fantasy Atlas · Accessory'),
  accessory('official-hf-tacticians-diadem',"Tactician's Diadem",800,'An ally acting immediately after you in the round recovers 5 MP at the start of that turn.','High Fantasy Atlas · Accessory'),
  accessory('official-hf-alchemists-bag',"Alchemist's Bag",1000,'When creating a potion with Gadgets (Alchemy), roll an additional d20.','High Fantasy Atlas · Accessory'),
  accessory('official-hf-sorcerers-pendant',"Sorcerer's Pendant",1200,"Cheap Shot's extra damage can apply to single-target offensive spells against status-afflicted targets.",'High Fantasy Atlas · Accessory'),
  accessory('official-hf-dancing-ribbon','Dancing Ribbon',2000,'Increase Dexterity by one die size, up to d12.','High Fantasy Atlas · Accessory'),

  // Natural Fantasy armor, shields, accessories
  armor('official-nf-woolly-cuirass','Woolly Cuirass',800,true,'11','INS',-3,'While not in Crisis, gain Resistance to ice damage and immunity to weak.','Natural Fantasy Atlas · Rare Armor'),
  armor('official-nf-engineer-jacket','Engineer Jacket',1000,false,'DEX +1','INS +1',-1,'When using an elemental shard, you may deal its damage to up to three creatures; damaging with a shard also deals 5 extra damage.','Natural Fantasy Atlas · Rare Armor'),
  armor('official-nf-noble-dress','Noble Dress',1600,false,'DEX +1','INS +1',0,'When an ally you can see causes you to recover HP while you are in Crisis, recover 5 MP.','Natural Fantasy Atlas · Rare Armor'),
  armor('official-nf-apothecary-robes','Apothecary Robes',1800,false,'DEX +1','INS +2',-2,'When using the Potion Rain Skill, the core restoring effect is not halved.','Natural Fantasy Atlas · Rare Armor'),
  armor('official-nf-fairy-tunic','Fairy Tunic',2000,false,'DEX +1','INS +2',-2,'While affected by one or more Scene-duration spells, gain +2 Magic Defense.','Natural Fantasy Atlas · Rare Armor'),
  shield('official-nf-plate-manica','Plate Manica',800,false,'+2','—','While you do not have a martial armor or another shield equipped, you may apply Dodge.','Natural Fantasy Atlas · Rare Shield'),
  shield('official-nf-lid-shield','Lid Shield',1500,true,'+2','+2','When you deal damage with a delicacy, deal 5 extra damage.','Natural Fantasy Atlas · Rare Shield'),
  shield('official-nf-lily-vambrace','Lily Vambrace',2000,true,'+2','+2','Battle Gardening may be used while carrying a magiseed with the Graft Skill.','Natural Fantasy Atlas · Rare Shield'),
  accessory('official-nf-watering-can','Watering Can',500,'When performing a water invocation, you may fill 1 section of the Growth Clock of a visible PC.','Natural Fantasy Atlas · Accessory'),
  accessory('official-nf-spicy-powder','Spicy Powder',600,'When dealing damage with a delicacy or potion, you may change its type to fire and increase the damage by the Expiration Date die.','Natural Fantasy Atlas · Accessory'),
  accessory('official-nf-dandelion-obi','Dandelion Obi',700,'When performing an air invocation, you may recover from one status effect.','Natural Fantasy Atlas · Accessory'),
  accessory('official-nf-clockwork-heart','Clockwork Heart',800,'Gain Resistance to bolt and fire. If you enter Crisis, its effect ceases until your next rest.','Natural Fantasy Atlas · Accessory'),
  accessory('official-nf-needlefrog-mantle','Needlefrog Mantle',900,'After dealing poison damage to one or more creatures, each target that loses HP this way cannot recover HP until the start of your next turn.','Natural Fantasy Atlas · Accessory'),
  accessory('official-nf-handmade-scarf','Handmade Scarf',1000,'When you gain one or more Trade Points via Real Treasure, also gain 1 Fabula Point.','Natural Fantasy Atlas · Accessory'),
  accessory('official-nf-fallen-leaf-amulet','Fallen Leaf Amulet',1500,'When using Tree of Life while in Crisis, choose an ally you can see who is also in Crisis; both benefit from HP recovery.','Natural Fantasy Atlas · Accessory'),
  accessory('official-nf-eccentrics-cookbook',"Eccentric's Cookbook",1600,'Once per rest, choose one discovered two-taste combination and use that effect instead of rolling again.','Natural Fantasy Atlas · Accessory'),

  // Techno Fantasy armor, shields, accessories
  armor('official-tf-misdirector','Misdirector',1000,false,'DEX +1','INS +1',-1,'As long as you have no shield equipped, you are Resistant to physical damage.','Techno Fantasy Atlas · Rare Armor'),
  armor('official-tf-lab-coat','Lab Coat',1500,false,'DEX +1','INS +2',-2,'If you have Secret Formula, treat its Skill Level as 2 higher, up to SL 7.','Techno Fantasy Atlas · Rare Armor'),
  armor('official-tf-biocloak','Biocloak',1800,false,'DEX +1','INS +1',0,'When a Skill requiring HP expenditure makes you halve that cost, halve it again (minimum 1).','Techno Fantasy Atlas · Rare Armor'),
  armor('official-tf-psykeleton','Psykeleton',2000,true,'11','INS +1',-3,'After Guard, if your Brainwave Clock is full, erase it completely.','Techno Fantasy Atlas · Rare Armor'),
  shield('official-tf-icebreaker','Icebreaker',700,false,'+2','—','All physical and fire damage you deal ignores Resistances.','Techno Fantasy Atlas · Rare Shield'),
  shield('official-tf-ballistic-shield','Ballistic Shield',800,false,'+2','—','Gain +1 to Accuracy Checks with ranged weapons.','Techno Fantasy Atlas · Rare Shield'),
  shield('official-tf-windshield','Windshield',1000,true,'+2','+2','While driving your personal vehicle, gain Resistance to air and ice damage.','Techno Fantasy Atlas · Rare Shield'),
  shield('official-tf-hekat-shield','Hekat Shield',2000,true,'+2','+2','Resistance to damage dealt by spells; when a spell damages you, recover 5 MP.','Techno Fantasy Atlas · Rare Shield'),
  accessory('official-tf-spare-magazine','Spare Magazine',600,'Once per scene, after an Accuracy Check with a Firearm, reroll one die.','Techno Fantasy Atlas · Accessory'),
  accessory('official-tf-flashbang-grenades','Flashbang Grenades',800,'When an elemental shard damages a creature, that creature also suffers dazed.','Techno Fantasy Atlas · Accessory'),
  accessory('official-tf-gas-mask','Gas Mask',900,'Resistance to poison damage and immunity to poisoned.','Techno Fantasy Atlas · Accessory'),
  accessory('official-tf-maverick-helmet','Maverick Helmet',1000,'At the start of your turn in conflict, if in Crisis and driving your personal vehicle, recover from one status effect.','Techno Fantasy Atlas · Accessory'),
  accessory('official-tf-ego-mask','Ego Mask',1500,'After summoning an Arcanum, you may perform a free attack with an equipped weapon; reduce HR to 0 for damage and you cannot willingly dismiss that Arcanum this turn.','Techno Fantasy Atlas · Accessory'),
  accessory('official-tf-medikit','Medikit',1500,'When a potion or spell restores HP to creatures, each target in Crisis recovers 5 additional HP.','Techno Fantasy Atlas · Accessory'),
  accessory('official-tf-portable-assembler','Portable Assembler',1500,'Once per scene, when paying an Inventory Point cost, you may halve that cost instead.','Techno Fantasy Atlas · Accessory'),
  accessory('official-tf-omnidex','Omnidex',2000,'When you Study an NPC and roll 12 or lower, treat the result as 13 unless it is a fumble.','Techno Fantasy Atlas · Accessory'),

  // Techno Fantasy weapon modules
  moduleItem('official-tf-richter-grasp','Richter Grasp',800,'Brawling','DEX + INS',0,12,'earth','Can interact with the scene as if it were a normal free hand.','Techno Fantasy Atlas · Weapon Module','Melee'),
  moduleItem('official-tf-scrapper','Scrapper',900,'Heavy','DEX + INS',1,12,'physical','Deals 5 extra damage to constructs.','Techno Fantasy Atlas · Weapon Module','Melee'),
  moduleItem('official-tf-flimvolver-battery','Flimvolver Battery',1000,'Firearm','DEX + INS',0,10,'ice','Damage dealt by this weapon ignores Resistances.','Techno Fantasy Atlas · Weapon Module','Ranged'),
  moduleItem('official-tf-emp-cannon','EMP Cannon',1100,'Firearm','DEX + INS',0,14,'bolt','If a transport hit by this weapon suffers dazed, its weapon modules cannot be operated while dazed.','Techno Fantasy Atlas · Weapon Module','Ranged'),
  moduleItem('official-tf-vanguard-pike','Vanguard Pike',1100,'Spear','DEX + INS',1,14,'physical','Deals 5 extra damage during the first round of each conflict.','Techno Fantasy Atlas · Weapon Module','Melee'),
  moduleItem('official-tf-crescens','Crescens',1200,'Sword','DEX + INS',1,12,'physical','Deals extra damage equal to Skill Level in Personal Vehicle.','Techno Fantasy Atlas · Weapon Module','Melee'),
  moduleItem('official-tf-holockaw','Holockaw',1200,'Flail','DEX + INS',1,12,'physical','Attacks can target flying creatures.','Techno Fantasy Atlas · Weapon Module','Melee'),
  moduleItem('official-tf-arbalest-mk-ii','Arbalest Mk II',1300,'Bow','DEX + INS',1,16,'physical','Deals 5 extra damage to flying creatures or creatures in midair.','Techno Fantasy Atlas · Weapon Module','Ranged'),
  moduleItem('official-tf-reactive-deflector','Reactive Deflector',1500,'Shield',undefined,0,undefined,undefined,'With Counterstrike support enabled, its effects can apply even when characters aboard the vehicle are hit by melee attacks.','Techno Fantasy Atlas · Weapon Module',undefined),
  moduleItem('official-tf-mercurialis','Mercurialis',1600,'Arcane','DEX + WLP',0,12,'fire','When a spell deals damage to one creature, it deals 5 extra damage; a vehicle with this module cannot have another weapon module enabled.','Techno Fantasy Atlas · Weapon Module','Melee'),
  moduleItem('official-tf-morphshield','Morphshield',1800,'Shield',undefined,0,undefined,undefined,'At the start of your turn while driving a vehicle, disable this module to enable another disabled Shield module; until next turn you lose all effects of a Shield module.','Techno Fantasy Atlas · Weapon Module',undefined),
  moduleItem('official-tf-plasma-rifle','Plasma Rifle',1800,'Firearm','DEX + INS',1,14,'light','Accuracy Checks with this weapon trigger a critical success if both dice show the same number and it is not a fumble.','Techno Fantasy Atlas · Weapon Module','Ranged'),
  moduleItem('official-tf-aerowitzer','Aerowitzer',2000,'Firearm','DEX + INS',0,18,'air','While driving your vehicle, gain +2 Defense; the vehicle cannot have another weapon module enabled.','Techno Fantasy Atlas · Weapon Module','Ranged'),
  moduleItem('official-tf-warp-cannon','Warp Cannon',2800,'Firearm','DEX + INS',1,18,'dark','Attacks have multi (2) and damage ignores Resistances, Immunities, and Absorption; the vehicle cannot have another weapon module enabled.','Techno Fantasy Atlas · Weapon Module','Ranged'),

  // Core artifacts
  artifact('official-core-astroscope','Astroscope','Manipulates day/night and weather within 1 travel day as powerful Entropism/Elementalism Ritual effects without MP or discipline mastery.','Core Rulebook · Artifact'),
  artifact('official-core-black-blood','Black Blood','Those who drink it remain bound to the living world after death instead of returning to the stream of souls.','Core Rulebook · Artifact'),
  artifact('official-core-dead-mans-zenit',"Dead Man's Zenit",'An indestructible coin said to command an army of ghostly pirates in exchange for the bearer’s soul.','Core Rulebook · Artifact'),
  artifact('official-core-final-feather','Final Feather','Can reportedly be destroyed to resurrect a recently fallen creature.','Core Rulebook · Artifact'),
  artifact('official-core-helm-of-thoughts','Helm of Thoughts','Senses surface thoughts and emotions; an action can read the thoughts of a specific living creature.','Core Rulebook · Artifact'),
  artifact('official-core-rod-rising-earth','Rod of Rising Earth','When used with an orichalcum ring, can lift entire landmasses and make them float and move.','Core Rulebook · Artifact'),
  artifact('official-core-soulrend','Soulrend','Can sever a consciousness from the stream of souls through an extreme Ritualism effect.','Core Rulebook · Artifact'),
  artifact('official-core-tome-of-the-gate','Tome of the Gate','Under a full moon, opens a path to the cosmos until daybreak.','Core Rulebook · Artifact'),
  artifact('official-core-voice-shard','Voice Shard','Its holder hears mysterious voices offering wisdom and guidance that no one else can hear.','Core Rulebook · Artifact'),
  artifact('official-core-wand-of-the-wilds','Wand of the Wilds','Transforms willing creatures into small beasts; the transformation can be reversed with the wand.','Core Rulebook · Artifact'),
  artifact('official-core-windscale','Windscale','Grants flight and levitation while kept against the bearer’s skin.','Core Rulebook · Artifact'),

  // High Fantasy artifacts
  artifact('official-hf-armor-of-supremacy','Armor of Supremacy','Its sentient dragon spirit can unleash heavy fire damage against one target, ignoring Immunities and Resistances.','High Fantasy Atlas · Artifact'),
  artifact('official-hf-behemoths-heart',"Behemoth's Heart",'Those accepted by the spirit within may transform into dragons and earn the respect of dragonkind.','High Fantasy Atlas · Artifact'),
  artifact('official-hf-chalice-of-youth','Chalice of Youth','Drinking from it rejuvenates the drinker into their ideal shape for a few days, while gradually altering their personality.','High Fantasy Atlas · Artifact'),
  artifact('official-hf-elemental-stones','Elemental Stones','Four stones allow MP-free, Check-free Elementalism Rituals tied to water, fire, earth, and air; combining them reveals a Fifth Element.','High Fantasy Atlas · Artifact'),
  artifact('official-hf-emarillion','Emarillion','A tome that records all events across the universe, though it chooses what readers can endure learning.','High Fantasy Atlas · Artifact'),
  artifact('official-hf-eye-of-awakening','Eye of Awakening','Awakens sealed memories and grants a Heroic Skill from a Class the owner has mastered.','High Fantasy Atlas · Artifact'),
  artifact('official-hf-lantern-of-discovery','Lantern of Discovery','Any text or glyph illuminated by its undying flame becomes understandable to the holder.','High Fantasy Atlas · Artifact'),
  artifact('official-hf-mirror-of-appearances','Mirror of Appearances','Allows its owner to freely change their features to become identical to another person.','High Fantasy Atlas · Artifact'),
  artifact('official-hf-orichalcum-chess','Orichalcum Chess','Six pieces can grow into powerful servant creatures after the owner binds their essence to the board.','High Fantasy Atlas · Artifact'),
  artifact('official-hf-red-lion-key','Red Lion Key','Universal key that opens into a protected hall suitable for rest and can exit toward distant known locations through an Entropism-like effect.','High Fantasy Atlas · Artifact'),
  artifact('official-hf-soulpiercing-spectacles','Soulpiercing Spectacles','A Skill action reveals a living creature’s abilities, history, goals, secrets, and full NPC profile.','High Fantasy Atlas · Artifact'),
  artifact('official-hf-tiara-of-control','Tiara of Control','Can control living minds, but repeated use risks the ancient entity within replacing the wearer’s consciousness.','High Fantasy Atlas · Artifact'),
  artifact('official-hf-time-wand','Time Wand','Moves an object or living being backward or forward through time without changing location.','High Fantasy Atlas · Artifact'),
  artifact('official-hf-timebreaker-bracers','Timebreaker Bracers','Creates a sphere in which time continues while the outside world stops briefly; each use permanently reduces the wearer’s max HP and MP by 5.','High Fantasy Atlas · Artifact'),
  artifact('official-hf-wine-of-sorrow','Wine of Sorrow','A willing drinker is destroyed body and soul; legends claim surviving it would grant godlike freedom from pain and emotion.','High Fantasy Atlas · Artifact'),

  // Natural Fantasy artifacts
  artifact('official-nf-cardinal-kylix','Cardinal Kylix','A legendary cup tied to civilization-ending calamities and the power to extinguish opposition.','Natural Fantasy Atlas · Artifact'),
  artifact('official-nf-egg-of-illuyanka','Egg of Illuyanka','An ancient egg said to hatch into a primordial creature; threatening it may cause its guardian to manifest.','Natural Fantasy Atlas · Artifact'),
  artifact('official-nf-gemshorn-of-tranquility','Gemshorn of Tranquility','Playing it calms beasts, monsters, and plants without MP or a Magic Check, though conflicts still require filling a Clock.','Natural Fantasy Atlas · Artifact'),
  artifact('official-nf-havenbell','Havenbell','After aiding a silkie, ringing the bell can call that same silkie to help; repeated misuse can cause the artifact to vanish.','Natural Fantasy Atlas · Artifact'),
  artifact('official-nf-keys-of-the-harmonist','Keys of the Harmonist','Nine keys tied to legendary heroes; each can summon a spirit echo of a matching hero.','Natural Fantasy Atlas · Artifact'),
  artifact('official-nf-moon-mirror','Moon Mirror','Once per month under moonlight, performs Verdant Sway without MP; its reflected light can manipulate plant growth.','Natural Fantasy Atlas · Artifact'),
  artifact('official-nf-reidys-journal',"Reidy's Journal",'A journal that records regional history and supports structured research into unresolved mysteries.','Natural Fantasy Atlas · Artifact'),
  artifact('official-nf-resin-tear','Resin Tear','A carved amber sword linked to ancient warriors; its legend is tied to lightning-like power and ancestral military tradition.','Natural Fantasy Atlas · Artifact'),
  artifact('official-nf-seal-second-sun','Seal of the Second Sun','A relic of a lost empire connected to forgotten scholars, collectors, and sealed necropolis lore.','Natural Fantasy Atlas · Artifact'),
  artifact('official-nf-skull-salamander-goddess','Skull of the Salamander-Goddess','A massive salamander skull believed to be tied to the return or awakening of an ancient fire divinity.','Natural Fantasy Atlas · Artifact'),
  artifact('official-nf-sky-oil','Sky Oil','A mysterious green liquid that falls from red clouds and can cause profound biological changes and mutations.','Natural Fantasy Atlas · Artifact'),
  artifact('official-nf-three-knot-rope','Three-Knot Rope','Untying its knots enables powerful wind and elemental Ritual effects without spending MP.','Natural Fantasy Atlas · Artifact'),
  artifact('official-nf-tome-of-the-meteor','Tome of the Meteor','A strange mechanism embedded in a book that predicts or records improbabilities, anomalies, and meteor-like events.','Natural Fantasy Atlas · Artifact'),
  artifact('official-nf-undoven','Undoven','Once per rest, can disassemble one piece of equipment and reassemble its combined value into two different material items.','Natural Fantasy Atlas · Artifact'),
  artifact('official-nf-white-mask-fragment','White Mask Fragment','A surviving fragment of a legendary mask whose courage and spirit repel undead; no undead except Villains may harm its wearer.','Natural Fantasy Atlas · Artifact'),

  // Techno Fantasy artifacts
  artifact('official-tf-aion','Aion','A colossal mecha that requires a large crew; powering it yields overwhelming force but terrible consequences for its pilots.','Techno Fantasy Atlas · Artifact'),
  artifact('official-tf-alien-umbilical-cord','Alien Umbilical Cord','Living alien tissue whose genetic material may strengthen bodies through mutation and irreversible change.','Techno Fantasy Atlas · Artifact'),
  artifact('official-tf-ark-of-hope','Ark of Hope','An ancient alien vessel containing traces of a sleeping consciousness and sealed secrets.','Techno Fantasy Atlas · Artifact'),
  artifact('official-tf-black-gear','The Black Gear','A shadow-metal gear that can spread corruption into damaged machinery, creating obedient soldiers.','Techno Fantasy Atlas · Artifact'),
  artifact('official-tf-cloning-vat','Cloning Vat','Can clone a living creature exactly, but repeated cloning gradually degrades its vitality.','Techno Fantasy Atlas · Artifact'),
  artifact('official-tf-demon-downloader','Demon Downloader','Can bind a demon through a Ritualism contract and grant access to specific spells or Ritual disciplines.','Techno Fantasy Atlas · Artifact'),
  artifact('official-tf-euscal-folder','Euscal Inc. Folder','An incriminating archive capable of exposing a megacorporation’s crimes, while making its holder a target.','Techno Fantasy Atlas · Artifact'),
  artifact('official-tf-m-day-model','M-Day Model','A legendary sword that becomes a rare transforming custom weapon for a worthy wielder and can reshape a battlefield through Entropism-like effects.','Techno Fantasy Atlas · Artifact'),
  artifact('official-tf-nephele-plans','Nephele System Plans','Plans revealing a space station’s ruthless design, weak points, and hidden purpose.','Techno Fantasy Atlas · Artifact'),
  artifact('official-tf-pulsar-morphmodule','Pulsar Morphmodule','Fuses with transportation, reshaping it into an aerodynamic exoskeleton and eventually enabling lightspeed movement.','Techno Fantasy Atlas · Artifact'),
  artifact('official-tf-scarlet-key','Scarlet Key','A cybernetic access card that can open a door in reality and route connected minds or machines through a cyberspace network.','Techno Fantasy Atlas · Artifact'),
  artifact('official-tf-spiritual-reconstruction-protocol','Spiritual Reconstruction Protocol','Draws on the soul network to reshape people and memories, with paradoxical effects across space and time.','Techno Fantasy Atlas · Artifact'),
  artifact('official-tf-universal-source-code','Universal Source Code','A living code-fragment believed to reveal the spiritual structure of the known world.','Techno Fantasy Atlas · Artifact'),
  artifact('official-tf-warsplice-engine','Warsplice Engine','A massive force-projection weapon that partitions space and creates destructive spatial distortions.','Techno Fantasy Atlas · Artifact'),
  artifact('official-tf-world-tear','World Tear','A cracked stone tied to an ancient magic wound; enables powerful Spiritism communication with the world itself.','Techno Fantasy Atlas · Artifact'),
]
